import { useRef, useState } from 'react';
import drawer from './opsDrawerShared.module.css';
import styles from './OperatingMessagesPage.module.css';
import { useOutsideClose } from '../../lib/useOutsideClose';
import type { MessageStatus, OperatingMessage } from './messageData';

type Tab = 'basic' | 'content' | 'target' | 'result' | 'history';
interface Props { message: OperatingMessage; onClose: () => void; onEdit: () => void; onClone: () => void; onCancel: () => void; onRetry: () => void; onPreview: () => void }
const STATUS_META: Record<MessageStatus, { bg: string; fg: string }> = { 작성중: { bg: '#f4f4f5', fg: '#52525b' }, '발송 예정': { bg: '#eff6ff', fg: '#2563eb' }, 발송중: { bg: '#fff7ed', fg: '#c2410c' }, '발송 완료': { bg: '#ecfdf5', fg: '#047857' }, '일부 실패': { bg: '#fff7ed', fg: '#c2410c' }, 실패: { bg: '#fef2f2', fg: '#dc2626' }, 중지: { bg: '#f4f4f5', fg: '#71717a' } };

export function OperatingMessageDetailDrawer({ message, onClose, onEdit, onClone, onCancel, onRetry, onPreview }: Props) {
  const [tab, setTab] = useState<Tab>('basic');
  const meta = STATUS_META[message.status];
  const total = message.result.success + message.result.failed;
  const successRate = total ? message.result.success / total * 100 : 0;
  const asideRef = useRef<HTMLElement>(null);
  useOutsideClose(asideRef, onClose);
  return <aside ref={asideRef} className={`${drawer.aside} ${styles.detailDrawer}`}>
    <div className={drawer.head}><div className={drawer.headRow}><div className={drawer.headBody}><div className={drawer.eyebrow}>{message.id} · 운영 메시지 상세</div><div className={drawer.titleRow}><h2 className={drawer.title}>{message.managementName}</h2><span className={drawer.badge} style={{ background: meta.bg, color: meta.fg }}>{message.status}</span></div><div className={drawer.sub}>{message.type} · {message.channels.join(', ')} · {message.targetType}</div></div><button type="button" className={drawer.closeBtn} onClick={onClose}>✕</button></div>
      <div className={styles.summaryGrid}><div><span>예상 대상</span><strong>{message.estimatedTargets.toLocaleString()}명</strong></div><div><span>실제 대상</span><strong>{message.actualTargets ? `${message.actualTargets.toLocaleString()}명` : '-'}</strong></div><div><span>예약 일시</span><strong>{message.scheduledAt ?? '-'}</strong></div><div><span>발송 일시</span><strong>{message.sentAt ?? '-'}</strong></div></div>
      <div className={drawer.actionRow}>{['작성중', '발송 예정'].includes(message.status) && <button type="button" className={drawer.actionLink} onClick={onEdit}>수정</button>}<button type="button" className={drawer.actionLink} onClick={onClone}>복제</button><button type="button" className={drawer.actionLink} onClick={onPreview}>미리보기</button>{['실패', '일부 실패'].includes(message.status) && <button type="button" className={drawer.primaryBtn} onClick={onRetry}>실패 대상 재발송</button>}{['발송 예정', '발송중'].includes(message.status) && <button type="button" className={drawer.dangerBtn} onClick={onCancel}>{message.status === '발송 예정' ? '발송 취소' : '발송 중지'}</button>}</div>
      <div className={drawer.tabs}>{([['basic', '기본 정보'], ['content', '메시지 내용'], ['target', '대상 설정'], ['result', '발송 결과'], ['history', '작업 이력']] as [Tab, string][]).map(([key, label]) => <button key={key} type="button" className={`${drawer.tabBtn} ${tab === key ? drawer.tabActive : ''}`} onClick={() => setTab(key)}>{label}</button>)}</div>
    </div>
    <div className={drawer.scroll}>
      {tab === 'basic' && <div className={drawer.fieldBox}><Info label="메시지 ID" value={message.id}/><Info label="메시지명" value={message.managementName}/><Info label="메시지 유형" value={message.type}/><Info label="발송 채널" value={message.channels.join(', ')}/><Info label="대상 유형" value={message.targetType}/><Info label="발송 상태" value={message.status}/><Info label="등록자" value={message.createdBy}/><Info label="등록일" value={message.createdAt}/><Info label="최근 수정일" value={message.updatedAt}/></div>}
      {tab === 'content' && <><div className={drawer.sectionTitle}>사용자 노출 제목</div><div className={drawer.bodyText}>{message.title}</div><div className={drawer.sectionTitle}>메시지 내용</div><div className={styles.messagePaper}>{message.content}</div><div className={drawer.sectionTitleLoose}>발송 채널</div><div className={styles.channelList}>{message.channels.map((channel) => <em key={channel} className={styles.channelTag}>{channel}</em>)}</div></>}
      {tab === 'target' && <><div className={drawer.fieldBox}><Info label="대상 유형" value={message.targetType}/><Info label="대상 조건" value={message.targetDetail}/><Info label="예상 발송 대상" value={`${message.estimatedTargets.toLocaleString()}명`}/><Info label="실제 발송 대상" value={message.actualTargets ? `${message.actualTargets.toLocaleString()}명` : '-'}/></div><div className={drawer.bodyText}>발송 시점에 탈퇴, 휴면, 채널 수신 가능 여부를 다시 검증하므로 예상 대상과 실제 대상은 달라질 수 있습니다.</div></>}
      {tab === 'result' && <>{total === 0 ? <div className={drawer.bodyText}>아직 발송 결과가 없습니다. 발송이 완료되면 채널별 결과와 실패 사유가 집계됩니다.</div> : <><div className={styles.resultGrid}><div><span>대상</span><strong>{total.toLocaleString()}</strong></div><div><span>성공</span><strong>{message.result.success.toLocaleString()}</strong></div><div><span>실패</span><strong>{message.result.failed.toLocaleString()}</strong></div><div><span>성공률</span><strong>{successRate.toFixed(1)}%</strong></div></div><div className={styles.progress}><span style={{ width: `${successRate}%` }}/></div><div className={styles.channelMetrics}><div className={styles.channelMetric}><span>열람 / 오픈</span><strong>{message.result.opened.toLocaleString()}</strong></div><div className={styles.channelMetric}><span>클릭</span><strong>{message.result.clicked.toLocaleString()}</strong></div><div className={styles.channelMetric}><span>클릭률</span><strong>{message.result.success ? (message.result.clicked / message.result.success * 100).toFixed(1) : '0.0'}%</strong></div></div>{message.failures.length > 0 && <><div className={drawer.sectionTitleLoose}>실패 내역 {message.failures.length}건</div><div className={styles.failureTable}><div className={styles.failureRow}><span>사용자</span><span>채널</span><span>실패 사유</span><span>발생일</span></div>{message.failures.map((failure, index) => <div className={styles.failureRow} key={`${failure.userId}-${index}`}><span>{failure.userId}</span><span>{failure.channel}</span><span>{failure.reason}</span><span>{failure.at}</span></div>)}</div></>}</>}</>}
      {tab === 'history' && message.history.map((item, index) => <div key={`${item.at}-${index}`} className={drawer.timelineItem}><span className={drawer.timelineDot}/><div className={drawer.timelineBody}><div className={drawer.timelineRow}><strong className={drawer.timelineTitle}>{item.action}</strong><span className={drawer.timelineWhen}>{item.at}</span></div><div className={drawer.timelineDetail}>{item.detail} · {item.actor}</div></div></div>)}
    </div>
  </aside>;
}

function Info({ label, value }: { label: string; value: string }) { return <div className={drawer.fieldRow}><span className={drawer.fieldLabel}>{label}</span><strong className={drawer.fieldValue}>{value}</strong></div>; }
