import { useState } from 'react';
import drawer from '../ops/opsDrawerShared.module.css';
import styles from './AdminMemosPage.module.css';
import { MEMO_ADMINS, MEMO_TARGET_TYPES, MEMO_TYPES, followUpState, type AdminMemoEntry, type MemoTargetType, type MemoType, type PinScope } from './adminMemosData';

type Tab = 'memo' | 'context' | 'followup' | 'version' | 'history';
interface Props { initial: AdminMemoEntry; isNew: boolean; startEditing?: boolean; onClose: () => void; onSave: (item: AdminMemoEntry, reason: string) => void; onComplete: (item: AdminMemoEntry, result: string) => void; onToggleImportant: (item: AdminMemoEntry) => void; onTogglePin: (item: AdminMemoEntry) => void; onHide: (item: AdminMemoEntry) => void; onRecover: (item: AdminMemoEntry) => void; }

export function AdminMemoDrawer({ initial, isNew, startEditing = false, onClose, onSave, onComplete, onToggleImportant, onTogglePin, onHide, onRecover }: Props) {
  const [draft, setDraft] = useState(initial); const [editing, setEditing] = useState(isNew || startEditing); const [tab, setTab] = useState<Tab>('memo'); const [reason, setReason] = useState(''); const [followResult, setFollowResult] = useState(''); const [error, setError] = useState('');
  const state = followUpState(draft); const set = <K extends keyof AdminMemoEntry>(key: K, value: AdminMemoEntry[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const save = () => { if (!draft.targetId.trim() || !draft.customerId.trim() || !draft.content.trim()) return setError('관련 대상, 고객, 메모 내용은 필수입니다.'); if (draft.followUpRequired && !draft.followUpAt) return setError('후속 확인 예정일을 입력해 주세요.'); if (!isNew && !reason.trim()) return setError('수정 이력을 위해 수정 사유를 입력해 주세요.'); onSave({ ...draft, targetId: draft.targetId.trim(), customerId: draft.customerId.trim(), customerName: draft.customerName.trim() || draft.customerId.trim() }, reason.trim() || '관리자 메모 등록'); };
  return <aside className={`${drawer.aside} ${styles.memoDrawer}`}>
    <div className={drawer.head}><div className={drawer.headRow}><div className={drawer.headBody}><div className={drawer.eyebrow}>{isNew ? '신규 내부 기록' : draft.id}</div><div className={drawer.titleRow}><h2 className={drawer.title}>{isNew ? '관리자 메모 등록' : draft.type}</h2>{draft.important && <span className={styles.importantBadge}>★ 중요</span>}{draft.pinScope !== '없음' && <span className={styles.pinBadge}>📌 {draft.pinScope}</span>}{draft.hidden && <span className={drawer.badge} style={{ background:'#f4f4f5',color:'#71717a' }}>숨김</span>}</div>{!isNew && <div className={drawer.sub}>{draft.author} · {draft.authorTeam} · {draft.createdAt}</div>}</div><button type="button" className={drawer.closeBtn} onClick={onClose}>✕</button></div>
      {!isNew && <div className={drawer.actionRow}><button type="button" className={drawer.actionLink} onClick={()=>{setEditing((current)=>!current);setTab('memo');}}>{editing?'수정 취소':'수정'}</button><button type="button" className={drawer.actionLink} onClick={()=>onToggleImportant(draft)}>{draft.important?'중요 해제':'중요 설정'}</button><button type="button" className={drawer.actionLink} onClick={()=>onTogglePin(draft)}>{draft.pinScope==='없음'?'고정':'고정 해제'}</button><span className={drawer.spacer}/>{draft.hidden?<button type="button" className={drawer.primaryBtn} onClick={()=>onRecover(draft)}>복구</button>:<button type="button" className={drawer.dangerBtn} onClick={()=>onHide(draft)}>메모 숨김</button>}</div>}
      <div className={drawer.tabs}>{([['memo','메모 정보'],['context','관련 Context'],['followup','후속 확인'],['version',`수정 Version ${draft.versions.length}`],['history','처리 이력']] as [Tab,string][]).map(([key,label])=><button key={key} type="button" className={`${drawer.tabBtn} ${tab===key?drawer.tabActive:''}`} onClick={()=>setTab(key)}>{label}</button>)}</div>
    </div>
    <div className={drawer.scroll}>
      <div className={styles.privateNotice}>🔒 고객에게 절대 노출되지 않는 내부 기록입니다. 객관적인 상담·업무 사실만 작성해 주세요.</div>
      {tab==='memo'&&<><Section title="관련 대상"><div className={styles.formGrid}><Field label="관련 대상 유형 *"><select disabled={!editing} value={draft.targetType} onChange={(e)=>set('targetType',e.target.value as MemoTargetType)}>{MEMO_TARGET_TYPES.map((value)=><option key={value}>{value}</option>)}</select></Field><Field label="대상 ID *"><input disabled={!editing} value={draft.targetId} onChange={(e)=>set('targetId',e.target.value)} placeholder="QNA-00182"/></Field><Field label="고객 ID *"><input disabled={!editing} value={draft.customerId} onChange={(e)=>set('customerId',e.target.value)} placeholder="user01"/></Field><Field label="고객명"><input disabled={!editing} value={draft.customerName} onChange={(e)=>set('customerName',e.target.value)} placeholder="김민수"/></Field></div></Section><Section title="메모 내용"><div className={styles.formGrid}><Field label="메모 유형 *"><select disabled={!editing} value={draft.type} onChange={(e)=>set('type',e.target.value as MemoType)}>{MEMO_TYPES.map((value)=><option key={value}>{value}</option>)}</select></Field><Field label="고정 범위"><select disabled={!editing} value={draft.pinScope} onChange={(e)=>set('pinScope',e.target.value as PinScope)}><option>없음</option><option>고객 고정</option><option>문의 고정</option></select></Field></div><label className={styles.checkLine}><input type="checkbox" disabled={!editing} checked={draft.important} onChange={(e)=>set('important',e.target.checked)}/> 반드시 확인해야 하는 중요 메모</label><textarea className={styles.memoEditor} disabled={!editing} value={draft.content} onChange={(e)=>set('content',e.target.value)} placeholder="내부 공유가 필요한 객관적인 사실을 기록하세요."/><div className={styles.writingGuide}>사람을 평가하거나 낙인찍는 표현, 불필요한 개인정보는 입력하지 마세요. 중요한 사실 변경은 기존 내용을 덮어쓰기보다 새 메모로 추가하는 것을 권장합니다.</div>{editing&&!isNew&&<Field label="수정 사유 *" hint="변경 전·후 내용과 함께 보존"><input value={reason} onChange={(e)=>setReason(e.target.value)} placeholder="오타 수정 또는 내용 보완 사유"/></Field>}</Section></>}
      {tab==='context'&&<><div className={styles.customerCard}><div><span>고객</span><strong>{draft.customerName} · {draft.customerId}</strong><button type="button">고객 보기 ↗</button></div>{draft.customerCompany&&<div><span>회사</span><strong>{draft.customerCompany}</strong></div>}<div><span>Context</span><strong>{draft.targetSummary||'-'}</strong><em>{draft.targetStatus||'-'}</em></div></div><Section title="연결 업무">{draft.relatedInquiryId&&<ContextRow label="1:1 문의" id={draft.relatedInquiryId} action={()=>window.location.assign('/cs/inquiries')}/>} {draft.relatedConsultationId&&<ContextRow label="상담" id={draft.relatedConsultationId} action={()=>window.location.assign('/cs/consultations')}/>} {draft.relatedOrderId&&<ContextRow label="주문" id={draft.relatedOrderId}/>} {!draft.relatedInquiryId&&!draft.relatedConsultationId&&!draft.relatedOrderId&&<div className={drawer.emptyInline}>추가로 연결된 업무가 없습니다.</div>}</Section><Section title="같은 고객의 최근 메모"><div className={styles.relatedMemo}><span>08.20</span><strong>이메일 연락 선호</strong><em>고객 요청사항</em></div><div className={styles.relatedMemo}><span>08.12</span><strong>이전 상담 후속 확인 완료</strong><em>상담 참고</em></div><button type="button" className={styles.fullLink}>이 고객의 전체 메모 보기</button></Section></>}
      {tab==='followup'&&<><div className={`${styles.followHero} ${styles[`follow_${state}`]}`}><span>후속 확인 상태</span><strong>{state==='경과'?'⚠ 확인 예정시간 경과':state}</strong>{draft.followUpAt&&<p>확인 예정 {draft.followUpAt} · 담당 {draft.followUpAssignee}</p>}{draft.followUpCompletedAt&&<p>완료 {draft.followUpCompletedAt} · {draft.followUpCompletedBy}</p>}</div>{editing&&<Section title="후속 확인 설정"><label className={styles.checkLine}><input type="checkbox" checked={draft.followUpRequired} onChange={(e)=>set('followUpRequired',e.target.checked)}/> 후속 확인 필요</label>{draft.followUpRequired&&<div className={styles.formGrid}><Field label="확인 예정"><input type="datetime-local" value={draft.followUpAt?.replace(' ','T')??''} onChange={(e)=>set('followUpAt',e.target.value?e.target.value.replace('T',' '):null)}/></Field><Field label="후속 담당자"><select value={draft.followUpAssignee??''} onChange={(e)=>set('followUpAssignee',e.target.value||null)}><option value="">미지정</option>{MEMO_ADMINS.map((value)=><option key={value}>{value}</option>)}</select></Field></div>}</Section>}{draft.followUpRequired&&!draft.followUpCompletedAt&&<Section title="확인 결과 기록"><textarea className={styles.followResult} value={followResult} onChange={(e)=>setFollowResult(e.target.value)} placeholder="확인한 결과를 기록하세요. 완료 시 원 메모는 유지되고 새 이력이 추가됩니다."/><button type="button" className={styles.primaryButton} disabled={!followResult.trim()} onClick={()=>onComplete(draft,followResult)}>확인 완료</button></Section>}</>}
      {tab==='version'&&<>{draft.versions.slice().reverse().map((version,index)=><div key={version.version} className={`${styles.versionCard} ${index===0?styles.currentVersion:''}`}><div><strong>V{version.version} {index===0&&<span>현재</span>}</strong><em>{version.at} · {version.by}</em></div><p>{version.reason}</p><pre>{version.content}</pre></div>)}{!draft.versions.length&&<div className={drawer.emptyInline}>등록 후 Version이 생성됩니다.</div>}</>}
      {tab==='history'&&<>{draft.history.slice().reverse().map((item)=><div key={item.id} className={drawer.timelineItem}><span className={drawer.timelineDot}/><div className={drawer.timelineBody}><div className={drawer.timelineRow}><strong className={drawer.timelineTitle}>{item.action}</strong><span className={drawer.timelineWhen}>{item.at}</span></div><div className={drawer.timelineDetail}>{item.by}{item.detail?` · ${item.detail}`:''}</div></div></div>)}</>}
      {error&&<div className={styles.formError}>{error}</div>}
    </div>
    {editing&&<div className={drawer.footer}><button type="button" className={drawer.editCancel} onClick={isNew?onClose:()=>{setDraft(initial);setEditing(false);}}>취소</button><button type="button" className={drawer.editConfirm} onClick={save}>{isNew?'메모 등록':'수정 저장'}</button></div>}
  </aside>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className={styles.formSection}><h3>{title}</h3>{children}</section>}
function Field({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}){return <label className={styles.formField}><span>{label}{hint&&<small>{hint}</small>}</span>{children}</label>}
function ContextRow({label,id,action}:{label:string;id:string;action?:()=>void}){return <div className={styles.contextRow}><span>{label}</span><strong>{id}</strong><em>연결됨</em><button type="button" onClick={action}>보기 ↗</button></div>}
