export type MemoType = '상담 참고' | '업무 확인' | '고객 요청사항' | '내부 전달' | '처리 주의사항' | '후속 확인' | '정책 확인' | '기타';
export type MemoTargetType = '1:1 문의' | '상담' | '고객' | '주문' | '결제' | '배송';
export type PinScope = '없음' | '고객 고정' | '문의 고정';

export interface MemoVersion { version: number; at: string; by: string; content: string; reason: string; }
export interface MemoHistory { id: string; at: string; by: string; action: string; detail?: string; }
export interface AdminMemoEntry {
  id: string; content: string; type: MemoType; important: boolean; pinScope: PinScope; targetType: MemoTargetType; targetId: string;
  customerId: string; customerName: string; customerCompany?: string; relatedInquiryId?: string; relatedConsultationId?: string; relatedOrderId?: string;
  targetSummary: string; targetStatus: string; author: string; authorTeam: string; createdAt: string; updatedAt: string;
  followUpRequired: boolean; followUpAt: string | null; followUpAssignee: string | null; followUpCompletedAt: string | null; followUpCompletedBy: string | null;
  hidden: boolean; hiddenReason?: string; sensitiveReview: boolean; versions: MemoVersion[]; history: MemoHistory[];
}

export const MEMO_TYPES: MemoType[] = ['상담 참고', '업무 확인', '고객 요청사항', '내부 전달', '처리 주의사항', '후속 확인', '정책 확인', '기타'];
export const MEMO_TARGET_TYPES: MemoTargetType[] = ['1:1 문의', '상담', '고객', '주문', '결제', '배송'];
export const MEMO_TEAMS = ['일반 CS팀', '주문 CS팀', '결제 CS팀', '배송 CS팀', '정산 CS팀'];
export const MEMO_ADMINS = ['admin01', 'admin02', 'admin03', 'admin04'];
const ver = (content: string): MemoVersion[] => [{ version: 1, at: '2026-08-24 10:00', by: 'admin01', content, reason: '메모 등록' }];
const hist = (id: string, at = '2026-08-24 10:00', by = 'admin01'): MemoHistory[] => [{ id: `${id}-H1`, at, by, action: '관리자 메모 등록' }];

export const ADMIN_MEMOS: AdminMemoEntry[] = [
  { id: 'MEMO-00182', content: '배송사 회신 대기중. 확인 후 고객에게 재안내 필요. 배송 완료 전 확정적인 일정 안내는 피해주세요.', type: '후속 확인', important: true, pinScope: '문의 고정', targetType: '1:1 문의', targetId: 'QNA-00182', customerId: 'user01', customerName: '김민수', customerCompany: '마켓원', relatedInquiryId: 'QNA-00182', relatedConsultationId: 'CS-00382', relatedOrderId: 'ORD-00582', targetSummary: '배송 > 배송 지연', targetStatus: '처리중', author: 'admin01', authorTeam: '배송 CS팀', createdAt: '2026-08-24 10:45', updatedAt: '2026-08-24 10:45', followUpRequired: true, followUpAt: '2026-08-24 13:00', followUpAssignee: 'admin01', followUpCompletedAt: null, followUpCompletedBy: null, hidden: false, sensitiveReview: false, versions: ver('배송사 회신 대기중. 확인 후 고객에게 재안내 필요.'), history: hist('MEMO-00182', '2026-08-24 10:45') },
  { id: 'MEMO-00181', content: 'PG사 취소 전문은 정상 수신됨. 카드사 매입 취소 반영 여부를 내일 오전 다시 확인할 것.', type: '업무 확인', important: true, pinScope: '없음', targetType: '상담', targetId: 'CS-00379', customerId: 'shop04', customerName: '최지우', customerCompany: '샵04', relatedInquiryId: 'QNA-00179', relatedConsultationId: 'CS-00379', relatedOrderId: 'ORD-00566', targetSummary: '취소 / 환불 > 환불 지연', targetStatus: '후속 처리 필요', author: 'admin02', authorTeam: '결제 CS팀', createdAt: '2026-08-24 09:15', updatedAt: '2026-08-24 09:15', followUpRequired: true, followUpAt: '2026-08-25 10:00', followUpAssignee: 'admin02', followUpCompletedAt: null, followUpCompletedBy: null, hidden: false, sensitiveReview: false, versions: ver('PG사 취소 전문은 정상 수신됨. 카드사 반영 여부 재확인.'), history: hist('MEMO-00181', '2026-08-24 09:15', 'admin02') },
  { id: 'MEMO-00180', content: '고객은 이메일 연락을 선호하며 전화 연락은 평일 오후 2시 이후 요청함.', type: '고객 요청사항', important: true, pinScope: '고객 고정', targetType: '고객', targetId: 'user01', customerId: 'user01', customerName: '김민수', customerCompany: '마켓원', targetSummary: '고객 연락 선호 정보', targetStatus: '정상', author: 'admin03', authorTeam: '일반 CS팀', createdAt: '2026-08-20 14:20', updatedAt: '2026-08-20 14:25', followUpRequired: false, followUpAt: null, followUpAssignee: null, followUpCompletedAt: null, followUpCompletedBy: null, hidden: false, sensitiveReview: false, versions: [{ version: 1, at: '2026-08-20 14:20', by: 'admin03', content: '이메일 연락 선호.', reason: '메모 등록' }, { version: 2, at: '2026-08-20 14:25', by: 'admin03', content: '고객은 이메일 연락을 선호하며 전화 연락은 평일 오후 2시 이후 요청함.', reason: '연락 가능 시간 보완' }], history: [...hist('MEMO-00180', '2026-08-20 14:20', 'admin03'), { id: 'MEMO-00180-H2', at: '2026-08-20 14:25', by: 'admin03', action: '메모 내용 수정', detail: '연락 가능 시간 보완' }] },
  { id: 'MEMO-00179', content: '택배사 회수 접수 누락 확인. 재접수 번호 SHP-00161 기준으로 회수 완료 여부 확인 필요.', type: '후속 확인', important: false, pinScope: '없음', targetType: '배송', targetId: 'SHP-00161', customerId: 'market05', customerName: '정하늘', customerCompany: '마켓05', relatedInquiryId: 'QNA-00178', relatedConsultationId: 'CS-00378', relatedOrderId: 'ORD-00542', targetSummary: '파손 상품 교환 회수', targetStatus: '회수 완료', author: 'admin01', authorTeam: '배송 CS팀', createdAt: '2026-08-23 09:20', updatedAt: '2026-08-23 09:20', followUpRequired: true, followUpAt: '2026-08-23 14:00', followUpAssignee: 'admin01', followUpCompletedAt: '2026-08-23 13:52', followUpCompletedBy: 'admin01', hidden: false, sensitiveReview: false, versions: ver('택배사 회수 접수 누락 확인. 회수 완료 여부 확인 필요.'), history: [...hist('MEMO-00179', '2026-08-23 09:20'), { id: 'MEMO-00179-H2', at: '2026-08-23 13:52', by: 'admin01', action: '후속 확인 완료', detail: '회수 완료 확인' }] },
  { id: 'MEMO-00178', content: '출고 완료 상태라 시스템 배송지 변경 불가. 고객에게 배송사 수령지 변경 절차만 안내함.', type: '정책 확인', important: false, pinScope: '없음', targetType: '1:1 문의', targetId: 'QNA-00176', customerId: 'store07', customerName: '오세훈', customerCompany: '스토어07', relatedInquiryId: 'QNA-00176', relatedConsultationId: 'CS-00376', relatedOrderId: 'ORD-00580', targetSummary: '배송 > 배송지 변경', targetStatus: '처리 완료', author: 'admin02', authorTeam: '배송 CS팀', createdAt: '2026-08-20 12:05', updatedAt: '2026-08-20 12:05', followUpRequired: false, followUpAt: null, followUpAssignee: null, followUpCompletedAt: null, followUpCompletedBy: null, hidden: false, sensitiveReview: false, versions: ver('출고 완료 상태라 시스템 배송지 변경 불가.'), history: hist('MEMO-00178', '2026-08-20 12:05', 'admin02') },
  { id: 'MEMO-00177', content: '세금계산서 수신 이메일 정정 완료. 7월 거래분 재발송 결과 확인함.', type: '상담 참고', important: false, pinScope: '없음', targetType: '상담', targetId: 'CS-00375', customerId: 'corp08', customerName: '문가영', customerCompany: '코퍼레이션08', relatedConsultationId: 'CS-00375', targetSummary: '정산 > 세금계산서', targetStatus: '해결', author: 'admin04', authorTeam: '정산 CS팀', createdAt: '2026-08-19 14:42', updatedAt: '2026-08-19 14:42', followUpRequired: false, followUpAt: null, followUpAssignee: null, followUpCompletedAt: null, followUpCompletedBy: null, hidden: false, sensitiveReview: false, versions: ver('세금계산서 수신 이메일 정정 완료.'), history: hist('MEMO-00177', '2026-08-19 14:42', 'admin04') },
  { id: 'MEMO-00176', content: '결제 담당팀에 중복 승인 건 우선 확인 요청. 고객에게 취소 확정 전 환불 완료 표현 사용 금지.', type: '처리 주의사항', important: true, pinScope: '문의 고정', targetType: '1:1 문의', targetId: 'QNA-00181', customerId: 'buyer02', customerName: '박서연', customerCompany: '오피스랩', relatedInquiryId: 'QNA-00181', relatedOrderId: 'ORD-00581', targetSummary: '결제 > 중복 결제', targetStatus: '접수', author: 'admin02', authorTeam: '결제 CS팀', createdAt: '2026-08-24 09:55', updatedAt: '2026-08-24 09:55', followUpRequired: true, followUpAt: '2026-08-24 14:30', followUpAssignee: 'admin02', followUpCompletedAt: null, followUpCompletedBy: null, hidden: false, sensitiveReview: false, versions: ver('중복 승인 건 우선 확인 요청.'), history: hist('MEMO-00176', '2026-08-24 09:55', 'admin02') },
  { id: 'MEMO-00175', content: '동일 내용이 중복 등록되어 일반 조회에서 숨김 처리함.', type: '기타', important: false, pinScope: '없음', targetType: '상담', targetId: 'CS-00381', customerId: 'buyer02', customerName: '박서연', customerCompany: '오피스랩', relatedConsultationId: 'CS-00381', targetSummary: '결제 > 결제 오류', targetStatus: '안내 완료', author: 'admin02', authorTeam: '결제 CS팀', createdAt: '2026-08-23 16:30', updatedAt: '2026-08-23 16:35', followUpRequired: false, followUpAt: null, followUpAssignee: null, followUpCompletedAt: null, followUpCompletedBy: null, hidden: true, hiddenReason: '동일 내용 중복 등록', sensitiveReview: false, versions: ver('PG 취소 확인 필요.'), history: [...hist('MEMO-00175', '2026-08-23 16:30', 'admin02'), { id: 'MEMO-00175-H2', at: '2026-08-23 16:35', by: 'admin02', action: '메모 숨김', detail: '동일 내용 중복 등록' }] },
  { id: 'MEMO-00174', content: '고객이 메모 본문에 개인 연락처 원문을 기재해 전달함. 민감정보 포함 여부 관리자 검토 필요.', type: '내부 전달', important: false, pinScope: '없음', targetType: '고객', targetId: 'office06', customerId: 'office06', customerName: '한소희', customerCompany: '오피스06', targetSummary: '고객 개인정보 검토', targetStatus: '정상', author: 'admin03', authorTeam: '일반 CS팀', createdAt: '2026-08-24 11:35', updatedAt: '2026-08-24 11:35', followUpRequired: true, followUpAt: '2026-08-24 17:00', followUpAssignee: 'admin03', followUpCompletedAt: null, followUpCompletedBy: null, hidden: false, sensitiveReview: true, versions: ver('민감정보 포함 여부 관리자 검토 필요.'), history: hist('MEMO-00174', '2026-08-24 11:35', 'admin03') },
];

const DEMO_NOW = new Date('2026-08-24T14:00:00').getTime();
export function followUpState(item: AdminMemoEntry): '없음' | '예정' | '경과' | '완료' { if (!item.followUpRequired) return '없음'; if (item.followUpCompletedAt) return '완료'; if (item.followUpAt && new Date(item.followUpAt.replace(' ', 'T')).getTime() < DEMO_NOW) return '경과'; return '예정'; }
export function newAdminMemo(): AdminMemoEntry { return { id: `MEMO-${Date.now()}`, content: '', type: '상담 참고', important: false, pinScope: '없음', targetType: '1:1 문의', targetId: '', customerId: '', customerName: '', targetSummary: '', targetStatus: '', author: 'admin01', authorTeam: '배송 CS팀', createdAt: '2026-08-24 14:00', updatedAt: '2026-08-24 14:00', followUpRequired: false, followUpAt: null, followUpAssignee: null, followUpCompletedAt: null, followUpCompletedBy: null, hidden: false, sensitiveReview: false, versions: [], history: [] }; }
