import type { BusinessType } from '../../lib/business';

export type ConsultationChannel = '1:1 문의' | '전화' | '채팅' | '이메일' | '오프라인' | '관리자 등록';
export type ConsultationResult = '해결' | '안내 완료' | '고객 확인 완료' | '후속 처리 필요' | '다른 부서 이관' | '정책상 처리 불가' | '고객 요청 철회' | '중복 문의';
export type SlaResult = '준수' | '초과' | '대상 아님';

export interface ConsultationCustomer {
  id: string; name: string; type: '회원' | '기업 고객'; status: string; phone: string; email: string; joinedAt: string; totalConsultations: number; recentConsultations: number; company?: string;
}
export interface ConsultationMessage { id: string; role: 'customer' | 'admin' | 'system'; author: string; at: string; body: string; }
export interface RelatedWork { type: '주문' | '결제' | '배송' | '환불'; id: string; status: string; detail: string; }
export interface ConsultationHistory { id: string; at: string; action: string; actor: string; detail?: string; kind: 'customer' | 'admin' | 'system'; }
export interface ConsultationMemo { id: string; at: string; author: string; body: string; }

export interface ConsultationEntry {
  id: string; businessType: BusinessType; inquiryId: string | null; channel: ConsultationChannel; category: string; subcategory: string; customer: ConsultationCustomer;
  title: string; summary: string; request: string; checked: string; resolution: string; startedAt: string; firstResponseAt: string | null; completedAt: string | null;
  assignee: string; team: string; result: ConsultationResult; completionReason: string; followUp: string | null; slaHours: number | null; actualResponseMinutes: number | null; slaResult: SlaResult;
  satisfaction: number | null; satisfactionComment: string | null; satisfactionAt: string | null; reopened: boolean; complaint: boolean; tags: string[];
  direction?: '수신' | '발신'; callMinutes?: number; messages: ConsultationMessage[]; related: RelatedWork[]; memos: ConsultationMemo[]; relatedConsultations: string[]; history: ConsultationHistory[];
}

const customer = (id: string, name: string, total: number, recent: number, company?: string): ConsultationCustomer => ({ id, name, type: company ? '기업 고객' : '회원', status: '정상', phone: '010-****-1234', email: `${id.slice(0, 1)}***@example.com`, joinedAt: '2025-10-20', totalConsultations: total, recentConsultations: recent, company });
const msg = (id: string, role: ConsultationMessage['role'], author: string, at: string, body: string): ConsultationMessage => ({ id, role, author, at, body });
const hist = (id: string, at: string, action: string, actor: string, kind: ConsultationHistory['kind'], detail?: string): ConsultationHistory => ({ id, at, action, actor, kind, detail });

export const CONSULTATIONS: ConsultationEntry[] = [
  {
    id: 'CS-00382', businessType: 'B2C', inquiryId: 'QNA-00182', channel: '1:1 문의', category: '배송', subcategory: '배송 지연', customer: customer('user01', '김민수', 12, 3, '마켓원'), title: '배송 예정일 초과 관련 확인', summary: '지역 터미널 지연 확인 후 금일 배송 예정 안내', request: '배송 예정일이 지났으나 상품을 받지 못해 현재 위치와 도착 일정을 확인 요청함.', checked: '택배사 조회 결과 지역 터미널 물량 증가로 배송이 지연된 것을 확인함.', resolution: '고객에게 현재 배송 상태와 금일 중 배송 예정임을 안내함.', startedAt: '2026-08-24 10:20', firstResponseAt: '2026-08-24 10:42', completedAt: '2026-08-24 11:15', assignee: 'admin01', team: '배송 CS팀', result: '해결', completionReason: '배송 일정 안내 완료', followUp: null, slaHours: 4, actualResponseMinutes: 22, slaResult: '준수', satisfaction: 5, satisfactionComment: '빠르게 확인해 주셔서 감사합니다.', satisfactionAt: '2026-08-24 13:10', reopened: false, complaint: false, tags: ['배송 이슈'],
    messages: [msg('M382-1', 'customer', 'user01', '10:20', '배송이 아직 도착하지 않았습니다.'), msg('M382-2', 'admin', 'admin01', '10:42', '배송 상태를 확인했습니다. 현재 지역 터미널에 도착한 상태입니다.'), msg('M382-3', 'customer', 'user01', '11:02', '오늘 받을 수 있나요?'), msg('M382-4', 'admin', 'admin01', '11:10', '오늘 중 배송 예정으로 확인됩니다.')],
    related: [{ type: '주문', id: 'ORD-00582', status: '주문 완료', detail: '428,000원' }, { type: '결제', id: 'PAY-00182', status: '결제 완료', detail: '법인카드' }, { type: '배송', id: 'SHP-00182', status: '배송 완료', detail: '08.24 17:25 완료' }], memos: [{ id: 'MM382-1', at: '2026-08-24 10:35', author: 'admin01', body: '배송사 확인 필요.' }, { id: 'MM382-2', at: '2026-08-24 10:55', author: 'admin02', body: '배송사에서 금일 배송 예정으로 회신.' }], relatedConsultations: ['CS-00371', 'CS-00352'],
    history: [hist('H382-1', '10:20', '문의 접수 · 상담 생성', 'user01', 'customer'), hist('H382-2', '10:25', '담당자 지정', '시스템', 'system', 'admin01'), hist('H382-3', '10:42', '첫 답변 발송', 'admin01', 'admin'), hist('H382-4', '11:02', '고객 추가 메시지', 'user01', 'customer'), hist('H382-5', '11:10', '추가 답변 발송', 'admin01', 'admin'), hist('H382-6', '11:15', '상담 완료', 'admin01', 'admin', '결과: 해결')],
  },
  {
    id: 'CS-00381', businessType: 'B2B', inquiryId: null, channel: '전화', category: '결제', subcategory: '결제 오류', customer: customer('buyer02', '박서연', 5, 1, '오피스랩'), title: '카드 승인 후 주문 미생성', summary: '승인 취소 예정 시간 및 재주문 방법 안내', request: '카드 승인은 되었으나 주문이 생성되지 않아 전화로 확인 요청.', checked: 'PG 승인 후 주문 생성 단계에서 타임아웃 발생. 자동 승인 취소 전문 발송 확인.', resolution: '영업일 기준 승인 취소 시점과 재주문 방법 안내.', startedAt: '2026-08-23 16:12', firstResponseAt: '2026-08-23 16:12', completedAt: '2026-08-23 16:24', assignee: 'admin02', team: '결제 CS팀', result: '안내 완료', completionReason: '결제 취소 일정 안내', followUp: 'PG 자동 승인 취소 모니터링', slaHours: 2, actualResponseMinutes: 0, slaResult: '준수', satisfaction: null, satisfactionComment: null, satisfactionAt: null, reopened: false, complaint: true, tags: ['불만', '결제 이슈'], direction: '수신', callMinutes: 12,
    messages: [], related: [{ type: '결제', id: 'PAY-00181', status: '승인 취소중', detail: '1,284,000원' }], memos: [{ id: 'MM381-1', at: '2026-08-23 16:25', author: 'admin02', body: 'PG 취소 배치 익일 확인 필요.' }], relatedConsultations: [], history: [hist('H381-1', '16:12', '전화 상담 시작', 'admin02', 'admin', '수신'), hist('H381-2', '16:24', '전화 상담 종료', 'admin02', 'admin', '통화 12분'), hist('H381-3', '16:25', '상담 결과 등록', 'admin02', 'admin', '안내 완료')],
  },
  {
    id: 'CS-00380', businessType: 'B2B', inquiryId: 'QNA-00180', channel: '채팅', category: '회원 / 계정', subcategory: '비밀번호', customer: customer('company03', '이준호', 3, 2, '컴퍼니03'), title: '관리자 계정 비밀번호 재설정', summary: '본인 인증 후 재설정 링크 발송', request: '담당자 변경으로 관리자 계정 비밀번호 재설정 요청.', checked: '회사 관리자 권한 및 본인 인증 확인.', resolution: '비밀번호 재설정 링크를 등록 이메일로 발송.', startedAt: '2026-08-24 08:40', firstResponseAt: '2026-08-24 08:44', completedAt: '2026-08-24 09:10', assignee: 'admin03', team: '일반 CS팀', result: '고객 확인 완료', completionReason: '재설정 완료 확인', followUp: null, slaHours: 12, actualResponseMinutes: 4, slaResult: '준수', satisfaction: 4, satisfactionComment: '도움이 됐어요.', satisfactionAt: '2026-08-24 09:15', reopened: false, complaint: false, tags: ['계정'], messages: [msg('M380-1', 'customer', 'company03', '08:40', '관리자 계정 비밀번호를 재설정하고 싶어요.'), msg('M380-2', 'admin', 'admin03', '08:44', '본인 인증 후 재설정 링크를 보내드리겠습니다.'), msg('M380-3', 'customer', 'company03', '09:08', '재설정을 완료했습니다.')], related: [], memos: [], relatedConsultations: ['CS-00291'], history: [hist('H380-1', '08:40', '채팅 시작', 'company03', 'customer'), hist('H380-2', '08:44', '첫 응답', 'admin03', 'admin'), hist('H380-3', '09:10', '상담 완료', 'admin03', 'admin')],
  },
  {
    id: 'CS-00379', businessType: 'C2C', inquiryId: 'QNA-00179', channel: '이메일', category: '취소 / 환불', subcategory: '환불 지연', customer: customer('shop04', '최지우', 9, 4, '샵04'), title: '카드 환불 지연 확인', summary: '카드사 처리 지연으로 후속 확인 필요', request: '지난주 취소 주문의 카드 환불 미반영 확인 요청.', checked: 'PG 취소 완료, 카드사 매입 취소 반영 대기.', resolution: '카드사 처리 기간을 안내하고 후속 확인 업무 연결.', startedAt: '2026-08-23 16:10', firstResponseAt: '2026-08-24 09:28', completedAt: '2026-08-24 10:05', assignee: 'admin02', team: '결제 CS팀', result: '후속 처리 필요', completionReason: '고객 안내 완료', followUp: '환불 RFD-00042 · 카드사 반영 확인중', slaHours: 8, actualResponseMinutes: 1038, slaResult: '초과', satisfaction: 2, satisfactionComment: '환불이 너무 늦습니다.', satisfactionAt: '2026-08-24 10:40', reopened: true, complaint: true, tags: ['불만', '낮은 만족도', '반복 문의'], messages: [msg('M379-1', 'customer', 'shop04', '08.23 16:10', '환불이 아직 반영되지 않았습니다.'), msg('M379-2', 'admin', 'admin02', '08.24 09:28', '카드사 매입 취소 반영을 확인 중입니다.')], related: [{ type: '주문', id: 'ORD-00566', status: '주문 취소', detail: '760,000원' }, { type: '환불', id: 'RFD-00042', status: '처리중', detail: '카드사 확인' }], memos: [{ id: 'MM379-1', at: '2026-08-24 09:15', author: 'admin02', body: 'PG 취소 전문 정상. 카드사 확인 필요.' }], relatedConsultations: ['CS-00388'], history: [hist('H379-1', '08.23 16:10', '이메일 수신', 'shop04', 'customer'), hist('H379-2', '08.24 09:28', '답변 발송', 'admin02', 'admin', 'SLA 초과'), hist('H379-3', '10:05', '상담 종료', 'admin02', 'admin', '후속 처리 필요'), hist('H379-4', '10:40', '만족도 응답', 'shop04', 'customer', '2점')],
  },
  {
    id: 'CS-00378', businessType: 'C2C', inquiryId: 'QNA-00178', channel: '1:1 문의', category: '교환 / 반품', subcategory: '상품 파손', customer: customer('market05', '정하늘', 7, 5, '마켓05'), title: '파손 상품 회수 일정 문의', summary: '회수 기사 재배정 요청 후 고객 안내', request: '교환 신청 후 회수 기사 연락이 없어 일정 확인 요청.', checked: '택배사 회수 접수 누락 확인.', resolution: '회수 재접수 후 익일 방문 예정 안내.', startedAt: '2026-08-22 13:05', firstResponseAt: '2026-08-22 14:10', completedAt: '2026-08-22 14:18', assignee: 'admin01', team: '배송 CS팀', result: '해결', completionReason: '회수 재접수 완료', followUp: null, slaHours: 4, actualResponseMinutes: 65, slaResult: '준수', satisfaction: 1, satisfactionComment: '처음부터 제대로 접수됐으면 좋겠습니다.', satisfactionAt: '2026-08-22 18:00', reopened: true, complaint: true, tags: ['불만', '반복 문의', '상품 파손'], messages: [msg('M378-1', 'customer', 'market05', '13:05', '기사님 연락을 받지 못했습니다.'), msg('M378-2', 'admin', 'admin01', '14:10', '회수 접수가 누락되어 다시 접수했습니다.')], related: [{ type: '주문', id: 'ORD-00542', status: '교환 접수', detail: '파손 상품' }, { type: '배송', id: 'SHP-00161', status: '회수 완료', detail: '08.23 완료' }], memos: [], relatedConsultations: ['CS-00391'], history: [hist('H378-1', '13:05', '문의 접수', 'market05', 'customer'), hist('H378-2', '13:20', '일반 CS → 배송 CS 이관', 'admin03', 'admin', '배송사 확인 필요'), hist('H378-3', '14:10', '답변 발송', 'admin01', 'admin'), hist('H378-4', '14:18', '상담 완료', 'admin01', 'admin')],
  },
  {
    id: 'CS-00377', businessType: 'B2B', inquiryId: null, channel: '관리자 등록', category: '서비스 이용', subcategory: '견적서', customer: customer('office06', '한소희', 2, 1, '오피스06'), title: '견적서 PDF 다운로드 안내', summary: '견적 상세의 PDF 다운로드 위치 안내', request: '영업 담당자를 통해 견적서 다운로드 방법 문의.', checked: '견적 QOT-00321 승인 완료 상태 확인.', resolution: '견적 상세 우측 상단 PDF 다운로드 버튼 안내.', startedAt: '2026-08-21 10:00', firstResponseAt: '2026-08-21 10:20', completedAt: '2026-08-21 10:35', assignee: 'admin03', team: '일반 CS팀', result: '안내 완료', completionReason: '이용 방법 안내', followUp: null, slaHours: null, actualResponseMinutes: 20, slaResult: '대상 아님', satisfaction: null, satisfactionComment: null, satisfactionAt: null, reopened: false, complaint: false, tags: ['이용 안내'], messages: [], related: [{ type: '주문', id: 'QOT-00321', status: '견적 승인', detail: '유효기간 08.31' }], memos: [], relatedConsultations: [], history: [hist('H377-1', '10:00', '수동 상담 등록', 'admin03', 'admin'), hist('H377-2', '10:35', '상담 결과 등록', 'admin03', 'admin', '안내 완료')],
  },
  {
    id: 'CS-00376', businessType: 'B2C', inquiryId: 'QNA-00176', channel: '1:1 문의', category: '배송', subcategory: '배송지 변경', customer: customer('store07', '오세훈', 4, 2, '스토어07'), title: '출고 전 배송지 변경 요청', summary: '상품 출고 완료로 정책상 변경 불가 안내', request: '이전 사무실 주소로 주문되어 배송지 변경 요청.', checked: '상품이 이미 택배사로 인계되어 시스템상 주소 변경 불가.', resolution: '배송사 고객센터를 통한 수령지 변경 절차 안내.', startedAt: '2026-08-20 11:35', firstResponseAt: '2026-08-20 12:00', completedAt: '2026-08-20 12:12', assignee: 'admin02', team: '배송 CS팀', result: '정책상 처리 불가', completionReason: '출고 완료', followUp: null, slaHours: 4, actualResponseMinutes: 25, slaResult: '준수', satisfaction: 3, satisfactionComment: null, satisfactionAt: '2026-08-20 14:00', reopened: false, complaint: false, tags: ['정책 안내'], messages: [msg('M376-1', 'customer', 'store07', '11:35', '출고 전 배송지를 바꿀 수 있을까요?'), msg('M376-2', 'admin', 'admin02', '12:00', '이미 택배사로 인계되어 시스템 변경이 어렵습니다.')], related: [{ type: '주문', id: 'ORD-00580', status: '출고 완료', detail: '배송지 변경 불가' }], memos: [], relatedConsultations: [], history: [hist('H376-1', '11:35', '문의 접수', 'store07', 'customer'), hist('H376-2', '12:00', '답변 발송', 'admin02', 'admin'), hist('H376-3', '12:12', '처리 완료', 'admin02', 'admin', '정책상 처리 불가')],
  },
  {
    id: 'CS-00375', businessType: 'B2B', inquiryId: null, channel: '오프라인', category: '정산', subcategory: '세금계산서', customer: customer('corp08', '문가영', 6, 2, '코퍼레이션08'), title: '세금계산서 수신 이메일 확인', summary: '수신 주소 정정 후 재발송 완료', request: '방문 미팅 중 7월 세금계산서 미수신 문의.', checked: '사업자 정보의 수신 이메일 오기 확인.', resolution: '이메일 주소 정정 및 세금계산서 재발송.', startedAt: '2026-08-19 14:20', firstResponseAt: '2026-08-19 14:25', completedAt: '2026-08-19 14:40', assignee: 'admin04', team: '정산 CS팀', result: '해결', completionReason: '재발송 완료', followUp: null, slaHours: null, actualResponseMinutes: 5, slaResult: '대상 아님', satisfaction: 5, satisfactionComment: '현장에서 바로 처리해 주셨어요.', satisfactionAt: '2026-08-19 15:00', reopened: false, complaint: false, tags: ['정산'], messages: [], related: [{ type: '결제', id: 'TAX-00118', status: '발행 완료', detail: '07월 거래분' }], memos: [], relatedConsultations: ['CS-00284'], history: [hist('H375-1', '14:20', '오프라인 상담 등록', 'admin04', 'admin'), hist('H375-2', '14:40', '처리 완료', 'admin04', 'admin')],
  },
];

export const CONSULTATION_CHANNELS: ConsultationChannel[] = ['1:1 문의', '전화', '채팅', '이메일', '오프라인', '관리자 등록'];
export const CONSULTATION_RESULTS: ConsultationResult[] = ['해결', '안내 완료', '고객 확인 완료', '후속 처리 필요', '다른 부서 이관', '정책상 처리 불가', '고객 요청 철회', '중복 문의'];
export const CONSULTATION_CATEGORIES = ['회원 / 계정', '주문', '결제', '배송', '취소 / 환불', '교환 / 반품', '서비스 이용', '정산'];
export const CONSULTATION_MANAGERS = ['admin01', 'admin02', 'admin03', 'admin04'];

export function durationLabel(item: ConsultationEntry) {
  if (!item.completedAt) return '진행중';
  const start = new Date(item.startedAt.replace(' ', 'T')).getTime();
  const end = new Date(item.completedAt.replace(' ', 'T')).getTime();
  const minutes = Math.round((end - start) / 60000);
  return minutes >= 60 ? `${Math.floor(minutes / 60)}시간 ${minutes % 60}분` : `${minutes}분`;
}
