import { DatePicker } from '../../components/forms/DatePicker';
import { useMemo, useState } from 'react';
import { DataGrid } from '../../components/DataGrid/DataGrid';
import type { GridRow } from '../../components/DataGrid/types';
import shared from '../ops/opsShared.module.css';
import { ConsultationDetailDrawer } from './ConsultationDetailDrawer';
import styles from './ConsultationsPage.module.css';
import { CONSULTATIONS, CONSULTATION_CATEGORIES, CONSULTATION_CHANNELS, CONSULTATION_MANAGERS, CONSULTATION_RESULTS, durationLabel, type ConsultationChannel, type ConsultationEntry, type ConsultationResult, type SlaResult } from './consultationsData';

type QuickFilter = '전체' | '오늘 상담' | '완료 상담' | '재문의 발생' | '불만 상담' | '내 담당 이력' | '낮은 만족도' | 'SLA 초과';
type Modal = 'register' | 'download' | 'reopen' | 'correct' | null;
const QUICK_FILTERS: QuickFilter[] = ['전체', '오늘 상담', '완료 상담', '재문의 발생', '불만 상담', '내 담당 이력', '낮은 만족도', 'SLA 초과'];
const COLUMNS = [{ label: '상담번호' }, { label: '채널' }, { label: '문의 유형' }, { label: '고객' }, { label: '상담 제목 / 요약' }, { label: '관련 대상' }, { label: '상담 시작' }, { label: '상담 종료' }, { label: '담당자' }, { label: '처리 결과' }, { label: 'SLA' }, { label: '만족도' }, { label: '관리', align: 'right' as const }];

function quickMatch(item: ConsultationEntry, filter: QuickFilter) {
  if (filter === '오늘 상담') return item.startedAt.startsWith('2026-08-24');
  if (filter === '완료 상담') return !!item.completedAt;
  if (filter === '재문의 발생') return item.reopened;
  if (filter === '불만 상담') return item.complaint;
  if (filter === '내 담당 이력') return item.assignee === 'admin01';
  if (filter === '낮은 만족도') return item.satisfaction !== null && item.satisfaction <= 2;
  if (filter === 'SLA 초과') return item.slaResult === '초과';
  return true;
}

const resultColor = (result: ConsultationResult) => ['해결', '안내 완료', '고객 확인 완료'].includes(result) ? { bg: '#ecfdf5', fg: '#047857' } : result === '후속 처리 필요' ? { bg: '#fff7ed', fg: '#c2410c' } : { bg: '#f4f4f5', fg: '#52525b' };
const channelColor = (channel: ConsultationChannel) => ({
  '1:1 문의': { bg: '#eff6ff', fg: '#2563eb' }, 전화: { bg: '#f0fdf4', fg: '#15803d' }, 채팅: { bg: '#f5f3ff', fg: '#7c3aed' }, 이메일: { bg: '#fff7ed', fg: '#c2410c' }, 오프라인: { bg: '#fdf2f8', fg: '#be185d' }, '관리자 등록': { bg: '#f4f4f5', fg: '#52525b' },
}[channel]);

export function ConsultationsPage() {
  const [items, setItems] = useState(CONSULTATIONS);
  const [quickFilter, setQuickFilter] = useState<QuickFilter>('전체');
  const [keyword, setKeyword] = useState(''); const [search, setSearch] = useState('');
  const [channel, setChannel] = useState(''); const [category, setCategory] = useState(''); const [result, setResult] = useState(''); const [manager, setManager] = useState('');
  const [satisfaction, setSatisfaction] = useState(''); const [reopened, setReopened] = useState(''); const [sla, setSla] = useState<SlaResult | ''>('');
  const [startedFrom, setStartedFrom] = useState(''); const [startedTo, setStartedTo] = useState(''); const [completedTo, setCompletedTo] = useState(''); const [showAdvanced, setShowAdvanced] = useState(false);
  const [selected, setSelected] = useState<string[]>([]); const [detailId, setDetailId] = useState<string | null>(null); const [openMenu, setOpenMenu] = useState<string | null>(null);
  const [modal, setModal] = useState<Modal>(null); const [toast, setToast] = useState('');
  const [manual, setManual] = useState({ customer: '', channel: '전화' as ConsultationChannel, category: '배송', title: '', request: '', resolution: '', result: '해결' as ConsultationResult, relatedId: '' });
  const [reopenReason, setReopenReason] = useState('추가 확인 필요'); const [keepAssignee, setKeepAssignee] = useState(true);
  const [correctResult, setCorrectResult] = useState<ConsultationResult>('안내 완료'); const [correctReason, setCorrectReason] = useState('결과 분류 오류');
  const [includeSensitive, setIncludeSensitive] = useState(false);

  const filtered = useMemo(() => items.filter((item) => {
    if (!quickMatch(item, quickFilter)) return false;
    const haystack = `${item.id} ${item.inquiryId ?? ''} ${item.customer.id} ${item.customer.name} ${item.customer.company ?? ''} ${item.title} ${item.summary} ${item.request} ${item.related.map((work) => work.id).join(' ')} ${item.assignee}`.toLowerCase();
    if (search && !haystack.includes(search.toLowerCase())) return false;
    if (channel && item.channel !== channel) return false; if (category && item.category !== category) return false; if (result && item.result !== result) return false; if (manager && item.assignee !== manager) return false;
    if (satisfaction === '미수집' ? item.satisfaction !== null : satisfaction && item.satisfaction !== Number(satisfaction)) return false;
    if (reopened === '예' && !item.reopened) return false; if (reopened === '아니오' && item.reopened) return false; if (sla && item.slaResult !== sla) return false;
    if (startedFrom && item.startedAt.slice(0, 10) < startedFrom) return false; if (startedTo && item.startedAt.slice(0, 10) > startedTo) return false; if (completedTo && item.completedAt && item.completedAt.slice(0, 10) > completedTo) return false;
    return true;
  }), [items, quickFilter, search, channel, category, result, manager, satisfaction, reopened, sla, startedFrom, startedTo, completedTo]);
  const detail = items.find((item) => item.id === detailId) ?? null;
  const toastBriefly = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2500); };
  const reset = () => { setKeyword(''); setSearch(''); setChannel(''); setCategory(''); setResult(''); setManager(''); setSatisfaction(''); setReopened(''); setSla(''); setStartedFrom(''); setStartedTo(''); setCompletedTo(''); setSelected([]); };

  const download = () => {
    const targets = selected.length ? items.filter((item) => selected.includes(item.id)) : filtered;
    const header = ['상담번호', '문의번호', '채널', '문의유형', '고객', '관련대상', '상담시작', '첫답변', '종료', '담당자', '처리결과', 'SLA', '만족도', ...(includeSensitive ? ['연락처', '이메일'] : [])];
    const rows = targets.map((item) => [item.id, item.inquiryId ?? '', item.channel, `${item.category}>${item.subcategory}`, item.customer.name, item.related.map((work) => work.id).join(' / '), item.startedAt, item.firstResponseAt ?? '', item.completedAt ?? '', item.assignee, item.result, item.slaResult, item.satisfaction ?? '', ...(includeSensitive ? [item.customer.phone, item.customer.email] : [])]);
    const csv = [header, ...rows].map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n');
    const url = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'consultations.csv'; anchor.click(); URL.revokeObjectURL(url); setModal(null); toastBriefly(`${targets.length}건을 다운로드했습니다. 다운로드 이력이 기록됩니다.`);
  };
  const register = () => {
    if (!manual.customer.trim() || !manual.title.trim() || !manual.request.trim() || !manual.resolution.trim()) return toastBriefly('고객, 제목, 고객 요청과 처리 내용은 필수입니다.');
    const source = items[0]; const now = '2026-08-24 14:00';
    const created: ConsultationEntry = { ...source, id: `CS-${String(items.length + 383).padStart(5, '0')}`, inquiryId: null, channel: manual.channel, category: manual.category, subcategory: '수동 분류', customer: { ...source.customer, id: manual.customer, name: manual.customer, totalConsultations: 1, recentConsultations: 1, company: undefined, type: '회원' }, title: manual.title, summary: manual.resolution, request: manual.request, checked: '상담원 수동 등록', resolution: manual.resolution, startedAt: now, firstResponseAt: now, completedAt: now, assignee: 'admin01', team: '일반 CS팀', result: manual.result, completionReason: '수동 상담 등록', followUp: null, slaHours: null, actualResponseMinutes: 0, slaResult: '대상 아님', satisfaction: null, satisfactionComment: null, satisfactionAt: null, reopened: false, complaint: false, tags: [], direction: manual.channel === '전화' ? '수신' : undefined, callMinutes: manual.channel === '전화' ? 0 : undefined, messages: [], related: manual.relatedId ? [{ type: '주문', id: manual.relatedId, status: '연결됨', detail: '수동 연결' }] : [], memos: [], relatedConsultations: [], history: [{ id: `H-${Date.now()}`, at: now, action: '수동 상담 등록', actor: 'admin01', kind: 'admin', detail: manual.result }] };
    setItems((current) => [created, ...current]); setModal(null); setDetailId(created.id); toastBriefly('상담 내역을 등록했습니다.');
  };
  const reopenInquiry = () => { if (!detail) return; setItems((current) => current.map((item) => item.id === detail.id ? { ...item, reopened: true, history: [...item.history, { id: `H-${Date.now()}`, at: '2026-08-24 14:00', action: '원 문의 재오픈', actor: 'admin01', kind: 'admin', detail: `${reopenReason} · ${keepAssignee ? '기존 담당자 유지' : '새로 배정'}` }] } : item)); setModal(null); toastBriefly(`${detail.inquiryId} 문의를 다시 처리 상태로 변경했습니다.`); };
  const correct = () => { if (!detail) return; const old = detail.result; setItems((current) => current.map((item) => item.id === detail.id ? { ...item, result: correctResult, history: [...item.history, { id: `H-${Date.now()}`, at: '2026-08-24 14:00', action: '상담 기록 정정', actor: 'admin01', kind: 'admin', detail: `${old} → ${correctResult} · ${correctReason}` }] } : item)); setModal(null); toastBriefly('원본을 보존하고 정정 이력을 추가했습니다.'); };

  const rows: GridRow[] = filtered.map((item) => {
    const rMeta = resultColor(item.result); const cMeta = channelColor(item.channel); const related = item.related[0]; const low = item.satisfaction !== null && item.satisfaction <= 2;
    return { id: item.id, selected: selected.includes(item.id), onToggleSelect: () => setSelected((current) => current.includes(item.id) ? current.filter((id) => id !== item.id) : [...current, item.id]), onClick: () => setDetailId(item.id), bg: low ? '#fffafa' : item.reopened ? '#fffdf6' : undefined, mark: low ? 'inset 3px 0 #f97316' : undefined, cells: [
      { kind: 'noTag', no: item.id, hasTag: item.reopened, tagText: '재문의', tagBg: '#fff7ed', tagFg: '#c2410c' }, { kind: 'badge', text: item.channel, bg: cMeta.bg, fg: cMeta.fg }, { kind: 'pillText', text: item.subcategory, sub: item.category, bg: '#f4f4f5', fg: '#52525b' },
      { kind: 'avatarText', title: item.customer.name, subtitle: item.customer.id, avatarChar: item.customer.name.slice(0, 1), avatarBg: '#eef2ff', avatarFg: '#4f46e5' }, { kind: 'titleWarn', title: item.title, hasIssue: item.complaint, issueTitle: item.tags.join(' · ') }, related ? { kind: 'stack', title: related.id, subtitle: `${related.type} · ${related.status}` } : { kind: 'text', text: '연결 없음', size: '13px', color: '#a1a1aa' },
      { kind: 'stack', title: item.startedAt.slice(0, 10), subtitle: item.startedAt.slice(11) }, item.completedAt ? { kind: 'stack', title: item.completedAt.slice(0, 10), subtitle: `${item.completedAt.slice(11)} · ${durationLabel(item)}` } : { kind: 'text', text: '진행중', size: '13px', color: '#c2410c' }, { kind: 'stack', title: item.assignee, subtitle: item.team }, { kind: 'badge', text: item.result, bg: rMeta.bg, fg: rMeta.fg },
      { kind: 'badgeSub', text: item.slaResult, subText: item.actualResponseMinutes === null ? '' : `첫 응답 ${item.actualResponseMinutes}분`, bg: item.slaResult === '초과' ? '#fef2f2' : item.slaResult === '준수' ? '#ecfdf5' : '#f4f4f5', fg: item.slaResult === '초과' ? '#dc2626' : item.slaResult === '준수' ? '#047857' : '#71717a' }, { kind: 'text', text: item.satisfaction ? `${'★'.repeat(item.satisfaction)} ${item.satisfaction}점` : '-', color: low ? '#dc2626' : item.satisfaction ? '#d97706' : '#a1a1aa', size: '11px' },
      { kind: 'rowMenu', align: 'right', detailLabel: '상세', onDetail: () => setDetailId(item.id), open: openMenu === item.id, onToggle: () => setOpenMenu(openMenu === item.id ? null : item.id), items: [{ label: '상세 보기', click: () => setDetailId(item.id) }, { label: '고객 보기' }, ...(item.inquiryId ? [{ label: '원 문의 보기', click: () => window.location.assign('/cs/inquiries') }] : []), ...(related ? [{ label: '관련 업무 보기' }] : []), { sep: true }, ...(item.inquiryId ? [{ label: '문의 재오픈', click: () => { setDetailId(item.id); setModal('reopen'); } }] : []), { label: '새 문의 등록', click: () => window.location.assign('/cs/inquiries') }, { label: '상담 기록 정정', click: () => { setDetailId(item.id); setCorrectResult(item.result); setModal('correct'); } }] },
    ] };
  });

  return <section className={shared.page} onClick={() => openMenu && setOpenMenu(null)}>
    <div className={shared.headTop}><div className={shared.headRow}><div><h1 className={shared.title}>상담 내역</h1><p className={shared.subtitle}>고객과 진행된 다채널 상담 내용과 처리 결과를 통합 조회합니다.</p></div><button type="button" className={shared.createBtn} onClick={() => setModal('register')}>+ 상담 내역 등록</button></div>
      <div className={shared.quickFilters}>{QUICK_FILTERS.map((filter) => <button key={filter} type="button" className={`${shared.qfBtn} ${quickFilter === filter ? styles.quickActive : ''}`} onClick={() => { setQuickFilter(filter); setSelected([]); }}><span className={shared.qfLabel}>{filter}</span><span className={shared.qfCount}>{items.filter((item) => quickMatch(item, filter)).length}</span></button>)}</div>
      <div className={shared.filterBox}><form className={shared.filterRow1} onSubmit={(event) => { event.preventDefault(); setSearch(keyword.trim()); }}><select className={shared.selectSm}><option>전체 검색</option><option>상담번호</option><option>고객</option><option>문의·주문번호</option></select><input className={shared.searchInput} value={keyword} onChange={(e) => setKeyword(e.target.value)} placeholder="상담번호, 회원, 문의번호, 주문번호 검색" /><button type="submit" className={shared.searchBtn}>검색</button></form>
        <div className={shared.filterRow2}><select className={shared.selectSm} value={channel} onChange={(e) => setChannel(e.target.value)}><option value="">전체 채널</option>{CONSULTATION_CHANNELS.map((value) => <option key={value}>{value}</option>)}</select><select className={shared.selectSm} value={category} onChange={(e) => setCategory(e.target.value)}><option value="">전체 문의유형</option>{CONSULTATION_CATEGORIES.map((value) => <option key={value}>{value}</option>)}</select><select className={shared.selectSm} value={result} onChange={(e) => setResult(e.target.value)}><option value="">전체 처리결과</option>{CONSULTATION_RESULTS.map((value) => <option key={value}>{value}</option>)}</select><select className={shared.selectSm} value={manager} onChange={(e) => setManager(e.target.value)}><option value="">전체 담당자</option>{CONSULTATION_MANAGERS.map((value) => <option key={value}>{value}</option>)}</select><select className={shared.selectSm} value={satisfaction} onChange={(e) => setSatisfaction(e.target.value)}><option value="">전체 만족도</option><option value="5">5점</option><option value="4">4점</option><option value="3">3점</option><option value="2">2점</option><option value="1">1점</option><option>미수집</option></select><button type="button" className={shared.detailFilterBtn} onClick={() => setShowAdvanced((current) => !current)}>상세 필터 {showAdvanced ? '−' : '+'}</button><span className={shared.rowSpacer} /><button type="button" className={shared.resetBtn} onClick={reset}>필터 초기화</button></div>
        {showAdvanced && <div className={styles.advancedFilters}><label>상담 시작<DatePicker value={startedFrom} onChange={(e) => setStartedFrom(e.target.value)} /></label><label>상담 종료<DatePicker value={startedTo} onChange={(e) => setStartedTo(e.target.value)} /></label><label>완료일 이내<DatePicker value={completedTo} onChange={(e) => setCompletedTo(e.target.value)} /></label><label>재문의<select value={reopened} onChange={(e) => setReopened(e.target.value)}><option value="">전체</option><option>예</option><option>아니오</option></select></label><label>SLA<select value={sla} onChange={(e) => setSla(e.target.value as SlaResult | '')}><option value="">전체</option><option>준수</option><option>초과</option><option>대상 아님</option></select></label></div>}
      </div>
    </div>
    {selected.length > 0 && <div className={shared.bulkBar}><span className={shared.bulkLabel}>{selected.length}건 선택</span><button type="button" className={shared.bulkBtn} onClick={() => setModal('download')}>선택 다운로드</button><button type="button" className={shared.bulkBtn} onClick={() => { setItems((current) => current.map((item) => selected.includes(item.id) ? { ...item, tags: [...new Set([...item.tags, '검토 필요'])] } : item)); toastBriefly('선택 상담에 검토 필요 태그를 지정했습니다.'); }}>태그 지정</button><span className={styles.bulkGuard}>완료된 상담 결과·담당자·원문은 일괄 변경할 수 없습니다.</span></div>}
    <div className={shared.gridWrap}><div className={shared.resultRow}><span className={shared.resultLabel}>총 {filtered.length}건</span><div className={shared.resultActions}><button type="button" className={shared.downloadBtn} onClick={() => setModal('download')}>상담 내역 다운로드</button><select className={shared.pageSizeSelect}><option>20개씩</option><option>50개씩</option></select></div></div><DataGrid columns={COLUMNS} rows={rows} gridTemplate="104px 82px 118px 124px minmax(190px,1.7fr) 140px 96px 116px 110px 110px 106px 94px 90px" minWidth="1510px" selectable allSelected={filtered.length > 0 && filtered.every((item) => selected.includes(item.id))} onToggleAll={() => setSelected(filtered.every((item) => selected.includes(item.id)) ? [] : filtered.map((item) => item.id))} empty={filtered.length === 0} emptyText={quickFilter === '재문의 발생' ? '현재 재문의가 발생한 상담 내역이 없습니다.' : '검색 결과가 없습니다.'} emptySubtext="검색어나 필터 조건을 변경해 주세요." emptyActionLabel="필터 초기화" emptyActionClick={reset} showPagination pages={[{ label: '‹' }, { label: '1', active: true }, { label: '›' }]} rangeLabel={filtered.length ? `1–${filtered.length} / ${filtered.length}` : '0건'} /></div>
    {detail && <ConsultationDetailDrawer key={detail.id} item={detail} onClose={() => setDetailId(null)} onReopen={() => setModal('reopen')} onCorrect={() => { setCorrectResult(detail.result); setModal('correct'); }} onNewInquiry={() => window.location.assign('/cs/inquiries')} />}

    {modal === 'register' && <div className={shared.dialogOverlay} onMouseDown={(e) => { if (e.target === e.currentTarget) setModal(null); }}><div className={`${shared.dialogBox} ${styles.largeDialog}`}><h2 className={shared.dialogTitle}>상담 내역 등록</h2><p className={shared.dialogBody}>전화·오프라인 등 시스템 밖에서 진행된 상담을 기록합니다.</p><div className={styles.formGrid}><label>고객 *<input value={manual.customer} onChange={(e) => setManual({ ...manual, customer: e.target.value })} placeholder="회원 ID 또는 고객명" /></label><label>상담 채널 *<select value={manual.channel} onChange={(e) => setManual({ ...manual, channel: e.target.value as ConsultationChannel })}>{CONSULTATION_CHANNELS.filter((value) => value !== '1:1 문의').map((value) => <option key={value}>{value}</option>)}</select></label><label>문의 유형 *<select value={manual.category} onChange={(e) => setManual({ ...manual, category: e.target.value })}>{CONSULTATION_CATEGORIES.map((value) => <option key={value}>{value}</option>)}</select></label><label>관련 주문<input value={manual.relatedId} onChange={(e) => setManual({ ...manual, relatedId: e.target.value })} placeholder="ORD-00000" /></label></div><label className={styles.dialogField}>상담 제목 *<input value={manual.title} onChange={(e) => setManual({ ...manual, title: e.target.value })} /></label><label className={styles.dialogField}>고객 요청 *<textarea value={manual.request} onChange={(e) => setManual({ ...manual, request: e.target.value })} /></label><label className={styles.dialogField}>처리 내용 *<textarea value={manual.resolution} onChange={(e) => setManual({ ...manual, resolution: e.target.value })} /></label><label className={styles.dialogField}>처리 결과 *<select value={manual.result} onChange={(e) => setManual({ ...manual, result: e.target.value as ConsultationResult })}>{CONSULTATION_RESULTS.map((value) => <option key={value}>{value}</option>)}</select></label><div className={shared.dialogActions}><button type="button" className={styles.cancelButton} onClick={() => setModal(null)}>취소</button><button type="button" className={styles.primaryButton} onClick={register}>등록</button></div></div></div>}
    {modal === 'download' && <div className={shared.dialogOverlay} onMouseDown={(e) => { if (e.target === e.currentTarget) setModal(null); }}><div className={shared.dialogBox}><h2 className={shared.dialogTitle}>상담 내역 다운로드</h2><p className={shared.dialogBody}>{selected.length ? `선택한 상담 ${selected.length}건` : `현재 검색 결과 ${filtered.length}건`}을 CSV로 다운로드합니다.</p><div className={styles.downloadFields}><span>기본 포함 항목</span><p>상담·문의번호, 채널, 유형, 고객, 관련 대상, 상담일, 첫 답변일, 완료일, 담당자, 처리결과, SLA, 만족도</p><label><input type="checkbox" checked={includeSensitive} onChange={(e) => setIncludeSensitive(e.target.checked)} /> 연락처·이메일 포함 <em>고권한 · Audit 기록</em></label></div><div className={styles.privacyWarning}>민감정보는 마스킹된 현재 표시값으로 내려받으며 다운로드 이력이 저장됩니다.</div><div className={shared.dialogActions}><button type="button" className={styles.cancelButton} onClick={() => setModal(null)}>취소</button><button type="button" className={styles.primaryButton} onClick={download}>다운로드</button></div></div></div>}
    {modal === 'reopen' && detail && <div className={shared.dialogOverlay} onMouseDown={(e) => { if (e.target === e.currentTarget) setModal(null); }}><div className={shared.dialogBox}><h2 className={shared.dialogTitle}>문의 재오픈</h2><p className={shared.dialogBody}>완료된 상담은 그대로 보존하고 원 문의 Workflow만 다시 처리 상태로 변경합니다.</p><div className={shared.dialogSummary}><div className={shared.dialogSummaryRow}><span>원 문의</span><strong>{detail.inquiryId}</strong></div><div className={shared.dialogSummaryRow}><span>최근 상담</span><strong>{detail.id}</strong></div></div><label className={styles.dialogField}>재오픈 사유 *<select value={reopenReason} onChange={(e) => setReopenReason(e.target.value)}><option>추가 확인 필요</option><option>고객 추가 요청</option><option>처리 결과 오류</option><option>후속 업무 미완료</option></select></label><div className={styles.radioGroup}><label><input type="radio" checked={keepAssignee} onChange={() => setKeepAssignee(true)} /> 기존 담당자 유지</label><label><input type="radio" checked={!keepAssignee} onChange={() => setKeepAssignee(false)} /> 새로 배정</label></div><div className={shared.dialogActions}><button type="button" className={styles.cancelButton} onClick={() => setModal(null)}>취소</button><button type="button" className={styles.primaryButton} onClick={reopenInquiry}>재오픈</button></div></div></div>}
    {modal === 'correct' && detail && <div className={shared.dialogOverlay} onMouseDown={(e) => { if (e.target === e.currentTarget) setModal(null); }}><div className={shared.dialogBox}><h2 className={shared.dialogTitle}>상담 기록 정정</h2><p className={shared.dialogBody}>원 상담 기록을 삭제하거나 덮어쓰지 않고 정정 전·후 값과 사유를 Audit에 보존합니다.</p><div className={shared.dialogSummary}><div className={shared.dialogSummaryRow}><span>현재 결과</span><strong>{detail.result}</strong></div></div><label className={styles.dialogField}>정정 결과 *<select value={correctResult} onChange={(e) => setCorrectResult(e.target.value as ConsultationResult)}>{CONSULTATION_RESULTS.map((value) => <option key={value}>{value}</option>)}</select></label><label className={styles.dialogField}>정정 사유 *<textarea value={correctReason} onChange={(e) => setCorrectReason(e.target.value)} /></label><div className={shared.dialogActions}><button type="button" className={styles.cancelButton} onClick={() => setModal(null)}>취소</button><button type="button" className={styles.primaryButton} onClick={correct}>정정 기록</button></div></div></div>}
    {toast && <div className={styles.toast}>{toast}</div>}
  </section>;
}
