export type TemplateStatus = '사용' | '비활성';
export type TemplateChannel = '1:1 문의' | '채팅' | '이메일' | 'SMS';

export interface TemplateVersion { version: number; at: string; by: string; reason: string; body: string; }
export interface TemplateHistory { id: string; at: string; by: string; action: string; detail?: string; }
export interface TemplateMemo { id: string; at: string; by: string; body: string; }
export interface ResponseTemplate {
  id: string; name: string; code: string; category: string; status: TemplateStatus; inquiryTypes: string[]; recommended: boolean; recommendationOrder: number;
  subject: string; body: string; keywords: string[]; channels: TemplateChannel[]; target: '전체 상담원' | '특정 팀'; teams: string[]; displayOrder: number;
  usageCount: number; recent30Usage: number; lastUsedAt: string | null; updatedAt: string; updatedBy: string; reviewDueAt: string; relatedFaqs: { id: string; title: string; status: '공개' | '비공개' }[];
  adminMemo: string; versions: TemplateVersion[]; history: TemplateHistory[]; memos: TemplateMemo[];
}

export const TEMPLATE_CATEGORIES = ['회원 / 계정', '주문', '결제', '배송', '취소 / 환불', '교환 / 반품', '정책', '서비스', '기타'];
export const TEMPLATE_CHANNELS: TemplateChannel[] = ['1:1 문의', '채팅', '이메일', 'SMS'];
export const TEMPLATE_TEAMS = ['일반 CS팀', '주문 CS팀', '결제 CS팀', '배송 CS팀', '정산 CS팀'];
export const TEMPLATE_INQUIRY_TYPES = ['회원 / 계정 > 비밀번호', '주문 > 주문 취소', '결제 > 결제 오류', '결제 > 중복 결제', '배송 > 배송 조회', '배송 > 배송 지연', '배송 > 배송 실패', '교환 / 반품 > 상품 파손', '취소 / 환불 > 환불 지연', '서비스 > 견적서'];
export const SUPPORTED_VARIABLES = ['{고객명}', '{회원ID}', '{문의번호}', '{문의접수일}', '{주문번호}', '{주문일}', '{상품명}', '{결제번호}', '{결제금액}', '{결제상태}', '{배송번호}', '{송장번호}', '{배송상태}', '{예상배송일}', '{환불번호}', '{환불금액}', '{환불상태}', '{상담원명}', '{회사명}', '{현재일자}'];
export const SAMPLE_VALUES: Record<string, string> = { '{고객명}': '김민수', '{회원ID}': 'user01', '{문의번호}': 'QNA-00182', '{문의접수일}': '2026.08.24', '{주문번호}': 'ORD-00582', '{주문일}': '2026.08.21', '{상품명}': '사무용 의자 외 2건', '{결제번호}': 'PAY-00182', '{결제금액}': '428,000원', '{결제상태}': '결제 완료', '{배송번호}': 'SHP-00182', '{송장번호}': '1234567890', '{배송상태}': '배송중', '{예상배송일}': '2026.08.25', '{환불번호}': 'RFD-00042', '{환불금액}': '760,000원', '{환불상태}': '카드사 처리중', '{상담원명}': 'admin01', '{회사명}': '마켓원', '{현재일자}': '2026.08.24' };

const version = (body: string, reason = '템플릿 생성'): TemplateVersion[] => [{ version: 1, at: '2026-07-01 09:00', by: 'admin01', reason, body }];
const history = (code: string): TemplateHistory[] => [{ id: `${code}-H1`, at: '2026-07-01 09:00', by: 'admin01', action: '템플릿 생성' }];

export const RESPONSE_TEMPLATES: ResponseTemplate[] = [
  { id: 'TPL-00182', name: '배송 지연 기본 안내', code: 'DELIVERY_DELAY_BASIC', category: '배송', status: '사용', inquiryTypes: ['배송 > 배송 지연', '배송 > 배송 조회'], recommended: true, recommendationOrder: 1, subject: '배송 관련 문의에 답변드립니다.', body: '안녕하세요, {고객명}님.\n\n문의하신 주문 {주문번호}의 배송 상태는 현재 {배송상태}로 확인됩니다.\n예상 배송일은 {예상배송일}입니다.\n\n배송 상황에 따라 일정이 변경될 수 있는 점 양해 부탁드립니다.', keywords: ['배송', '택배', '배송지연', '늦음', '예정일'], channels: ['1:1 문의', '채팅', '이메일'], target: '특정 팀', teams: ['배송 CS팀'], displayOrder: 1, usageCount: 482, recent30Usage: 84, lastUsedAt: '2026-08-24', updatedAt: '2026-08-20', updatedBy: 'admin01', reviewDueAt: '2027-02-20', relatedFaqs: [{ id: 'FAQ-00182', title: '배송 상태는 어디에서 확인하나요?', status: '공개' }], adminMemo: '배송팀 요청으로 안내 문구 수정.', versions: [{ version: 1, at: '2026-03-01', by: 'admin01', reason: '템플릿 생성', body: '배송 예정일까지 조금만 기다려 주세요.' }, { version: 2, at: '2026-06-10', by: 'admin02', reason: '주문번호 변수 추가', body: '주문 {주문번호}의 배송을 확인 중입니다.' }, { version: 3, at: '2026-08-20', by: 'admin01', reason: '배송 일정 안내 정책 변경', body: '현재 예상 배송일은 {예상배송일}입니다. 배송 상황에 따라 일정이 변경될 수 있습니다.' }], history: [...history('DELIVERY_DELAY_BASIC'), { id: 'DDB-H2', at: '2026-08-10 11:00', by: 'admin02', action: '연결 문의유형 추가', detail: '배송 조회' }, { id: 'DDB-H3', at: '2026-08-20 15:20', by: 'admin01', action: '본문 수정', detail: '배송 일정 안내 정책 변경' }], memos: [{ id: 'DDB-M1', at: '2026-08-20', by: 'admin01', body: '배송팀 요청으로 안내 문구 수정.' }] },
  { id: 'TPL-00181', name: '배송 상태 확인 요청', code: 'DELIVERY_CHECK_REQUEST', category: '배송', status: '사용', inquiryTypes: ['배송 > 배송 지연', '배송 > 배송 실패'], recommended: true, recommendationOrder: 2, subject: '', body: '안녕하세요, {고객명}님.\n정확한 확인을 위해 주문번호와 송장번호를 남겨 주세요.\n확인 후 빠르게 안내드리겠습니다.', keywords: ['송장', '택배사', '확인'], channels: ['1:1 문의', '채팅'], target: '특정 팀', teams: ['배송 CS팀'], displayOrder: 2, usageCount: 318, recent30Usage: 67, lastUsedAt: '2026-08-24', updatedAt: '2026-08-15', updatedBy: 'admin01', reviewDueAt: '2027-02-15', relatedFaqs: [], adminMemo: '', versions: version('정확한 확인을 위해 주문번호와 송장번호를 남겨 주세요.'), history: history('DELIVERY_CHECK_REQUEST'), memos: [] },
  { id: 'TPL-00180', name: '중복 결제 확인 안내', code: 'PAYMENT_DUPLICATE_CHECK', category: '결제', status: '사용', inquiryTypes: ['결제 > 중복 결제'], recommended: true, recommendationOrder: 1, subject: '[서비스] 중복 결제 확인 결과', body: '안녕하세요, {고객명}님.\n\n주문 {주문번호}의 결제 내역을 확인 중입니다.\n중복 승인으로 확인되는 경우 {결제금액}은 카드사 정책에 따라 자동 취소됩니다.\n처리 결과를 다시 안내드리겠습니다.', keywords: ['중복', '이중결제', '카드승인'], channels: ['1:1 문의', '이메일'], target: '특정 팀', teams: ['결제 CS팀'], displayOrder: 1, usageCount: 184, recent30Usage: 43, lastUsedAt: '2026-08-23', updatedAt: '2026-08-12', updatedBy: 'admin02', reviewDueAt: '2026-11-12', relatedFaqs: [{ id: 'FAQ-00144', title: '결제가 두 번 되었어요', status: '공개' }], adminMemo: '결제 정책 변경 시 법무 검토', versions: version('중복 결제 내역을 확인 중입니다.'), history: history('PAYMENT_DUPLICATE_CHECK'), memos: [] },
  { id: 'TPL-00179', name: '환불 처리 일정 안내', code: 'REFUND_SCHEDULE_INFO', category: '취소 / 환불', status: '사용', inquiryTypes: ['취소 / 환불 > 환불 지연'], recommended: true, recommendationOrder: 1, subject: '환불 처리 일정을 안내드립니다.', body: '안녕하세요, {고객명}님.\n환불번호 {환불번호}의 현재 상태는 {환불상태}입니다.\n환불 금액 {환불금액}은 카드사 영업일 기준으로 반영됩니다.', keywords: ['환불', '카드취소', '반영'], channels: ['1:1 문의', '이메일', '채팅'], target: '특정 팀', teams: ['결제 CS팀'], displayOrder: 1, usageCount: 231, recent30Usage: 51, lastUsedAt: '2026-08-24', updatedAt: '2026-08-18', updatedBy: 'admin02', reviewDueAt: '2026-11-18', relatedFaqs: [{ id: 'FAQ-00131', title: '카드 환불은 언제 반영되나요?', status: '비공개' }], adminMemo: 'FAQ 공개 상태 확인 필요', versions: version('환불 처리 일정을 안내드립니다.'), history: history('REFUND_SCHEDULE_INFO'), memos: [] },
  { id: 'TPL-00178', name: '계정 재설정 안내', code: 'ACCOUNT_RESET_GUIDE', category: '회원 / 계정', status: '사용', inquiryTypes: ['회원 / 계정 > 비밀번호'], recommended: true, recommendationOrder: 1, subject: '계정 재설정 링크를 안내드립니다.', body: '안녕하세요, {고객명}님.\n본인 인증 후 비밀번호 재설정 링크를 등록 이메일로 발송해 드렸습니다.\n보안을 위해 링크는 30분간 유효합니다.', keywords: ['비밀번호', '로그인', '재설정'], channels: ['1:1 문의', '이메일', '채팅'], target: '전체 상담원', teams: [], displayOrder: 1, usageCount: 296, recent30Usage: 61, lastUsedAt: '2026-08-24', updatedAt: '2026-07-20', updatedBy: 'admin03', reviewDueAt: '2027-01-20', relatedFaqs: [], adminMemo: '', versions: version('비밀번호 재설정 링크를 발송했습니다.'), history: history('ACCOUNT_RESET_GUIDE'), memos: [] },
  { id: 'TPL-00177', name: '주문 취소 불가 안내', code: 'ORDER_CANCEL_REJECT', category: '주문', status: '사용', inquiryTypes: ['주문 > 주문 취소'], recommended: false, recommendationOrder: 3, subject: '', body: '안녕하세요, {고객명}님.\n주문 {주문번호}는 이미 출고가 시작되어 시스템에서 취소할 수 없습니다.\n상품 수령 후 반품 절차를 이용해 주세요.', keywords: ['취소불가', '출고', '반품'], channels: ['1:1 문의', '채팅'], target: '특정 팀', teams: ['주문 CS팀'], displayOrder: 3, usageCount: 102, recent30Usage: 21, lastUsedAt: '2026-08-21', updatedAt: '2026-03-03', updatedBy: 'admin01', reviewDueAt: '2026-09-03', relatedFaqs: [], adminMemo: '장기 미검토 예정', versions: version('출고 후 주문 취소는 불가합니다.'), history: history('ORDER_CANCEL_REJECT'), memos: [] },
  { id: 'TPL-00176', name: '파손 상품 사진 요청', code: 'DAMAGED_PHOTO_REQUEST', category: '교환 / 반품', status: '비활성', inquiryTypes: ['교환 / 반품 > 상품 파손'], recommended: false, recommendationOrder: 1, subject: '', body: '안녕하세요, {고객명}님.\n상품과 포장 상태를 확인할 수 있는 사진을 첨부해 주세요.\n확인 후 교환 절차를 안내드리겠습니다.', keywords: ['파손', '사진', '교환'], channels: ['1:1 문의'], target: '특정 팀', teams: ['배송 CS팀'], displayOrder: 1, usageCount: 0, recent30Usage: 0, lastUsedAt: null, updatedAt: '2026-08-24', updatedBy: 'admin01', reviewDueAt: '2027-02-24', relatedFaqs: [], adminMemo: '신규 검토 중', versions: version('파손 사진을 첨부해 주세요.', '초안 생성'), history: history('DAMAGED_PHOTO_REQUEST'), memos: [] },
  { id: 'TPL-00175', name: '배송 예정일 구버전', code: 'DELIVERY_DATE_LEGACY', category: '배송', status: '비활성', inquiryTypes: [], recommended: false, recommendationOrder: 9, subject: '', body: '안녕하세요. 예상 배송일은 {deliveryDate}입니다.', keywords: ['구버전', '배송'], channels: [], target: '전체 상담원', teams: [], displayOrder: 9, usageCount: 76, recent30Usage: 0, lastUsedAt: '2025-11-10', updatedAt: '2025-10-01', updatedBy: 'admin02', reviewDueAt: '2026-04-01', relatedFaqs: [], adminMemo: '신규 템플릿 전환 완료 후 보존', versions: version('예상 배송일은 {deliveryDate}입니다.'), history: history('DELIVERY_DATE_LEGACY'), memos: [] },
];

export function extractVariables(text: string): string[] { return [...new Set(text.match(/\{[^{}]+\}/g) ?? [])]; }
export function invalidVariables(item: Pick<ResponseTemplate, 'subject' | 'body'>): string[] { return extractVariables(`${item.subject}\n${item.body}`).filter((variable) => !SUPPORTED_VARIABLES.includes(variable)); }
export function templateIssues(item: ResponseTemplate): string[] {
  const issues: string[] = [];
  if (invalidVariables(item).length) issues.push(`변수 오류: ${invalidVariables(item).join(', ')}`);
  if (!item.inquiryTypes.length) issues.push('문의유형 연결 없음');
  if (!item.channels.length) issues.push('사용 채널 없음');
  if (item.relatedFaqs.some((faq) => faq.status === '비공개')) issues.push('관련 FAQ 비공개');
  if (!item.lastUsedAt || item.lastUsedAt < '2026-02-24') issues.push('장기 미사용');
  if (item.reviewDueAt < '2026-08-24') issues.push('검토 기한 경과');
  return issues;
}
export function sampleReplace(text: string): string { return extractVariables(text).reduce((result, variable) => result.replaceAll(variable, SAMPLE_VALUES[variable] ?? `⚠ ${variable} 값 없음`), text); }
export function newResponseTemplate(): ResponseTemplate { return { id: `TPL-${Date.now()}`, name: '', code: '', category: '배송', status: '비활성', inquiryTypes: [], recommended: false, recommendationOrder: 1, subject: '', body: '', keywords: [], channels: ['1:1 문의'], target: '전체 상담원', teams: [], displayOrder: 1, usageCount: 0, recent30Usage: 0, lastUsedAt: null, updatedAt: '2026-08-24', updatedBy: 'admin01', reviewDueAt: '2027-02-24', relatedFaqs: [], adminMemo: '', versions: [], history: [], memos: [] }; }
