import { useRef, useState } from 'react';
import drawer from '../ops/opsDrawerShared.module.css';
import styles from './ResponseTemplatesPage.module.css';
import { useOutsideClose } from '../../lib/useOutsideClose';
import { SUPPORTED_VARIABLES, TEMPLATE_CATEGORIES, TEMPLATE_CHANNELS, TEMPLATE_INQUIRY_TYPES, TEMPLATE_TEAMS, extractVariables, invalidVariables, sampleReplace, templateIssues, type ResponseTemplate, type TemplateChannel, type TemplateStatus } from './responseTemplatesData';

type Tab = 'content' | 'links' | 'preview' | 'usage' | 'version' | 'history';
interface Props { initial: ResponseTemplate; isNew: boolean; startMode?: 'view' | 'edit' | 'preview'; onClose: () => void; onSave: (item: ResponseTemplate, reason: string) => void; onDuplicate: (item: ResponseTemplate) => void; onDeactivate: (item: ResponseTemplate) => void; }

export function ResponseTemplateDrawer({ initial, isNew, startMode = 'view', onClose, onSave, onDuplicate, onDeactivate }: Props) {
  const [draft, setDraft] = useState(initial); const [editing, setEditing] = useState(isNew || startMode === 'edit'); const [tab, setTab] = useState<Tab>(startMode === 'preview' ? 'preview' : 'content');
  const [keyword, setKeyword] = useState(''); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const bodyRef = useRef<HTMLTextAreaElement>(null);
  const set = <K extends keyof ResponseTemplate>(key: K, value: ResponseTemplate[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const invalid = invalidVariables(draft); const usedVariables = extractVariables(`${draft.subject}\n${draft.body}`); const issues = templateIssues(draft);
  const insertVariable = (variable: string) => { const element = bodyRef.current; const start = element?.selectionStart ?? draft.body.length; const end = element?.selectionEnd ?? draft.body.length; set('body', `${draft.body.slice(0, start)}${variable}${draft.body.slice(end)}`); window.setTimeout(() => { element?.focus(); element?.setSelectionRange(start + variable.length, start + variable.length); }, 0); };
  const save = () => { if (!draft.name.trim() || !draft.code.trim() || !draft.body.trim()) return setError('템플릿명, 코드, 답변 본문은 필수입니다.'); if (invalid.length) return setError(`지원되지 않는 변수를 수정해 주세요: ${invalid.join(', ')}`); if (!draft.channels.length) return setError('사용 채널을 하나 이상 선택해 주세요.'); onSave({ ...draft, name: draft.name.trim(), code: draft.code.trim().toUpperCase().replace(/\s+/g, '_') }, reason.trim() || (isNew ? '템플릿 생성' : '답변 문구 수정')); };
  const toggle = <T,>(values: T[], value: T) => values.includes(value) ? values.filter((item) => item !== value) : [...values, value];

  const asideRef = useRef<HTMLElement>(null);
  useOutsideClose(asideRef, onClose);

  return <aside ref={asideRef} className={`${drawer.aside} ${styles.templateDrawer}`}>
    <div className={drawer.head}><div className={drawer.headRow}><div className={drawer.headBody}><div className={drawer.eyebrow}>{isNew ? '신규 답변 템플릿' : `${draft.id} · ${draft.code}`}</div><div className={drawer.titleRow}><h2 className={drawer.title}>{isNew ? '답변 템플릿 등록' : draft.name}</h2><span className={drawer.badge} style={{ background: draft.status === '사용' ? '#ecfdf5' : '#f4f4f5', color: draft.status === '사용' ? '#047857' : '#71717a' }}>{draft.status}</span>{draft.recommended && <span className={styles.recommendBadge}>★ 추천</span>}</div>{!isNew && <div className={drawer.sub}>{draft.category} · 최근 사용 {draft.lastUsedAt ?? '없음'} · 누적 {draft.usageCount.toLocaleString()}회</div>}</div><button type="button" className={drawer.closeBtn} onClick={onClose}>✕</button></div>
      {!isNew && <div className={drawer.actionRow}><button type="button" className={drawer.actionLink} onClick={() => { setEditing((current) => !current); setTab('content'); }}>{editing ? '수정 취소' : '수정'}</button><button type="button" className={drawer.actionLink} onClick={() => setTab('preview')}>미리보기</button><button type="button" className={drawer.actionLink} onClick={() => onDuplicate(draft)}>복제</button><span className={drawer.spacer} />{draft.status === '사용' && <button type="button" className={drawer.dangerBtn} onClick={() => onDeactivate(draft)}>비활성</button>}</div>}
      <div className={drawer.tabs}>{([['content', '답변 내용'], ['links', '연결·사용 설정'], ['preview', '미리보기'], ['usage', '사용 현황'], ['version', `Version ${draft.versions.length}`], ['history', '변경 이력']] as [Tab,string][]).map(([key,label]) => <button key={key} type="button" className={`${drawer.tabBtn} ${tab === key ? drawer.tabActive : ''}`} onClick={() => setTab(key)}>{label}</button>)}</div>
    </div>
    <div className={drawer.scroll}>
      {tab === 'content' && <>
        {issues.length > 0 && <div className={styles.issueBanner}><strong>검토 필요</strong>{issues.map((issue) => <span key={issue}>⚠ {issue}</span>)}</div>}
        <Section title="기본 정보"><div className={styles.formGrid}><Field label="템플릿명 *"><input disabled={!editing} value={draft.name} onChange={(e) => set('name', e.target.value)} placeholder="배송 지연 기본 안내" /></Field><Field label="템플릿 코드 *" hint={!isNew ? '생성 후 변경 불가' : '영문 대문자와 밑줄'}><input disabled={!editing || !isNew} value={draft.code} onChange={(e) => set('code', e.target.value)} placeholder="DELIVERY_DELAY_BASIC" /></Field><Field label="카테고리 *"><select disabled={!editing} value={draft.category} onChange={(e) => set('category', e.target.value)}>{TEMPLATE_CATEGORIES.map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="상태"><select disabled={!editing} value={draft.status} onChange={(e) => set('status', e.target.value as TemplateStatus)}><option>사용</option><option>비활성</option></select></Field></div></Section>
        <Section title="답변 문구"><Field label="답변 제목" hint="이메일 채널에서 사용"><input disabled={!editing} value={draft.subject} onChange={(e) => set('subject', e.target.value)} placeholder="답변 제목 (선택)" /></Field><div className={styles.editorToolbar}><button type="button" disabled={!editing} onClick={() => insertVariable('{고객명}')}>+ 고객명</button><button type="button" disabled={!editing} onClick={() => insertVariable('{주문번호}')}>+ 주문번호</button><button type="button" disabled={!editing} onClick={() => insertVariable('{현재일자}')}>+ 현재일자</button><span>자동 발송이 아닌 상담원 선택·수정용 문구입니다.</span></div><textarea ref={bodyRef} className={styles.bodyEditor} disabled={!editing} value={draft.body} onChange={(e) => set('body', e.target.value)} placeholder="고객에게 전달할 답변 문구를 입력하세요." />
          <div className={styles.variablePanel}><div><strong>사용중 변수</strong><div className={styles.chipRow}>{usedVariables.length ? usedVariables.map((variable) => <span key={variable} className={SUPPORTED_VARIABLES.includes(variable) ? '' : styles.invalidChip}>{variable}</span>) : <em>사용중인 변수가 없습니다.</em>}</div></div>{editing && <div><strong>변수 삽입</strong><div className={styles.variableButtons}>{SUPPORTED_VARIABLES.map((variable) => <button key={variable} type="button" onClick={() => insertVariable(variable)}>{variable}</button>)}</div></div>}</div>{invalid.length > 0 && <div className={styles.validationError}>⚠ 지원되지 않는 변수입니다: {invalid.join(', ')}. 저장이 차단됩니다.</div>}
        </Section>
        <Section title="검색 설정"><div className={styles.keywordList}>{draft.keywords.map((value) => <span key={value}>{value}{editing && <button type="button" onClick={() => set('keywords', draft.keywords.filter((item) => item !== value))}>×</button>}</span>)}</div>{editing && <div className={styles.addRow}><input value={keyword} onChange={(e) => setKeyword(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); if (keyword.trim() && !draft.keywords.includes(keyword.trim())) set('keywords', [...draft.keywords, keyword.trim()]); setKeyword(''); } }} placeholder="검색 키워드 입력" /><button type="button" onClick={() => { if (keyword.trim() && !draft.keywords.includes(keyword.trim())) set('keywords', [...draft.keywords, keyword.trim()]); setKeyword(''); }}>+ 추가</button></div>}</Section>
        <Section title="내부 관리"><Field label="관리자 메모"><textarea disabled={!editing} value={draft.adminMemo} onChange={(e) => set('adminMemo', e.target.value)} /></Field>{editing && <Field label="변경 사유" hint="새 Version과 Audit에 기록"><input value={reason} onChange={(e) => setReason(e.target.value)} placeholder="예: 배송 안내 정책 변경" /></Field>}</Section>
      </>}

      {tab === 'links' && <>
        <Section title="문의 유형 연결 (복수 선택)"><div className={styles.checkList}>{TEMPLATE_INQUIRY_TYPES.map((value) => <label key={value}><input type="checkbox" disabled={!editing} checked={draft.inquiryTypes.includes(value)} onChange={() => set('inquiryTypes', toggle(draft.inquiryTypes, value))} />{value}</label>)}</div><label className={styles.recommendToggle}><input type="checkbox" disabled={!editing} checked={draft.recommended} onChange={(e) => set('recommended', e.target.checked)} /> 연결된 문의 유형의 답변창에서 우선 추천</label>{draft.recommended && <Field label="추천 우선순위"><input type="number" min="1" disabled={!editing} value={draft.recommendationOrder} onChange={(e) => set('recommendationOrder', Number(e.target.value))} /></Field>}</Section>
        <Section title="사용 채널 / 대상"><div className={styles.channelChecks}>{TEMPLATE_CHANNELS.map((value) => <label key={value}><input type="checkbox" disabled={!editing} checked={draft.channels.includes(value)} onChange={() => set('channels', toggle(draft.channels, value as TemplateChannel))} />{value}</label>)}</div><div className={styles.formGrid}><Field label="사용 대상"><select disabled={!editing} value={draft.target} onChange={(e) => set('target', e.target.value as ResponseTemplate['target'])}><option>전체 상담원</option><option>특정 팀</option></select></Field><Field label="노출 순서"><input type="number" min="1" disabled={!editing} value={draft.displayOrder} onChange={(e) => set('displayOrder', Number(e.target.value))} /></Field></div>{draft.target === '특정 팀' && <div className={styles.channelChecks}>{TEMPLATE_TEAMS.map((value) => <label key={value}><input type="checkbox" disabled={!editing} checked={draft.teams.includes(value)} onChange={() => set('teams', toggle(draft.teams, value))} />{value}</label>)}</div>}</Section>
        <Section title="관련 FAQ">{draft.relatedFaqs.length ? draft.relatedFaqs.map((faq) => <div key={faq.id} className={styles.faqRow}><span>{faq.id}</span><strong>{faq.title}</strong><em className={faq.status === '비공개' ? styles.faqHidden : ''}>{faq.status}</em><button type="button">보기 ↗</button></div>) : <div className={drawer.emptyInline}>연결된 FAQ가 없습니다.</div>}</Section>
      </>}

      {tab === 'preview' && <div className={styles.previewGrid}><div className={styles.previewCard}><span>원본 템플릿</span>{draft.subject && <h3>{draft.subject}</h3>}<pre>{draft.body || '(답변 본문 없음)'}</pre><div className={styles.previewVariables}>{usedVariables.join(' · ') || '변수 없음'}</div></div><div className={styles.previewCard}><span>샘플 데이터 적용</span>{draft.subject && <h3>{sampleReplace(draft.subject)}</h3>}<pre>{sampleReplace(draft.body) || '(답변 본문 없음)'}</pre>{invalid.length ? <div className={styles.validationError}>미치환 변수가 있어 실제 답변 발송이 차단됩니다.</div> : <div className={styles.previewSuccess}>✓ 모든 변수가 샘플 데이터로 치환되었습니다.</div>}</div></div>}
      {tab === 'usage' && <><div className={styles.usageGrid}><Stat label="누적 사용" value={`${draft.usageCount.toLocaleString()}회`} /><Stat label="최근 30일" value={`${draft.recent30Usage}회`} /><Stat label="최근 사용" value={draft.lastUsedAt ?? '-'} /><Stat label="연결 유형" value={`${draft.inquiryTypes.length}개`} /></div><div className={styles.snapshotNotice}>템플릿 수정은 앞으로 불러오는 답변부터 적용됩니다. 이미 고객에게 발송된 최종 답변 Snapshot은 변경되지 않습니다.</div><Section title="최근 사용 상담"><div className={styles.usageRow}><span>QNA-00182</span><strong>배송이 아직 도착하지 않았어요</strong><em>admin01 · 수정 후 발송</em></div><div className={styles.usageRow}><span>QNA-00171</span><strong>현재 배송 상태 문의</strong><em>admin02 · 원문 사용</em></div></Section></>}
      {tab === 'version' && <>{draft.versions.slice().reverse().map((version, index) => <div key={version.version} className={`${styles.versionCard} ${index === 0 ? styles.currentVersion : ''}`}><div><strong>V{version.version} {index === 0 && <span>현재</span>}</strong><em>{version.at} · {version.by}</em></div><p>{version.reason}</p><pre>{version.body}</pre></div>)}{!draft.versions.length && <div className={drawer.emptyInline}>저장 후 Version이 생성됩니다.</div>}</>}
      {tab === 'history' && <><Section title="관리자 메모">{draft.memos.length ? draft.memos.map((memo) => <div key={memo.id} className={styles.memoRow}><div><strong>{memo.by}</strong><span>{memo.at}</span></div><p>{memo.body}</p></div>) : <div className={drawer.emptyInline}>등록된 관리자 메모가 없습니다.</div>}</Section><Section title="변경 이력">{draft.history.slice().reverse().map((item) => <div key={item.id} className={drawer.timelineItem}><span className={drawer.timelineDot} /><div className={drawer.timelineBody}><div className={drawer.timelineRow}><strong className={drawer.timelineTitle}>{item.action}</strong><span className={drawer.timelineWhen}>{item.at}</span></div><div className={drawer.timelineDetail}>{item.by}{item.detail ? ` · ${item.detail}` : ''}</div></div></div>)}</Section></>}
      {error && <div className={styles.formError}>{error}</div>}
    </div>
    {editing && <div className={drawer.footer}><button type="button" className={drawer.editCancel} onClick={isNew ? onClose : () => { setDraft(initial); setEditing(false); }}>취소</button><button type="button" className={drawer.editCancel} onClick={() => setTab('preview')}>미리보기</button><button type="button" className={drawer.editConfirm} onClick={save}>{isNew ? '등록' : '수정 저장'}</button></div>}
  </aside>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className={styles.formSection}><h3>{title}</h3>{children}</section>; }
function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) { return <label className={styles.formField}><span>{label}{hint && <small>{hint}</small>}</span>{children}</label>; }
function Stat({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
