import { useMemo, useState } from 'react';
import { DataGrid } from '../../components/DataGrid/DataGrid';
import type { GridRow } from '../../components/DataGrid/types';
import shared from '../ops/opsShared.module.css';
import drawer from '../ops/opsDrawerShared.module.css';
import { ResponseTemplateDrawer } from './ResponseTemplateDrawer';
import styles from './ResponseTemplatesPage.module.css';
import { RESPONSE_TEMPLATES, TEMPLATE_CATEGORIES, TEMPLATE_CHANNELS, TEMPLATE_TEAMS, newResponseTemplate, templateIssues, type ResponseTemplate, type TemplateStatus } from './responseTemplatesData';

type QuickFilter = '전체' | '사용중' | '비활성' | '자주 사용' | '검토 필요' | '내 팀 템플릿' | '미사용 템플릿';
type DrawerMode = 'view' | 'edit' | 'preview';
type Confirm = { kind: 'deactivate' | 'delete'; item: ResponseTemplate } | null;
const QUICK_FILTERS: QuickFilter[] = ['전체', '사용중', '비활성', '자주 사용', '검토 필요', '내 팀 템플릿', '미사용 템플릿'];
const COLUMNS = [{ label: '템플릿명' }, { label: '문의 유형' }, { label: '카테고리' }, { label: '사용 채널' }, { label: '추천' }, { label: '담당팀' }, { label: '사용 횟수' }, { label: '최근 사용' }, { label: '상태' }, { label: '수정일 / 수정자' }, { label: '관리', align: 'right' as const }];
function quickMatch(item: ResponseTemplate, filter: QuickFilter) { if (filter === '사용중') return item.status === '사용'; if (filter === '비활성') return item.status === '비활성'; if (filter === '자주 사용') return item.recent30Usage >= 40; if (filter === '검토 필요') return templateIssues(item).length > 0; if (filter === '내 팀 템플릿') return item.target === '전체 상담원' || item.teams.includes('배송 CS팀'); if (filter === '미사용 템플릿') return !item.lastUsedAt || item.lastUsedAt < '2026-02-24'; return true; }

export function ResponseTemplatesPage() {
  const [templates, setTemplates] = useState(RESPONSE_TEMPLATES); const [quickFilter, setQuickFilter] = useState<QuickFilter>('전체'); const [keyword, setKeyword] = useState(''); const [search, setSearch] = useState('');
  const [inquiryType, setInquiryType] = useState(''); const [category, setCategory] = useState(''); const [channel, setChannel] = useState(''); const [team, setTeam] = useState(''); const [status, setStatus] = useState<TemplateStatus | ''>(''); const [modifiedFrom, setModifiedFrom] = useState(''); const [showAdvanced, setShowAdvanced] = useState(false);
  const [selected, setSelected] = useState<string[]>([]); const [openMenu, setOpenMenu] = useState<string | null>(null); const [drawerItem, setDrawerItem] = useState<ResponseTemplate | null>(null); const [isNew, setIsNew] = useState(false); const [drawerMode, setDrawerMode] = useState<DrawerMode>('view'); const [confirm, setConfirm] = useState<Confirm>(null); const [deactivateReason, setDeactivateReason] = useState('문구 개편'); const [toast, setToast] = useState('');
  const filtered = useMemo(() => templates.filter((item) => { if (!quickMatch(item, quickFilter)) return false; const haystack = `${item.name} ${item.code} ${item.body} ${item.keywords.join(' ')} ${item.inquiryTypes.join(' ')}`.toLowerCase(); if (search && !haystack.includes(search.toLowerCase())) return false; if (inquiryType && !item.inquiryTypes.some((value) => value.includes(inquiryType))) return false; if (category && item.category !== category) return false; if (channel && !item.channels.includes(channel as ResponseTemplate['channels'][number])) return false; if (team === '전체 상담원' ? item.target !== '전체 상담원' : team && !item.teams.includes(team)) return false; if (status && item.status !== status) return false; if (modifiedFrom && item.updatedAt < modifiedFrom) return false; return true; }), [templates, quickFilter, search, inquiryType, category, channel, team, status, modifiedFrom]);
  const toastBriefly = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400); };
  const reset = () => { setKeyword(''); setSearch(''); setInquiryType(''); setCategory(''); setChannel(''); setTeam(''); setStatus(''); setModifiedFrom(''); setSelected([]); };
  const open = (item: ResponseTemplate, mode: DrawerMode) => { setDrawerItem(item); setIsNew(false); setDrawerMode(mode); };
  const create = (seed = newResponseTemplate()) => { setDrawerItem(seed); setIsNew(true); setDrawerMode('edit'); };
  const duplicate = (item: ResponseTemplate) => create({ ...item, id: `TPL-${Date.now()}`, name: `[복사본] ${item.name}`, code: '', status: '비활성', recommended: false, usageCount: 0, recent30Usage: 0, lastUsedAt: null, versions: [], history: [], memos: [], updatedAt: '2026-08-24', updatedBy: 'admin01' });
  const save = (item: ResponseTemplate, reason: string) => {
    if (isNew) { const created = { ...item, versions: [{ version: 1, at: '2026-08-24 14:00', by: 'admin01', reason, body: item.body }], history: [{ id: `H-${Date.now()}`, at: '2026-08-24 14:00', by: 'admin01', action: '템플릿 생성', detail: reason }], memos: item.adminMemo ? [{ id: `M-${Date.now()}`, at: '2026-08-24', by: 'admin01', body: item.adminMemo }] : [] }; setTemplates((current) => [created, ...current]); setDrawerItem(created); setIsNew(false); setDrawerMode('view'); toastBriefly('답변 템플릿을 등록했습니다.'); }
    else { const previous = templates.find((value) => value.id === item.id); const updated = { ...item, updatedAt: '2026-08-24', updatedBy: 'admin01', versions: [...item.versions, { version: (item.versions.at(-1)?.version ?? 0) + 1, at: '2026-08-24 14:00', by: 'admin01', reason, body: item.body }], history: [...item.history, { id: `H-${Date.now()}`, at: '2026-08-24 14:00', by: 'admin01', action: '템플릿 수정', detail: `${reason}${previous?.body !== item.body ? ' · 본문 변경' : ''}` }], memos: item.adminMemo && item.adminMemo !== previous?.adminMemo ? [...item.memos, { id: `M-${Date.now()}`, at: '2026-08-24', by: 'admin01', body: item.adminMemo }] : item.memos }; setTemplates((current) => current.map((value) => value.id === item.id ? updated : value)); setDrawerItem(updated); setDrawerMode('view'); toastBriefly('새 Version으로 저장했습니다. 기존 발송 답변은 유지됩니다.'); }
  };
  const confirmAction = () => { if (!confirm) return; if (confirm.kind === 'delete') { setTemplates((current) => current.filter((item) => item.id !== confirm.item.id)); setDrawerItem(null); toastBriefly('사용 이력이 없는 템플릿을 삭제했습니다.'); } else { const updated = { ...confirm.item, status: '비활성' as const, updatedAt: '2026-08-24', updatedBy: 'admin01', history: [...confirm.item.history, { id: `H-${Date.now()}`, at: '2026-08-24 14:00', by: 'admin01', action: '템플릿 비활성', detail: deactivateReason }] }; setTemplates((current) => current.map((item) => item.id === updated.id ? updated : item)); setDrawerItem(null); toastBriefly('새 상담의 검색·추천에서 제외했습니다.'); } setConfirm(null); };
  const download = (targets: ResponseTemplate[]) => { const csv = [['템플릿번호','템플릿명','코드','카테고리','문의유형','채널','담당팀','추천','사용횟수','최근사용','상태'], ...targets.map((item) => [item.id,item.name,item.code,item.category,item.inquiryTypes.join(' / '),item.channels.join(' / '),item.target === '전체 상담원' ? item.target : item.teams.join(' / '),item.recommended ? '추천' : '-',item.usageCount,item.lastUsedAt ?? '',item.status])].map((row) => row.map((value) => `"${String(value).replaceAll('"','""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type:'text/csv;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href=url; anchor.download='response-templates.csv'; anchor.click(); URL.revokeObjectURL(url); };

  const rows: GridRow[] = filtered.map((item) => { const issues = templateIssues(item); return { id:item.id, selected:selected.includes(item.id), onToggleSelect:()=>setSelected((current)=>current.includes(item.id)?current.filter((id)=>id!==item.id):[...current,item.id]), onClick:()=>open(item,'view'), bg:issues.length?'#fffdf8':undefined, cells:[
    {kind:'titleWarn',title:item.name,hasIssue:issues.length>0,issueTitle:issues.join(' · ')},{kind:'stack',title:item.inquiryTypes[0]??'연결 없음',subtitle:item.inquiryTypes.length>1?`외 ${item.inquiryTypes.length-1}개`:`${item.code}`},{kind:'pillText',text:item.category,bg:'#f4f4f5',fg:'#52525b'},{kind:'text',text:item.channels.join(' / ')||'없음',color:item.channels.length?'#3f3f46':'#dc2626',size:'11px'},{kind:'badge',text:item.recommended?`★ ${item.recommendationOrder}순위`:'-',bg:item.recommended?'#fffbeb':'#f4f4f5',fg:item.recommended?'#a16207':'#a1a1aa'},{kind:'text',text:item.target==='전체 상담원'?'전체 상담원':item.teams.join(' / ')||'미설정',size:'11px'},{kind:'stack',title:`${item.usageCount.toLocaleString()}회`,subtitle:`30일 ${item.recent30Usage}회`},{kind:'text',text:item.lastUsedAt??'사용 없음',color:item.lastUsedAt?'#52525b':'#a1a1aa',numeric:true},{kind:'statusDot',text:item.status,dot:item.status==='사용'?'#10b981':'#a1a1aa',fg:item.status==='사용'?'#047857':'#71717a'},{kind:'stack',title:item.updatedAt,subtitle:item.updatedBy},{kind:'rowMenu',align:'right',detailLabel:'상세',onDetail:()=>open(item,'view'),open:openMenu===item.id,onToggle:()=>setOpenMenu(openMenu===item.id?null:item.id),items:[{label:'수정',click:()=>open(item,'edit')},{label:'미리보기',click:()=>open(item,'preview')},{label:'사용 상담 보기',click:()=>window.location.assign('/cs/consultations')},{sep:true},{label:'복제',click:()=>duplicate(item)},item.status==='사용'?{label:'비활성화',fg:'#dc2626',click:()=>setConfirm({kind:'deactivate',item})}:{label:'활성화',click:()=>setTemplates((current)=>current.map((value)=>value.id===item.id?{...value,status:'사용'}:value))},...(item.usageCount===0?[{label:'삭제',fg:'#dc2626',click:()=>setConfirm({kind:'delete',item})}]:[])]}
  ]}; });

  return <section className={shared.page} onClick={()=>openMenu&&setOpenMenu(null)}><div className={shared.headTop}><div className={shared.headRow}><div><h1 className={shared.title}>답변 템플릿</h1><p className={shared.subtitle}>상담원이 답변 작성 시 불러오는 공통 문구와 자동 치환 변수를 관리합니다.</p></div><button type="button" className={shared.createBtn} onClick={()=>create()}>+ 템플릿 등록</button></div>
    <div className={shared.quickFilters}>{QUICK_FILTERS.map((filter)=><button key={filter} type="button" className={`${shared.qfBtn} ${quickFilter===filter?styles.quickActive:''}`} onClick={()=>{setQuickFilter(filter);setSelected([]);}}><span className={shared.qfLabel}>{filter}</span><span className={shared.qfCount}>{templates.filter((item)=>quickMatch(item,filter)).length}</span></button>)}</div>
    <div className={shared.filterBox}><form className={shared.filterRow1} onSubmit={(event)=>{event.preventDefault();setSearch(keyword.trim());}}><select className={shared.selectSm}><option>전체 검색</option><option>템플릿명</option><option>답변 본문</option><option>검색 키워드</option></select><input className={shared.searchInput} value={keyword} onChange={(e)=>setKeyword(e.target.value)} placeholder="템플릿명, 내용, 키워드 검색"/><button type="submit" className={shared.searchBtn}>검색</button></form><div className={shared.filterRow2}><select className={shared.selectSm} value={inquiryType} onChange={(e)=>setInquiryType(e.target.value)}><option value="">전체 문의유형</option>{TEMPLATE_CATEGORIES.map((value)=><option key={value}>{value}</option>)}</select><select className={shared.selectSm} value={category} onChange={(e)=>setCategory(e.target.value)}><option value="">전체 카테고리</option>{TEMPLATE_CATEGORIES.map((value)=><option key={value}>{value}</option>)}</select><select className={shared.selectSm} value={channel} onChange={(e)=>setChannel(e.target.value)}><option value="">전체 채널</option>{TEMPLATE_CHANNELS.map((value)=><option key={value}>{value}</option>)}</select><select className={shared.selectSm} value={team} onChange={(e)=>setTeam(e.target.value)}><option value="">전체 담당팀</option><option>전체 상담원</option>{TEMPLATE_TEAMS.map((value)=><option key={value}>{value}</option>)}</select><select className={shared.selectSm} value={status} onChange={(e)=>setStatus(e.target.value as TemplateStatus|'')}><option value="">전체 상태</option><option>사용</option><option>비활성</option></select><button type="button" className={shared.detailFilterBtn} onClick={()=>setShowAdvanced((current)=>!current)}>상세 필터 {showAdvanced?'−':'+'}</button><span className={shared.rowSpacer}/><button type="button" className={shared.resetBtn} onClick={reset}>필터 초기화</button></div>{showAdvanced&&<div className={styles.advancedFilters}><label>수정일 이후<input type="date" value={modifiedFrom} onChange={(e)=>setModifiedFrom(e.target.value)}/></label><span>답변 본문과 변수 변경은 개별 템플릿에서만 가능합니다.</span></div>}</div>
  </div>
  {selected.length>0&&<div className={shared.bulkBar}><span className={shared.bulkLabel}>{selected.length}건 선택</span><select className={shared.selectXs} defaultValue="" onChange={(e)=>{const value=e.target.value;if(!value)return;setTemplates((current)=>current.map((item)=>selected.includes(item.id)?{...item,category:value}:item));e.target.value='';toastBriefly('카테고리를 일괄 변경했습니다.');}}><option value="">카테고리 변경</option>{TEMPLATE_CATEGORIES.map((value)=><option key={value}>{value}</option>)}</select><select className={shared.selectXs} defaultValue="" onChange={(e)=>{const value=e.target.value;if(!value)return;setTemplates((current)=>current.map((item)=>selected.includes(item.id)?{...item,target:'특정 팀',teams:[value]}:item));e.target.value='';toastBriefly('사용 대상 팀을 변경했습니다.');}}><option value="">담당팀 변경</option>{TEMPLATE_TEAMS.map((value)=><option key={value}>{value}</option>)}</select><select className={shared.selectXs} defaultValue="" onChange={(e)=>{const value=e.target.value as TemplateStatus;if(!value)return;setTemplates((current)=>current.map((item)=>selected.includes(item.id)?{...item,status:value}:item));e.target.value='';}}><option value="">상태 변경</option><option>사용</option><option>비활성</option></select><button type="button" className={shared.bulkBtn} onClick={()=>download(templates.filter((item)=>selected.includes(item.id)))}>선택 다운로드</button><span className={styles.bulkGuard}>답변 본문·변수는 안전을 위해 일괄 변경할 수 없습니다.</span></div>}
  <div className={shared.gridWrap}><div className={shared.resultRow}><span className={shared.resultLabel}>총 {filtered.length}건</span><div className={shared.resultActions}><button type="button" className={shared.downloadBtn} onClick={()=>download(filtered)}>목록 다운로드</button><select className={shared.pageSizeSelect}><option>20개씩</option><option>50개씩</option></select></div></div><DataGrid columns={COLUMNS} rows={rows} gridTemplate="178px 176px 92px 128px 88px 118px 92px 94px 78px 112px 90px" minWidth="1330px" selectable allSelected={filtered.length>0&&filtered.every((item)=>selected.includes(item.id))} onToggleAll={()=>setSelected(filtered.every((item)=>selected.includes(item.id))?[]:filtered.map((item)=>item.id))} empty={filtered.length===0} emptyText={quickFilter==='검토 필요'?'현재 확인이 필요한 답변 템플릿이 없습니다.':'검색 결과가 없습니다.'} emptySubtext="검색어나 필터 조건을 변경해 주세요." emptyActionLabel="필터 초기화" emptyActionClick={reset} showPagination pages={[{label:'‹'},{label:'1',active:true},{label:'›'}]} rangeLabel={filtered.length?`1–${filtered.length} / ${filtered.length}`:'0건'}/></div>
  {drawerItem&&<ResponseTemplateDrawer key={`${drawerItem.id}-${isNew}-${drawerMode}`} initial={drawerItem} isNew={isNew} startMode={drawerMode} onClose={()=>setDrawerItem(null)} onSave={save} onDuplicate={duplicate} onDeactivate={(item)=>setConfirm({kind:'deactivate',item})}/>} 
  {confirm&&<div className={shared.dialogOverlay}><div className={shared.dialogBox}><h2 className={shared.dialogTitle}>{confirm.kind==='delete'?'답변 템플릿 삭제':'답변 템플릿 비활성화'}</h2><p className={shared.dialogBody}>{confirm.kind==='delete'?'사용 및 발송 연결 이력이 없는 템플릿입니다. 삭제 후 복구할 수 없습니다.':'새로운 상담의 검색·추천에서 제외됩니다. 이미 고객에게 발송된 답변 Snapshot은 변경되지 않습니다.'}</p><div className={shared.dialogSummary}><div className={shared.dialogSummaryRow}><span>템플릿</span><strong>{confirm.item.name}</strong></div><div className={shared.dialogSummaryRow}><span>최근 30일 사용</span><strong>{confirm.item.recent30Usage}회</strong></div><div className={shared.dialogSummaryRow}><span>연결 문의유형</span><strong>{confirm.item.inquiryTypes.length}개</strong></div></div>{confirm.kind==='deactivate'&&<label className={drawer.formGroup}><span className={drawer.formLabel}>비활성화 사유</span><input className={drawer.formInput} value={deactivateReason} onChange={(e)=>setDeactivateReason(e.target.value)}/></label>}<div className={shared.dialogActions}><button type="button" className={drawer.editCancel} onClick={()=>setConfirm(null)}>취소</button><button type="button" className={styles.dangerButton} onClick={confirmAction}>{confirm.kind==='delete'?'삭제':'비활성화'}</button></div></div></div>}
  {toast&&<div className={styles.toast}>{toast}</div>}</section>;
}
