import { useMemo, useState } from 'react';
import { DataGrid } from '../../components/DataGrid';
import type { GridRow } from '../../components/DataGrid/types';
import { DatePicker } from '../../components/forms/DatePicker';
import drawer from '../ops/opsDrawerShared.module.css';
import shared from '../ops/opsShared.module.css';
import styles from './ModulePlaceholderPage.module.css';
import { CommonButton } from '../../components/common';

interface Props { title: string; subtitle: string; icon?: string; kind?: 'management' | 'analytics' }
interface Entry { id: string; name: string; type: string; status: string; owner: string; createdAt: string; updatedAt: string; note: string }
const STATUS_COLORS: Record<string, { bg: string; fg: string }> = {
  정상: { bg: '#ecfdf5', fg: '#047857' }, 사용: { bg: '#ecfdf5', fg: '#047857' }, 승인: { bg: '#ecfdf5', fg: '#047857' }, 완료: { bg: '#ecfdf5', fg: '#047857' }, 처리완료: { bg: '#ecfdf5', fg: '#047857' }, 진행중: { bg: '#ecfdf5', fg: '#047857' },
  대기: { bg: '#eff6ff', fg: '#2563eb' }, 검토중: { bg: '#eff6ff', fg: '#2563eb' }, 예정: { bg: '#eff6ff', fg: '#2563eb' }, 요청: { bg: '#eff6ff', fg: '#2563eb' },
  주의: { bg: '#fff7ed', fg: '#c2410c' }, 부족: { bg: '#fff7ed', fg: '#c2410c' }, 보류: { bg: '#fff7ed', fg: '#c2410c' }, 신고: { bg: '#fff7ed', fg: '#c2410c' },
  반려: { bg: '#fef2f2', fg: '#dc2626' }, 실패: { bg: '#fef2f2', fg: '#dc2626' }, 제한: { bg: '#fef2f2', fg: '#dc2626' }, 품절: { bg: '#fef2f2', fg: '#dc2626' },
  중지: { bg: '#f4f4f5', fg: '#71717a' }, 숨김: { bg: '#f4f4f5', fg: '#71717a' }, 삭제: { bg: '#f4f4f5', fg: '#71717a' }, 해제: { bg: '#f4f4f5', fg: '#71717a' },
};
function seed(text: string) { return [...text].reduce((sum, char) => sum + char.charCodeAt(0), 0); }
function statusesFor(title: string) { if (/재고|품절/.test(title)) return ['정상', '부족', '품절', '주의']; if (/취소|반품|교환/.test(title)) return ['요청', '검토중', '완료', '반려']; if (/신고|분쟁/.test(title)) return ['대기', '검토중', '처리완료', '반려']; if (/제재|제한|금지/.test(title)) return ['대기', '승인', '제한', '해제']; if (/배송|출고|회수/.test(title)) return ['대기', '진행중', '완료', '실패']; if (/정산|대금|출금/.test(title)) return ['예정', '검토중', '완료', '보류']; if (/인증/.test(title)) return ['정상', '대기', '완료', '실패']; if (/설정|정책|코드|템플릿|배송사|브랜드/.test(title)) return ['사용', '대기', '중지', '삭제']; return ['정상', '대기', '완료', '중지']; }
function typesFor(title: string) { if (/배송/.test(title)) return ['일반 배송', '묶음 배송', '도서산간']; if (/상품|재고/.test(title)) return ['일반 상품', '옵션 상품', '세트 상품']; if (/회원|판매자|구매자|인증/.test(title)) return ['일반 회원', '우수 회원', '사업자']; if (/신고|분쟁|제재/.test(title)) return ['회원', '상품', '거래']; if (/쿠폰|할인|프로모션|포인트/.test(title)) return ['정액', '정률', '조건형']; return ['기본', '자동', '관리자']; }
function initialEntries(title: string): Entry[] { const base = seed(title); const statuses = statusesFor(title); const types = typesFor(title); return Array.from({ length: 12 }, (_, index) => ({ id: `${title.replaceAll(' ', '').slice(0, 3).toUpperCase()}-${String(base % 900 + index + 100).padStart(4, '0')}`, name: `${title} ${String(index + 1).padStart(2, '0')}`, type: types[index % types.length], status: statuses[index % statuses.length], owner: `admin0${index % 4 + 1}`, createdAt: `2026-08-${String(26 - index).padStart(2, '0')}`, updatedAt: `2026-08-${String(26 - Math.floor(index / 2)).padStart(2, '0')} ${String(9 + index % 8).padStart(2, '0')}:20`, note: `${title} 업무 기준에 따라 등록된 관리 항목입니다. 관련 대상과 처리 상태를 확인할 수 있습니다.` })); }

export function ModulePlaceholderPage({ title, subtitle, icon = '▧', kind = 'management' }: Props) { if (kind === 'analytics') return <AnalyticsPage title={title} subtitle={subtitle} icon={icon}/>; return <ManagementPage title={title} subtitle={subtitle} icon={icon}/>; }

function ManagementPage({ title, subtitle, icon }: Required<Pick<Props, 'title' | 'subtitle' | 'icon'>>) {
  const [entries, setEntries] = useState<Entry[]>(() => initialEntries(title)); const [quick, setQuick] = useState('전체'); const [keyword, setKeyword] = useState(''); const [search, setSearch] = useState(''); const [typeFilter, setTypeFilter] = useState(''); const [statusFilter, setStatusFilter] = useState(''); const [selectedId, setSelectedId] = useState<string | null>(null); const [editorOpen, setEditorOpen] = useState(false); const [form, setForm] = useState({ name: '', type: typesFor(title)[0], status: statusesFor(title)[0], note: '' }); const [toast, setToast] = useState('');
  const statuses = statusesFor(title); const types = typesFor(title); const selected = entries.find((entry) => entry.id === selectedId) ?? null;
  const filtered = useMemo(() => entries.filter((entry) => (quick === '전체' || entry.status === quick) && (!typeFilter || entry.type === typeFilter) && (!statusFilter || entry.status === statusFilter) && (!search || `${entry.id} ${entry.name} ${entry.owner}`.toLowerCase().includes(search.toLowerCase()))), [entries, quick, search, statusFilter, typeFilter]);
  function reset() { setQuick('전체'); setKeyword(''); setSearch(''); setTypeFilter(''); setStatusFilter(''); }
  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(''), 2200); }
  function save() { if (!form.name.trim()) return notify('관리 항목명을 입력해 주세요.'); const entry: Entry = { id: `${title.replaceAll(' ', '').slice(0, 3).toUpperCase()}-${Date.now().toString().slice(-5)}`, name: form.name.trim(), type: form.type, status: form.status, owner: 'admin01', createdAt: '2026-08-26', updatedAt: '2026-08-26 15:40', note: form.note.trim() || `${title} 신규 관리 항목` }; setEntries((current) => [entry, ...current]); setEditorOpen(false); setSelectedId(entry.id); notify('관리 항목을 등록했습니다.'); }
  function updateStatus(status: string) { if (!selected) return; setEntries((current) => current.map((entry) => entry.id === selected.id ? { ...entry, status, updatedAt: '2026-08-26 15:40' } : entry)); notify(`상태를 ${status}(으)로 변경했습니다.`); }
  function download() { const csv = [['관리번호', '항목명', '구분', '상태', '담당자', '등록일', '수정일'], ...filtered.map((entry) => [entry.id, entry.name, entry.type, entry.status, entry.owner, entry.createdAt, entry.updatedAt])].map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = `${title}-목록.csv`; a.click(); URL.revokeObjectURL(url); }
  const rows: GridRow[] = filtered.map((entry) => { const meta = STATUS_COLORS[entry.status] ?? { bg: '#f4f4f5', fg: '#52525b' }; return { id: entry.id, onClick: () => setSelectedId(entry.id), cells: [{ kind: 'link', text: entry.id }, { kind: 'stack', title: entry.name, subtitle: entry.note }, { kind: 'pillText', text: entry.type, bg: '#f4f4f5', fg: '#52525b' }, { kind: 'badge', text: entry.status, bg: meta.bg, fg: meta.fg }, { kind: 'text', text: entry.owner }, { kind: 'text', text: entry.createdAt, numeric: true }, { kind: 'text', text: entry.updatedAt, numeric: true }] }; });
  const quicks = ['전체', ...statuses];
  return <section className={shared.page}><div className={shared.headTop}><div className={shared.headRow}><div><div className={styles.titleLine}><span className={styles.moduleIcon}>{icon}</span><h1 className={shared.title}>{title}</h1></div><p className={shared.subtitle}>{subtitle}</p></div><button type="button" className={shared.createBtn} onClick={() => { setForm({ name: '', type: types[0], status: statuses[0], note: '' }); setEditorOpen(true); }}>+ {title} 등록</button></div><div className={shared.quickFilters}>
  {quicks.map((item) => {
    const active = quick === item;
    return (
      <CommonButton
        key={item}
        type="button"
        variant={active ? 'primary-light' : 'secondary'}
        size="md"
        className={`${shared.qfBtn} ${active ? styles.quickActive : ''}`}
        onClick={() => setQuick(item)}
      >
        <span className={shared.qfLabel}>{item}</span>
        <span className={shared.qfCount}>{entries.filter((entry) => item === '전체' || entry.status === item).length}</span>
      </CommonButton>
    );
  })}
</div><div className={shared.filterBox}><form className={shared.filterRow1} onSubmit={(event) => { event.preventDefault(); setSearch(keyword.trim()); }}><label className="globalFilterField"><span>검색 범위</span><select aria-label="검색 범위" className={shared.selectSm}><option>전체 검색</option><option>관리번호</option><option>항목명</option><option>담당자</option></select></label><input className={shared.searchInput} value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder={`${title} 번호 / 항목명 / 담당자`}/><button className={shared.searchBtn} type="submit">조회</button></form><div className={shared.filterRow2}><label className="globalFilterField"><span>구분</span><select aria-label="구분" className={shared.selectSm} value={typeFilter} onChange={(event) => setTypeFilter(event.target.value)}><option value="">전체 구분</option>{types.map((type) => <option key={type}>{type}</option>)}</select></label><label className="globalFilterField"><span>상태</span><select aria-label="상태" className={shared.selectSm} value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="">전체 상태</option>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><DatePicker defaultValue="2026-08-01"/><span>~</span><DatePicker defaultValue="2026-08-26"/><span className={shared.rowSpacer}/><button type="button" className={shared.resetBtn} onClick={reset}>초기화</button></div></div><div className={shared.resultRow}><span className={shared.resultLabel}>총 {filtered.length}건</span><div className={shared.resultActions}><button type="button" className={shared.downloadBtn} onClick={download}>다운로드</button><select className={shared.pageSizeSelect}><option>20개씩</option><option>50개씩</option></select></div></div></div><div className={shared.gridWrap}><DataGrid columns={[{ label: '관리번호' }, { label: '항목명' }, { label: '구분' }, { label: '상태' }, { label: '담당자' }, { label: '등록일' }, { label: '수정일' }]} rows={rows} gridTemplate="125px minmax(220px,1.6fr) 100px 84px 85px 95px 125px" minWidth="940px" empty={filtered.length === 0} emptyText="검색 결과가 없습니다." emptySubtext="검색어나 필터 조건을 변경해 주세요." emptyActionLabel="필터 초기화" emptyActionClick={reset} showPagination pages={[{ label: '‹' }, { label: '1', active: true }, { label: '›' }]} rangeLabel={filtered.length ? `1–${filtered.length} / ${filtered.length}` : '0건'}/></div>
    {selected && <aside className={drawer.aside}><div className={drawer.head}><div className={drawer.headRow}><div className={drawer.headBody}><div className={drawer.eyebrow}>{title} 상세 · {selected.id}</div><div className={drawer.titleRow}><h2 className={drawer.title}>{selected.name}</h2><span className={drawer.badge} style={{ background: (STATUS_COLORS[selected.status] ?? STATUS_COLORS.중지).bg, color: (STATUS_COLORS[selected.status] ?? STATUS_COLORS.중지).fg }}>{selected.status}</span></div><div className={drawer.sub}>{selected.type} · 담당 {selected.owner}</div></div><button type="button" className={drawer.closeBtn} onClick={() => setSelectedId(null)}>×</button></div><div className={drawer.actionRow}>{statuses.map((status) => status !== selected.status && <button key={status} type="button" className={drawer.actionLink} onClick={() => updateStatus(status)}>{status} 처리</button>)}</div></div><div className={drawer.scroll}><div className={drawer.sectionTitle}>기본 정보</div><div className={drawer.fieldBox}><Info label="관리번호" value={selected.id}/><Info label="항목명" value={selected.name}/><Info label="구분" value={selected.type}/><Info label="상태" value={selected.status}/><Info label="담당자" value={selected.owner}/><Info label="등록일" value={selected.createdAt}/><Info label="최근 수정" value={selected.updatedAt}/></div><div className={drawer.sectionTitleLoose}>업무 내용</div><div className={drawer.bodyText}>{selected.note}</div><div className={drawer.sectionTitleLoose}>처리 이력</div>{['등록', '검토', '최근 상태 변경'].map((action, index) => <div key={action} className={drawer.timelineItem}><span className={drawer.timelineDot}/><div className={drawer.timelineBody}><div className={drawer.timelineRow}><strong className={drawer.timelineTitle}>{action}</strong><span className={drawer.timelineWhen}>2026-08-{String(24 + index).padStart(2, '0')}</span></div><div className={drawer.timelineDetail}>admin0{index + 1} · {title} 처리 기록</div></div></div>)}</div></aside>}
    {editorOpen && <div className={shared.dialogOverlay} onMouseDown={(event) => { if (event.target === event.currentTarget) setEditorOpen(false); }}><div className={shared.dialogBox}><h2 className={shared.dialogTitle}>{title} 등록</h2><p className={shared.dialogBody}>새 관리 항목의 기본 정보와 초기 상태를 입력합니다.</p><Field label="항목명 *"><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })}/></Field><Field label="구분"><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}>{types.map((type) => <option key={type}>{type}</option>)}</select></Field><Field label="초기 상태"><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></Field><Field label="관리 메모"><textarea value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })}/></Field><div className={shared.dialogActions}><button type="button" className={drawer.editCancel} onClick={() => setEditorOpen(false)}>취소</button><button type="button" className={drawer.editConfirm} onClick={save}>등록</button></div></div></div>}{toast && <div className={styles.toast}>{toast}</div>}</section>;
}

function AnalyticsPage({ title, subtitle, icon }: Required<Pick<Props, 'title' | 'subtitle' | 'icon'>>) {
  const base = seed(title); const [range, setRange] = useState('최근 30일'); const metrics = [{ label: '전체', value: (base * 17 % 85000 + 12400).toLocaleString(), change: '+8.4%' }, { label: '완료 / 성사', value: (base * 11 % 42000 + 8200).toLocaleString(), change: '+5.2%' }, { label: '평균 비율', value: `${(base % 28 + 61).toFixed(1)}%`, change: '+2.1%p' }, { label: '전환 가치', value: `${(base % 48 + 12).toLocaleString()}억`, change: '+11.7%' }]; const days = Array.from({ length: 12 }, (_, index) => ({ label: `8/${index + 15}`, value: 35 + (base + index * 17) % 64 }));
  const rows: GridRow[] = ['전체 회원', '신규 회원', '재구매 회원', 'VIP 회원', '휴면 복귀'].map((segment, index) => ({ id: segment, cells: [{ kind: 'text', text: segment, weight: 600 }, { kind: 'text', text: (base % 8000 + 1200 - index * 137).toLocaleString(), align: 'right', numeric: true }, { kind: 'text', text: `${(82 - index * 6.4).toFixed(1)}%`, align: 'right', numeric: true }, { kind: 'progress', pct: 82 - index * 9, label: `${82 - index * 9}%` }, { kind: 'text', text: `${index % 2 ? '-' : '+'}${(index * 1.7 + 2.4).toFixed(1)}%`, align: 'right', color: index % 2 ? '#dc2626' : '#047857' }] }));
  function download() { const csv = [['지표', '값', '이전 기간 대비'], ...metrics.map((metric) => [metric.label, metric.value, metric.change]), [], ['일자', '지수'], ...days.map((day) => [day.label, day.value])].map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = `${title}-${range}-리포트.csv`; a.click(); URL.revokeObjectURL(url); }
  return <section className={shared.page}><div className={shared.headTop}><div className={shared.headRow}><div><div className={styles.titleLine}><span className={styles.moduleIcon}>{icon}</span><h1 className={shared.title}>{title}</h1></div><p className={shared.subtitle}>{subtitle}</p></div><div className={shared.resultActions}><select className={shared.selectSm} value={range} onChange={(event) => setRange(event.target.value)}><option>최근 7일</option><option>최근 30일</option><option>최근 90일</option><option>올해</option></select><button type="button" className={shared.downloadBtn} onClick={download}>리포트 다운로드</button></div></div></div><div className={styles.analyticsBody}><div className={styles.metricGrid}>{metrics.map((metric) => <div key={metric.label} className={styles.metricCard}><span>{metric.label}</span><strong>{metric.value}</strong><em>{metric.change} · 이전 기간 대비</em></div>)}</div><div className={styles.chartCard}><div className={styles.cardHead}><div><h2>{range} 추이</h2><p>선택한 지표의 일별 변화</p></div><span className={styles.legend}><i/> 현재 기간</span></div><div className={styles.barChart}>{days.map((day) => <div key={day.label} className={styles.barCol}><span style={{ height: `${day.value}%` }}/><small>{day.label}</small></div>)}</div></div><div className={styles.tableCard}><div className={styles.cardHead}><div><h2>주요 세그먼트</h2><p>대상 구간별 성과와 구성비</p></div></div><DataGrid columns={[{ label: '구간' }, { label: '대상 수', align: 'right' }, { label: '완료율', align: 'right' }, { label: '구성비' }, { label: '증감', align: 'right' }]} rows={rows} gridTemplate="1.2fr 100px 90px 160px 90px" minWidth="700px"/></div></div></section>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className={drawer.fieldRow}><span className={drawer.fieldLabel}>{label}</span><strong className={drawer.fieldValue}>{value}</strong></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className={styles.field}><span>{label}</span>{children}</label>; }
