import { useMemo,useState } from 'react';
import { DataGrid } from '../../components/DataGrid';
import type { Cell,GridColumn,GridRow } from '../../components/DataGrid/types';
import { ExcelDownloadButton } from '../../components/common/ExcelDownloadButton';
import { DatePicker } from '../../components/forms/DatePicker';
import { POINT_LEDGER,fmtPoint } from './pointLedgerData';
import styles from './pointSubpages.module.css';
const ENTRIES=POINT_LEDGER.filter(e=>['관리자 차감','적립 취소'].includes(e.type));
const COLUMNS:GridColumn[]=[{label:'차감 번호'},{label:'차감일시'},{label:'회원'},{label:'차감 유형'},{label:'차감 포인트',align:'right'},{label:'차감 후 잔액',align:'right'},{label:'차감 사유'},{label:'처리자'}];
export function PointDeductedPage(){const [keyword,setKeyword]=useState('');const [search,setSearch]=useState('');const [type,setType]=useState('');const [start,setStart]=useState('');const [end,setEnd]=useState('');const rows=useMemo<GridRow[]>(()=>ENTRIES.filter(e=>!search||`${e.id} ${e.member} ${e.note}`.toLowerCase().includes(search.toLowerCase())).filter(e=>!type||e.type===type).filter(e=>(!start||e.at.slice(0,10)>=start)&&(!end||e.at.slice(0,10)<=end)).map(e=>({id:e.id,cells:[{kind:'text',text:e.id,weight:650,numeric:true},{kind:'text',text:e.at,color:'#71717a',numeric:true},{kind:'text',text:e.member,weight:650},{kind:'badge',text:e.type,bg:'#fff7ed',fg:'#c2410c'},{kind:'text',text:fmtPoint(Math.abs(e.delta)),color:'#dc2626',weight:700,align:'right',numeric:true},{kind:'text',text:fmtPoint(e.after),color:e.after<0?'#dc2626':'#18181b',weight:650,align:'right',numeric:true},{kind:'text',text:e.note,color:'#52525b'},{kind:'text',text:e.by,color:'#71717a'}] as Cell[]})),[search,type,start,end]);const reset=()=>{setKeyword('');setSearch('');setType('');setStart('');setEnd('')};return <div className={styles.page}><header className={styles.header}><div className={styles.title}>차감 내역</div><div className={styles.subtitle}>관리자 차감 및 적립 취소로 회수된 포인트 내역을 조회합니다.</div></header><section className={styles.summary}><div className={styles.summaryCard}><span>총 차감 건수</span><strong>{ENTRIES.length}건</strong></div><div className={styles.summaryCard}><span>총 차감 포인트</span><strong>{fmtPoint(ENTRIES.reduce((s,e)=>s+Math.abs(e.delta),0))}</strong></div><div className={styles.summaryCard}><span>잔액 확인 필요</span><strong>{ENTRIES.filter(e=>e.after<0).length}건</strong></div></section><section className={styles.filterBox}><form className={styles.filterRow} onSubmit={e=>{e.preventDefault();setSearch(keyword.trim())}}><label className={styles.field}><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="차감 번호 / 회원 / 사유"/></label><label className={styles.field}><span>차감 유형</span><select value={type} onChange={e=>setType(e.target.value)}><option value="">전체 차감 유형</option><option>관리자 차감</option><option>적립 취소</option></select></label><label className={styles.dateField}><span>차감일</span><div className={styles.dateRange}><DatePicker value={start} onChange={e=>setStart(e.target.value)}/><span>~</span><DatePicker value={end} onChange={e=>setEnd(e.target.value)}/></div></label><button className={styles.searchButton}>조회</button><button type="button" className={styles.resetButton} onClick={reset}>초기화</button></form></section><div className={styles.resultRow}><strong>총 {rows.length}건</strong><ExcelDownloadButton type="button" data-grid-download/></div><div className={styles.grid}><DataGrid columns={COLUMNS} rows={rows} gridTemplate="150px 130px 1fr 100px 110px 110px 1.3fr 90px" minWidth="1050px" empty={rows.length===0} emptyText="검색 조건에 해당하는 차감 내역이 없습니다."/></div></div>}
