import { useMemo,useState } from 'react';
import { DataGrid } from '../../components/DataGrid';
import type { Cell,GridColumn,GridRow } from '../../components/DataGrid/types';
import { ExcelDownloadButton } from '../../components/common/ExcelDownloadButton';
import { DatePicker } from '../../components/forms/DatePicker';
import { POINT_LEDGER,fmtPoint } from './pointLedgerData';
import styles from './pointSubpages.module.css';
const ENTRIES=POINT_LEDGER.filter(e=>e.type==='포인트 소멸');
const COLUMNS:GridColumn[]=[{label:'소멸 번호'},{label:'소멸일시'},{label:'회원'},{label:'소멸 포인트',align:'right'},{label:'소멸 전 잔액',align:'right'},{label:'소멸 후 잔액',align:'right'},{label:'소멸 사유'},{label:'처리 주체'}];
export function PointExpiredPage(){const [keyword,setKeyword]=useState('');const [search,setSearch]=useState('');const [start,setStart]=useState('');const [end,setEnd]=useState('');const rows=useMemo<GridRow[]>(()=>ENTRIES.filter(e=>!search||`${e.id} ${e.member} ${e.note}`.toLowerCase().includes(search.toLowerCase())).filter(e=>(!start||e.at.slice(0,10)>=start)&&(!end||e.at.slice(0,10)<=end)).map(e=>({id:e.id,cells:[{kind:'text',text:e.id,weight:650,numeric:true},{kind:'text',text:e.at,color:'#71717a',numeric:true},{kind:'text',text:e.member,weight:650},{kind:'text',text:fmtPoint(Math.abs(e.delta)),color:'#dc2626',weight:700,align:'right',numeric:true},{kind:'text',text:fmtPoint(e.before),align:'right',numeric:true},{kind:'text',text:fmtPoint(e.after),weight:650,align:'right',numeric:true},{kind:'text',text:e.note,color:'#52525b'},{kind:'badge',text:e.by,bg:'#f4f4f5',fg:'#52525b'}] as Cell[]})),[search,start,end]);const reset=()=>{setKeyword('');setSearch('');setStart('');setEnd('')};return <div className={styles.page}><header className={styles.header}><div className={styles.title}>소멸 내역</div><div className={styles.subtitle}>유효기간 만료로 소멸 처리된 포인트/적립금 내역을 조회합니다.</div></header><section className={styles.summary}><div className={styles.summaryCard}><span>총 소멸 건수</span><strong>{ENTRIES.length}건</strong></div><div className={styles.summaryCard}><span>총 소멸 포인트</span><strong>{fmtPoint(ENTRIES.reduce((s,e)=>s+Math.abs(e.delta),0))}</strong></div><div className={styles.summaryCard}><span>시스템 처리</span><strong>{ENTRIES.filter(e=>e.by==='SYSTEM').length}건</strong></div></section><section className={styles.filterBox}><form className={styles.filterRow} onSubmit={e=>{e.preventDefault();setSearch(keyword.trim())}}><label className={styles.field}><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="소멸 번호 / 회원 / 사유"/></label><label className={styles.dateField}><span>소멸일</span><div className={styles.dateRange}><DatePicker value={start} onChange={e=>setStart(e.target.value)}/><span>~</span><DatePicker value={end} onChange={e=>setEnd(e.target.value)}/></div></label><button className={styles.searchButton}>조회</button><button type="button" className={styles.resetButton} onClick={reset}>초기화</button></form></section><div className={styles.resultRow}><strong>총 {rows.length}건</strong><ExcelDownloadButton type="button" data-grid-download/></div><div className={styles.grid}><DataGrid columns={COLUMNS} rows={rows} gridTemplate="150px 130px 1fr 110px 110px 110px 1.4fr 100px" minWidth="1000px" empty={rows.length===0} emptyText="검색 조건에 해당하는 소멸 내역이 없습니다."/></div></div>}
