import { DatePicker } from '../../../components/forms/DatePicker';
import { useMemo, useState } from 'react';
import { DataGrid } from '../../../components/DataGrid';
import type { GridRow } from '../../../components/DataGrid/types';
import shared from '../shared.module.css';
import drawer from '../../ops/opsDrawerShared.module.css';
import base from '../sales/SalesActivity.module.css';
import styles from './PurchaseActivity.module.css';
import { CommonButton, showToast } from '../../../components/common';
import { ControlArea, DetailDrawer, FilterBox, GridArea, Metrics, PageHeading, ResultBar } from '../sales/SalesActivityShared';
import { downloadCsv, pages } from '../sales/salesActivityUtils';
import { PURCHASES, PURCHASE_STATUS_META, buyerById, formatWon, productById, sellerById, type PurchaseStatus } from './purchaseActivityData';

const QUICK:Array<'전체'|PurchaseStatus| '이슈 있음'>=['전체','결제완료','배송중','구매확정','취소요청','취소완료','분쟁중','이슈 있음'];

export function PurchaseHistoryPage(){
  const [purchases,setPurchases]=useState(PURCHASES); const [quick,setQuick]=useState<(typeof QUICK)[number]>('전체'); const [keyword,setKeyword]=useState(''); const [search,setSearch]=useState(''); const [payment,setPayment]=useState(''); const [buyerGrade,setBuyerGrade]=useState(''); const [selectedId,setSelectedId]=useState<string|null>(null);
  const filtered=useMemo(()=>purchases.filter((purchase)=>{if(quick==='이슈 있음'?!purchase.issue:quick!=='전체'&&purchase.status!==quick)return false;if(payment&&purchase.paymentMethod!==payment)return false;const buyer=buyerById(purchase.buyerId);if(buyerGrade&&buyer?.grade!==buyerGrade)return false;const product=productById(purchase.productId);const seller=sellerById(purchase.sellerId);return !search||`${purchase.id} ${purchase.tradeId} ${buyer?.nickname??''} ${seller?.nickname??''} ${product?.title??''}`.toLowerCase().includes(search.toLowerCase());}),[buyerGrade,payment,purchases,quick,search]);
  const selected=purchases.find((purchase)=>purchase.id===selectedId)??null; const buyer=selected?buyerById(selected.buyerId):null; const seller=selected?sellerById(selected.sellerId):null; const product=selected?productById(selected.productId):null;
  const total=purchases.reduce((sum,item)=>sum+item.amount+item.deliveryFee,0); const notify=(message:string)=>showToast({message,type:'success'});
  const update=(status:PurchaseStatus,issue='')=>{if(!selected)return;setPurchases((items)=>items.map((item)=>item.id===selected.id?{...item,status,issue,updatedAt:'2026-08-26 15:40',confirmedAt:status==='구매확정'?'2026-08-26 15:40':item.confirmedAt}:item));notify(`${selected.id} 구매 상태를 ${status}(으)로 변경했습니다.`);};
  const rows:GridRow[]=filtered.map((purchase)=>{const itemBuyer=buyerById(purchase.buyerId);const itemSeller=sellerById(purchase.sellerId);const itemProduct=productById(purchase.productId);return{id:purchase.id,onClick:()=>setSelectedId(purchase.id),cells:[{kind:'stack',title:purchase.id,subtitle:purchase.paidAt},{kind:'avatarText',title:itemBuyer?.nickname??purchase.buyerId,subtitle:`${itemBuyer?.name??'-'} · ${purchase.buyerId}`,avatarChar:(itemBuyer?.nickname??'구')[0],avatarBg:'#eef2ff',avatarFg:'#4338ca'},{kind:'stack',title:itemProduct?.title??purchase.productId,subtitle:`판매자 ${itemSeller?.nickname??purchase.sellerId}`},{kind:'text',text:formatWon(purchase.amount+purchase.deliveryFee),align:'right',numeric:true,weight:600},{kind:'text',text:purchase.paymentMethod},{kind:'badge',text:purchase.status,...PURCHASE_STATUS_META[purchase.status]},{kind:'stack',title:purchase.shipping,subtitle:purchase.issue||'이슈 없음'},{kind:'text',text:purchase.updatedAt,numeric:true},{kind:'link',text:'상세'}]};});
  return <div className={shared.page}>
    <PageHeading title="구매 내역" subtitle="C2C 구매자의 결제, 배송, 구매확정과 취소·분쟁 상태를 구매 건별로 조회합니다." action={<button type="button" className={shared.downloadBtn} onClick={()=>downloadCsv('C2C-구매내역.csv',['구매번호','구매자','상품','판매자','결제금액','결제수단','상태','결제일'],filtered.map((item)=>[item.id,buyerById(item.buyerId)?.nickname??item.buyerId,productById(item.productId)?.title??item.productId,sellerById(item.sellerId)?.nickname??item.sellerId,item.amount+item.deliveryFee,item.paymentMethod,item.status,item.paidAt]))}>다운로드</button>}/>
    <Metrics items={[{label:'총 구매 금액',value:formatWon(total),note:'조회 기간 결제액',tone:'up',dot:'#4f7bd9'},{label:'구매 확정',value:`${purchases.filter((p)=>p.status==='구매확정').length}건`,note:`확정률 ${((purchases.filter((p)=>p.status==='구매확정').length/purchases.length)*100).toFixed(1)}%`,dot:'#10b981'},{label:'취소 요청',value:`${purchases.filter((p)=>p.status==='취소요청').length}건`,note:'승인 대기 포함',tone:'down',dot:'#f59e0b'},{label:'분쟁 구매',value:`${purchases.filter((p)=>p.status==='분쟁중').length}건`,note:'운영자 확인 필요',tone:'down',dot:'#ef4444'}]}/>
    <ControlArea><div className={shared.quickFilters}>{QUICK.map((item) => {
      const active = quick === item;
      return (
        <CommonButton
          type="button"
          key={item}
          variant={active ? 'primary-light' : 'secondary'}
          size="md"
          className={`${shared.qfBtn} ${active ? base.quickActive : ''}`}
          onClick={() => setQuick(item)}
        >
          <span className={shared.qfLabel}>{item}</span>
          <span className={shared.qfCount}>{purchases.filter((purchase) => item === '전체' || (item === '이슈 있음' ? !purchase.issue : purchase.status === item)).length}</span>
        </CommonButton>
      );
    })}</div><FilterBox><form className={shared.filterRow1} onSubmit={(e)=>{e.preventDefault();setSearch(keyword.trim());}}><label className="globalFilterField"><span>검색 범위</span><select aria-label="검색 범위" className={shared.selectSm}><option>통합 검색</option><option>구매번호</option><option>구매자</option><option>상품명</option><option>판매자</option></select></label><input className={shared.searchInput} value={keyword} onChange={(e)=>setKeyword(e.target.value)} placeholder="구매번호 / 구매자 / 상품 / 판매자"/><button className={shared.searchBtn}>조회</button></form><div className={shared.filterRow2}><label className="globalFilterField"><span>결제수단</span><select aria-label="결제수단" className={shared.selectSm} value={payment} onChange={(e)=>setPayment(e.target.value)}><option value="">전체 결제수단</option><option>안전결제</option><option>카드</option><option>간편결제</option></select></label><label className="globalFilterField"><span>구매자 등급</span><select aria-label="구매자 등급" className={shared.selectSm} value={buyerGrade} onChange={(e)=>setBuyerGrade(e.target.value)}><option value="">전체 구매자 등급</option><option>일반</option><option>우수</option><option>VIP</option></select></label><span>결제일</span><DatePicker className={shared.selectSm} defaultValue="2026-08-01"/><span>~</span><DatePicker className={shared.selectSm} defaultValue="2026-08-26"/><span className={shared.rowSpacer}/><button type="button" className={shared.resetBtn} onClick={()=>{setKeyword('');setSearch('');setPayment('');setBuyerGrade('');}}>초기화</button></div></FilterBox></ControlArea>
    <GridArea><ResultBar count={filtered.length} unit="건"><select className={shared.pageSizeSelect}><option>20개씩</option><option>50개씩</option></select></ResultBar><DataGrid columns={[{label:'구매번호 / 결제일'},{label:'구매자'},{label:'상품 / 판매자'},{label:'결제금액',align:'right'},{label:'결제수단'},{label:'구매 상태'},{label:'배송 / 이슈'},{label:'최근 변경'},{label:'관리'}]} rows={rows} gridTemplate="132px 236px minmax(190px,1.35fr) 95px 78px 82px minmax(140px,1fr) 125px 55px" minWidth="1175px" empty={!filtered.length} emptyText="조건에 맞는 구매 내역이 없습니다." showPagination pages={pages} rangeLabel={filtered.length?`1–${filtered.length} / ${filtered.length}`:'0건'}/></GridArea>
    {selected&&buyer&&seller&&product&&<DetailDrawer eyebrow={`구매 상세 · ${selected.id}`} title={product.title} status={selected.status} statusMeta={PURCHASE_STATUS_META[selected.status]} subtitle={`${buyer.nickname} 구매 · ${seller.nickname} 판매`} onClose={()=>setSelectedId(null)} actions={<>{selected.status==='배송중'&&<button type="button" className={drawer.primaryBtn} onClick={()=>update('구매확정')}>구매 확정 처리</button>}<span className={drawer.spacer}/>{!['취소완료','구매확정'].includes(selected.status)&&<button type="button" className={drawer.dangerBtn} onClick={()=>update('분쟁중','운영자 분쟁 전환')}>분쟁 전환</button>}</>} stats={[{label:'상품 금액',value:formatWon(selected.amount)},{label:'배송비',value:formatWon(selected.deliveryFee)},{label:'총 결제액',value:formatWon(selected.amount+selected.deliveryFee)}]} fields={[{label:'거래번호',value:selected.tradeId},{label:'결제수단',value:selected.paymentMethod},{label:'결제일',value:selected.paidAt},{label:'배송 상태',value:selected.shipping},{label:'구매 확정일',value:selected.confirmedAt},{label:'최근 변경',value:selected.updatedAt}]}><div className={drawer.sectionTitleLoose}>구매자 정보</div><div className={styles.buyerSummary}><span className={styles.buyerAvatar}>{buyer.nickname[0]}</span><span className={styles.buyerBody}><strong>{buyer.nickname} · {buyer.grade}</strong><span>{buyer.name} · 구매 {buyer.purchaseCount}건 · 취소 {buyer.cancelCount}건</span></span><span className={styles.buyerScore}>{buyer.mannerScore}점</span></div><div className={drawer.sectionTitleLoose}>진행 이슈</div><div className={selected.issue?base.warningBox:drawer.bodyText}>{selected.issue||'현재 등록된 구매 이슈가 없습니다.'}</div></DetailDrawer>}
  </div>;
}
