import { DatePicker } from '../../../components/forms/DatePicker';
import { useMemo, useState } from 'react';
import { DataGrid } from '../../../components/DataGrid';
import type { GridRow } from '../../../components/DataGrid/types';
import shared from '../../ops/opsShared.module.css';
import drawer from '../../ops/opsDrawerShared.module.css';
import base from '../sales/SalesActivity.module.css';
import { ControlArea, DetailDrawer, FilterBox, GridArea, PageHeading, ResultBar } from '../sales/SalesActivityShared';
import { downloadCsv, pages } from '../sales/salesActivityUtils';
import { PURCHASE_ACTIVITY_LOGS, buyerById, purchaseById, type PurchaseActivityLog } from './purchaseActivityData';

const CATEGORY_META:Record<PurchaseActivityLog['category'],{bg:string;fg:string}>={구매:{bg:'#eff6ff',fg:'#1d4ed8'},결제:{bg:'#ecfdf5',fg:'#047857'},배송:{bg:'#f5f3ff',fg:'#6d28d9'},취소:{bg:'#fff7ed',fg:'#c2410c'},분쟁:{bg:'#fef2f2',fg:'#dc2626'},환불:{bg:'#ecfeff',fg:'#0e7490'}};

export function PurchaseActivityHistoryPage(){
  const [keyword,setKeyword]=useState('');const[search,setSearch]=useState('');const[category,setCategory]=useState('');const[actor,setActor]=useState('');const[selectedId,setSelectedId]=useState<string|null>(null);
  const filtered=useMemo(()=>PURCHASE_ACTIVITY_LOGS.filter((item)=>(!category||item.category===category)&&(!actor||(actor==='SYSTEM'?item.actor==='SYSTEM':item.actor!=='SYSTEM'))&&(!search||`${item.id} ${item.action} ${item.target} ${item.reason} ${item.actor} ${buyerById(item.buyerId)?.nickname??''}`.toLowerCase().includes(search.toLowerCase()))),[actor,category,search]);
  const selected=PURCHASE_ACTIVITY_LOGS.find((item)=>item.id===selectedId)??null;const buyer=selected?buyerById(selected.buyerId):null;const purchase=selected?purchaseById(selected.target):null;
  const rows:GridRow[]=filtered.map((item)=>{const itemBuyer=buyerById(item.buyerId);return{id:item.id,onClick:()=>setSelectedId(item.id),cells:[{kind:'text',text:item.occurredAt,numeric:true},{kind:'pillText',text:item.category,...CATEGORY_META[item.category]},{kind:'stack',title:item.action,subtitle:item.target},{kind:'avatarText',title:itemBuyer?.nickname??item.buyerId,subtitle:item.buyerId,avatarChar:(itemBuyer?.nickname??'구')[0],avatarBg:'#eef2ff',avatarFg:'#4338ca'},{kind:'text',text:item.before,color:'#71717a'},{kind:'text',text:`→ ${item.after}`,weight:600},{kind:'stack',title:item.actor,subtitle:item.ip},{kind:'text',text:item.reason},{kind:'link',text:'상세'}]};});
  return <section className={shared.page}>
    <PageHeading title="구매 활동 이력" subtitle="구매, 결제, 배송, 취소, 분쟁과 환불 과정의 변경 내역을 처리 주체와 변경 전후 값으로 감사 조회합니다." action={<button type="button" className={shared.downloadBtn} onClick={()=>downloadCsv('구매-활동-이력.csv',['발생일시','구분','행위','대상','구매자','변경 전','변경 후','처리자','사유','IP'],filtered.map((item)=>[item.occurredAt,item.category,item.action,item.target,item.buyerId,item.before,item.after,item.actor,item.reason,item.ip]))}>감사 로그 다운로드</button>}/>
    <ControlArea><FilterBox><form className={shared.filterRow1} onSubmit={(e)=>{e.preventDefault();setSearch(keyword.trim());}}><label className="globalFilterField"><span>검색 범위</span><select aria-label="검색 범위" className={shared.selectSm}><option>통합 검색</option><option>로그 ID</option><option>구매번호</option><option>구매자</option><option>처리자</option></select></label><input className={shared.searchInput} value={keyword} onChange={(e)=>setKeyword(e.target.value)} placeholder="로그 ID / 구매번호 / 구매자 / 처리자 / 사유"/><button className={shared.searchBtn}>조회</button></form><div className={shared.filterRow2}><label className="globalFilterField"><span>업무 구분</span><select aria-label="업무 구분" className={shared.selectSm} value={category} onChange={(e)=>setCategory(e.target.value)}><option value="">전체 업무 구분</option><option>구매</option><option>결제</option><option>배송</option><option>취소</option><option>분쟁</option><option>환불</option></select></label><label className="globalFilterField"><span>처리 주체</span><select aria-label="처리 주체" className={shared.selectSm} value={actor} onChange={(e)=>setActor(e.target.value)}><option value="">전체 처리 주체</option><option>구매자/판매자</option><option>관리자</option><option value="SYSTEM">SYSTEM</option></select></label><span>발생일</span><DatePicker mode="datetime-local" className={shared.selectSm} defaultValue="2026-08-20T00:00"/><span>~</span><DatePicker mode="datetime-local" className={shared.selectSm} defaultValue="2026-08-26T23:59"/><span className={shared.rowSpacer}/><button type="button" className={shared.resetBtn} onClick={()=>{setKeyword('');setSearch('');setCategory('');setActor('');}}>초기화</button></div></FilterBox></ControlArea>
    <GridArea><ResultBar count={filtered.length} unit="건"><span className={base.rangeText}>최근 발생순</span><select className={shared.pageSizeSelect}><option>50개씩</option><option>100개씩</option></select></ResultBar><DataGrid columns={[{label:'발생일시'},{label:'구분'},{label:'행위 / 대상'},{label:'구매자'},{label:'변경 전'},{label:'변경 후'},{label:'처리자 / IP'},{label:'변경 사유'},{label:'관리'}]} rows={rows} gridTemplate="128px 58px minmax(155px,1fr) 198px 68px 88px 83px minmax(160px,1.2fr) 55px" minWidth="1060px" empty={!filtered.length} emptyText="조건에 맞는 구매 활동 이력이 없습니다." showPagination pages={pages} rangeLabel={filtered.length?`1–${filtered.length} / ${filtered.length}`:'0건'}/></GridArea>
    {selected&&buyer&&<DetailDrawer eyebrow={`구매 활동 로그 · ${selected.id}`} title={selected.action} status={selected.category} statusMeta={CATEGORY_META[selected.category]} subtitle={`${selected.target} · ${selected.occurredAt}`} onClose={()=>setSelectedId(null)} stats={[{label:'구매자',value:buyer.nickname},{label:'처리자',value:selected.actor},{label:'업무 구분',value:selected.category}]} fields={[{label:'로그 ID',value:selected.id},{label:'구매자 ID',value:selected.buyerId},{label:'구매번호',value:selected.target},{label:'거래번호',value:purchase?.tradeId??'-'},{label:'발생 일시',value:selected.occurredAt},{label:'접속 IP',value:selected.ip}]}><div className={drawer.sectionTitleLoose}>변경 내용</div><div className={base.compare}><b>{selected.before}</b><span className={base.arrow}>→</span><span className={base.after}>{selected.after}</span></div><div className={drawer.sectionTitleLoose}>변경 사유</div><div className={base.warningBox}>{selected.reason}</div><div className={drawer.sectionTitleLoose}>감사 흐름</div><div className={base.timeline}><div className={base.timelineItem}><strong>요청 또는 이벤트 발생</strong><p>{selected.reason}</p><time>{selected.occurredAt}</time></div><div className={base.timelineItem}><strong>구매 상태 반영</strong><p>{selected.before} → {selected.after}</p><time>{selected.occurredAt}</time></div><div className={base.timelineItem}><strong>감사 로그 저장</strong><p>{selected.actor} · {selected.ip}</p><time>{selected.occurredAt}</time></div></div></DetailDrawer>}
  </section>;
}
