import { DatePicker } from '../../../components/forms/DatePicker';
import { useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { DataGrid } from '../../../components/DataGrid';
import type { GridRow } from '../../../components/DataGrid/types';
import shared from '../../ops/opsShared.module.css';
import drawer from '../../ops/opsDrawerShared.module.css';
import base from '../sales/SalesActivity.module.css';
import styles from './PurchaseActivity.module.css';
import { ControlArea, DetailDrawer, FilterBox, GridArea, Metrics, PageHeading, ResultBar } from '../sales/SalesActivityShared';
import { downloadCsv, pages } from '../sales/salesActivityUtils';
import { DISPUTE_STATUS_META, PURCHASE_DISPUTES, buyerById, formatWon, productById, purchaseById, sellerById, type DisputeStatus } from './purchaseActivityData';

const QUICK=['전체','접수','검토중','증빙대기','운영판단','조정완료','SLA 임박'] as const satisfies readonly ('전체'|DisputeStatus|'SLA 임박')[];
type QuickFilter=(typeof QUICK)[number];
const QUERY_TO_QUICK:Record<string,QuickFilter>={received:'접수',review:'검토중',evidence:'증빙대기',decision:'운영판단',completed:'조정완료',sla:'SLA 임박'};
const QUICK_TO_QUERY:Partial<Record<QuickFilter,string>>={접수:'received',검토중:'review',증빙대기:'evidence',운영판단:'decision',조정완료:'completed','SLA 임박':'sla'};
const PRIORITY_META={일반:{bg:'#f4f4f5',fg:'#52525b'},주의:{bg:'#fff7ed',fg:'#c2410c'},긴급:{bg:'#fef2f2',fg:'#dc2626'}};

export function PurchaseDisputesPage(){
  const [searchParams,setSearchParams]=useSearchParams(); const quick=QUERY_TO_QUICK[searchParams.get('status')??'']??'전체';
  const [disputes,setDisputes]=useState(PURCHASE_DISPUTES); const [keyword,setKeyword]=useState(''); const [search,setSearch]=useState(''); const [category,setCategory]=useState(''); const [assignee,setAssignee]=useState(''); const [selectedId,setSelectedId]=useState<string|null>(null); const [decision,setDecision]=useState(''); const [toast,setToast]=useState('');
  const isSlaRisk=(dueAt:string)=>dueAt<='2026-08-27 18:00';
  const filtered=useMemo(()=>disputes.filter((item)=>(quick==='SLA 임박'?item.status!=='조정완료'&&isSlaRisk(item.dueAt):quick==='전체'||item.status===quick)&&(!category||item.category===category)&&(!assignee||(assignee==='미배정'?item.assignee==='미배정':item.assignee!=='미배정'))&&(!search||(()=>{const purchase=purchaseById(item.purchaseId);return `${item.id} ${item.purchaseId} ${buyerById(purchase?.buyerId??'')?.nickname??''} ${sellerById(purchase?.sellerId??'')?.nickname??''} ${item.buyerClaim} ${item.sellerClaim}`.toLowerCase().includes(search.toLowerCase());})())),[assignee,category,disputes,quick,search]);
  const selected=disputes.find((item)=>item.id===selectedId)??null; const purchase=selected?purchaseById(selected.purchaseId):null; const buyer=purchase?buyerById(purchase.buyerId):null; const seller=purchase?sellerById(purchase.sellerId):null; const product=purchase?productById(purchase.productId):null;
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),2300);};
  const setQuickFilter=(nextQuick:QuickFilter)=>{const next=new URLSearchParams(searchParams);const status=QUICK_TO_QUERY[nextQuick];if(status)next.set('status',status);else next.delete('status');setSearchParams(next,{replace:true});};
  const resetFilters=()=>{setKeyword('');setSearch('');setCategory('');setAssignee('');setQuickFilter('전체');};
  const update=(status:DisputeStatus,extra?:{assignee?:string;resolution?:string})=>{if(!selected)return;setDisputes((items)=>items.map((item)=>item.id===selected.id?{...item,status,assignee:extra?.assignee??item.assignee,resolution:extra?.resolution??item.resolution}:item));notify(`${selected.id} 분쟁을 ${status}(으)로 처리했습니다.`);};
  const resolve=()=>{if(!decision.trim())return notify('운영 판단 내용을 입력해 주세요.');update('조정완료',{assignee:selected?.assignee==='미배정'?'admin01':selected?.assignee,resolution:decision.trim()});setDecision('');};
  const rows:GridRow[]=filtered.map((item)=>{const p=purchaseById(item.purchaseId);const b=buyerById(p?.buyerId??'');const s=sellerById(p?.sellerId??'');const pr=productById(p?.productId??'');return{id:item.id,onClick:()=>setSelectedId(item.id),cells:[{kind:'stack',title:item.id,subtitle:item.receivedAt},{kind:'pillText',text:item.priority,...PRIORITY_META[item.priority]},{kind:'stack',title:item.category,subtitle:pr?.title??item.purchaseId},{kind:'stack',title:b?.nickname??'-',subtitle:`판매자 ${s?.nickname??'-'}`},{kind:'text',text:`${item.buyerEvidence} / ${item.sellerEvidence}`,align:'right',numeric:true},{kind:'badge',text:item.status,...DISPUTE_STATUS_META[item.status]},{kind:'badgeSub',text:isSlaRisk(item.dueAt)&&item.status!=='조정완료'?'임박':'정상',bg:isSlaRisk(item.dueAt)&&item.status!=='조정완료'?'#fef2f2':'#ecfdf5',fg:isSlaRisk(item.dueAt)&&item.status!=='조정완료'?'#dc2626':'#047857',subText:item.dueAt},{kind:'text',text:item.assignee,color:item.assignee==='미배정'?'#dc2626':undefined},{kind:'link',text:'검토'}]};});
  return <section className={shared.page}>
    <PageHeading title="분쟁 처리" subtitle="C2C 거래의 구매자·판매자 주장과 증빙을 한곳에서 비교하고 SLA 내 운영 판단과 조정 결과를 관리합니다." action={<button type="button" className={shared.downloadBtn} onClick={()=>downloadCsv('C2C-분쟁처리.csv',['분쟁번호','구매번호','유형','우선순위','상태','구매자 증빙','판매자 증빙','담당자','처리기한'],filtered.map((item)=>[item.id,item.purchaseId,item.category,item.priority,item.status,item.buyerEvidence,item.sellerEvidence,item.assignee,item.dueAt]))}>분쟁 리포트</button>}/>
    <Metrics items={[{label:'처리 대기',value:`${disputes.filter((d)=>d.status==='접수').length}건`,note:'담당자 배정 필요',tone:'down',dot:'#f59e0b'},{label:'SLA 임박',value:`${disputes.filter((d)=>d.status!=='조정완료'&&isSlaRisk(d.dueAt)).length}건`,note:'오늘 18시 이전',tone:'down',dot:'#ef4444'},{label:'증빙 대기',value:`${disputes.filter((d)=>d.status==='증빙대기').length}건`,note:'당사자 자료 제출 필요',dot:'#8b5cf6'},{label:'조정 완료율',value:`${((disputes.filter((d)=>d.status==='조정완료').length/disputes.length)*100).toFixed(1)}%`,note:'이번 달 누적',tone:'up',dot:'#10b981'}]}/>
    <ControlArea><div className={shared.quickFilters}>{QUICK.map((item)=><button type="button" key={item} className={`${shared.qfBtn} ${quick===item?base.quickActive:''}`} onClick={()=>setQuickFilter(item)}><span className={shared.qfLabel}>{item}</span><span className={shared.qfCount}>{disputes.filter((dispute)=>item==='전체'||(item==='SLA 임박'?dispute.status!=='조정완료'&&isSlaRisk(dispute.dueAt):dispute.status===item)).length}</span></button>)}</div><FilterBox><form className={shared.filterRow1} onSubmit={(e)=>{e.preventDefault();setSearch(keyword.trim());}}><label className="globalFilterField"><span>검색 범위</span><select aria-label="검색 범위" className={shared.selectSm}><option>통합 검색</option><option>분쟁번호</option><option>구매번호</option><option>구매자</option><option>판매자</option></select></label><input className={shared.searchInput} value={keyword} onChange={(e)=>setKeyword(e.target.value)} placeholder="분쟁번호 / 구매번호 / 구매자 / 판매자 / 주장"/><button className={shared.searchBtn}>조회</button></form><div className={shared.filterRow2}><label className="globalFilterField"><span>분쟁 유형</span><select aria-label="분쟁 유형" className={shared.selectSm} value={category} onChange={(e)=>setCategory(e.target.value)}><option value="">전체 분쟁 유형</option><option>상품 상태</option><option>미배송</option><option>가품 의심</option><option>구성품 누락</option><option>거래 취소</option></select></label><label className="globalFilterField"><span>담당 상태</span><select aria-label="담당 상태" className={shared.selectSm} value={assignee} onChange={(e)=>setAssignee(e.target.value)}><option value="">전체 담당 상태</option><option>미배정</option><option value="배정">담당자 배정</option></select></label><span>접수일</span><DatePicker className={shared.selectSm} defaultValue="2026-08-01"/><span>~</span><DatePicker className={shared.selectSm} defaultValue="2026-08-27"/><span className={shared.rowSpacer}/><button type="button" className={shared.resetBtn} onClick={resetFilters}>초기화</button></div></FilterBox></ControlArea>
    <GridArea><ResultBar count={filtered.length} unit="건"/><DataGrid columns={[{label:'분쟁번호 / 접수일'},{label:'우선순위'},{label:'유형 / 상품'},{label:'구매자 / 판매자'},{label:'증빙(구매/판매)',align:'right'},{label:'진행 상태'},{label:'SLA / 기한'},{label:'담당자'},{label:'관리'}]} rows={rows} gridTemplate="145px 65px minmax(165px,1.2fr) 130px 98px 82px 105px 70px 55px" minWidth="1060px" empty={!filtered.length} emptyText="조건에 맞는 분쟁이 없습니다." emptyActionLabel="필터 초기화" emptyActionClick={resetFilters} showPagination pages={pages} rangeLabel={filtered.length?`1–${filtered.length} / ${filtered.length}`:'0건'}/></GridArea>
    {selected&&purchase&&buyer&&seller&&product&&<DetailDrawer eyebrow={`분쟁 상세 · ${selected.id}`} title={product.title} status={selected.status} statusMeta={DISPUTE_STATUS_META[selected.status]} subtitle={`${selected.category} · ${selected.priority} · ${selected.receivedAt}`} onClose={()=>{setSelectedId(null);setDecision('');}} actions={<>{selected.assignee==='미배정'&&<button type="button" className={drawer.primaryBtn} onClick={()=>update('검토중',{assignee:'admin01'})}>나에게 배정</button>}{selected.status==='검토중'&&<button type="button" className={drawer.actionLink} onClick={()=>update('증빙대기')}>추가 증빙 요청</button>}<span className={drawer.spacer}/>{selected.status==='증빙대기'&&<button type="button" className={drawer.actionLink} onClick={()=>update('운영판단')}>판단 단계 전환</button>}</>} stats={[{label:'거래 금액',value:formatWon(purchase.amount)},{label:'구매자 증빙',value:`${selected.buyerEvidence}개`},{label:'판매자 증빙',value:`${selected.sellerEvidence}개`}]} fields={[{label:'구매번호',value:selected.purchaseId},{label:'구매자',value:`${buyer.nickname} (${buyer.id})`},{label:'판매자',value:`${seller.nickname} (${seller.id})`},{label:'담당자',value:selected.assignee},{label:'처리 기한',value:selected.dueAt},{label:'우선순위',value:selected.priority}]}><div className={drawer.sectionTitleLoose}>당사자 주장 비교</div><div className={styles.claimGrid}><div className={styles.claimBox}><div className={styles.claimHead}><strong>구매자 주장</strong><span>증빙 {selected.buyerEvidence}개</span></div><p>{selected.buyerClaim}</p></div><div className={styles.claimBox}><div className={styles.claimHead}><strong>판매자 주장</strong><span>증빙 {selected.sellerEvidence}개</span></div><p>{selected.sellerClaim}</p></div></div><div className={drawer.sectionTitleLoose}>증빙 자료</div><div className={styles.evidenceBox}><div className={styles.evidenceRow}><span>구매자 사진·대화 캡처</span><strong>{selected.buyerEvidence}개</strong></div><div className={styles.evidenceRow}><span>판매자 출고 사진·구매 증빙</span><strong>{selected.sellerEvidence}개</strong></div></div><div className={drawer.sectionTitleLoose}>운영 판단</div>{selected.status==='조정완료'?<div className={drawer.bodyText}>{selected.resolution}</div>:<div className={styles.decisionBox}><textarea value={decision} onChange={(e)=>setDecision(e.target.value)} placeholder="양측 주장과 증빙을 근거로 조정 판단을 입력하세요."/><div className={styles.decisionActions}><button type="button" className={drawer.editCancel} onClick={()=>setDecision('')}>초기화</button><button type="button" className={drawer.editConfirm} onClick={resolve}>판단 확정</button></div></div>}</DetailDrawer>}
    {toast&&<div className={base.toast}>{toast}</div>}
  </section>;
}
