import { DatePicker } from '../../../components/forms/DatePicker';
import { useMemo, useState } from 'react';
import { DataGrid } from '../../../components/DataGrid';
import type { GridRow } from '../../../components/DataGrid/types';
import shared from '../../ops/opsShared.module.css';
import drawer from '../../ops/opsDrawerShared.module.css';
import base from '../sales/SalesActivity.module.css';
import styles from './PurchaseActivity.module.css';
import { ControlArea, DetailDrawer, FilterBox, GridArea, Metrics, PageHeading, ResultBar } from '../sales/SalesActivityShared';
import { downloadCsv, pages } from '../sales/salesActivityUtils';
import { CANCEL_STATUS_META, PURCHASE_CANCELS, buyerById, formatWon, productById, purchaseById, sellerById, type CancelStatus, type PurchaseCancel } from './purchaseActivityData';

const QUICK:Array<'전체'|CancelStatus>=['전체','승인대기','구매자 확인','판매자 확인','환불처리중','취소완료','반려'];

export function PurchaseCancelPage(){
  const [cancels,setCancels]=useState(PURCHASE_CANCELS); const [quick,setQuick]=useState<(typeof QUICK)[number]>('전체'); const [keyword,setKeyword]=useState(''); const [search,setSearch]=useState(''); const [reason,setReason]=useState(''); const [responsibility,setResponsibility]=useState(''); const [selectedId,setSelectedId]=useState<string|null>(null); const [toast,setToast]=useState('');
  const filtered=useMemo(()=>cancels.filter((item)=>(quick==='전체'||item.status===quick)&&(!reason||item.reasonType===reason)&&(!responsibility||item.responsibility===responsibility)&&(!search||(()=>{const purchase=purchaseById(item.purchaseId);return `${item.id} ${item.purchaseId} ${buyerById(purchase?.buyerId??'')?.nickname??''} ${productById(purchase?.productId??'')?.title??''} ${item.reason}`.toLowerCase().includes(search.toLowerCase());})())),[cancels,quick,reason,responsibility,search]);
  const selected=cancels.find((item)=>item.id===selectedId)??null; const purchase=selected?purchaseById(selected.purchaseId):null; const buyer=purchase?buyerById(purchase.buyerId):null; const seller=purchase?sellerById(purchase.sellerId):null; const product=purchase?productById(purchase.productId):null;
  const pendingAmount=cancels.filter((item)=>!['취소완료','반려'].includes(item.status)).reduce((sum,item)=>sum+item.refundAmount,0); const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),2200);};
  const update=(status:CancelStatus,responsibilityValue?:PurchaseCancel['responsibility'])=>{if(!selected)return;setCancels((items)=>items.map((item)=>item.id===selected.id?{...item,status,responsibility:responsibilityValue??item.responsibility,assignee:item.assignee==='미배정'?'admin01':item.assignee,completedAt:['취소완료','반려'].includes(status)?'2026-08-26 15:40':item.completedAt}:item));notify(`${selected.id} 취소 요청을 ${status}(으)로 처리했습니다.`);};
  const rows:GridRow[]=filtered.map((item)=>{const p=purchaseById(item.purchaseId);const b=buyerById(p?.buyerId??'');const s=sellerById(p?.sellerId??'');const pr=productById(p?.productId??'');return{id:item.id,onClick:()=>setSelectedId(item.id),cells:[{kind:'stack',title:item.id,subtitle:item.requestedAt},{kind:'stack',title:b?.nickname??'-',subtitle:`판매자 ${s?.nickname??'-'}`},{kind:'stack',title:pr?.title??item.purchaseId,subtitle:item.purchaseId},{kind:'pillText',text:item.reasonType,bg:'#fff7ed',fg:'#c2410c'},{kind:'text',text:item.responsibility,color:item.responsibility==='검토중'?'#dc2626':undefined},{kind:'text',text:formatWon(item.refundAmount),align:'right',numeric:true,weight:600},{kind:'badge',text:item.status,...CANCEL_STATUS_META[item.status]},{kind:'text',text:item.assignee},{kind:'link',text:'검토'}]};});
  return <section className={shared.page}>
    <PageHeading title="구매 취소" subtitle="구매 취소 요청의 사유와 귀책을 확인하고 승인, 반려 및 환불 진행 상태를 관리합니다." action={<button type="button" className={shared.downloadBtn} onClick={()=>downloadCsv('C2C-구매취소.csv',['취소번호','구매번호','사유','귀책','환불액','상태','담당자'],filtered.map((item)=>[item.id,item.purchaseId,item.reasonType,item.responsibility,item.refundAmount,item.status,item.assignee]))}>다운로드</button>}/>
    <Metrics items={[{label:'승인 대기',value:`${cancels.filter((c)=>c.status==='승인대기').length}건`,note:'신규 요청 우선 처리',tone:'down',dot:'#f59e0b'},{label:'확인 진행중',value:`${cancels.filter((c)=>['구매자 확인','판매자 확인'].includes(c.status)).length}건`,note:'당사자 응답 확인',dot:'#4f7bd9'},{label:'환불 예정액',value:formatWon(pendingAmount),note:'완료·반려 제외',dot:'#8b5cf6'},{label:'처리 완료율',value:`${((cancels.filter((c)=>['취소완료','반려'].includes(c.status)).length/cancels.length)*100).toFixed(1)}%`,note:'이번 달 누적',tone:'up',dot:'#10b981'}]}/>
    <ControlArea><div className={shared.quickFilters}>{QUICK.map((item)=><button type="button" key={item} className={`${shared.qfBtn} ${quick===item?base.quickActive:''}`} onClick={()=>setQuick(item)}><span className={shared.qfLabel}>{item}</span><span className={shared.qfCount}>{cancels.filter((cancel)=>item==='전체'||cancel.status===item).length}</span></button>)}</div><FilterBox><form className={shared.filterRow1} onSubmit={(e)=>{e.preventDefault();setSearch(keyword.trim());}}><label className="globalFilterField"><span>검색 범위</span><select aria-label="검색 범위" className={shared.selectSm}><option>통합 검색</option><option>취소번호</option><option>구매번호</option><option>구매자</option><option>상품명</option></select></label><input className={shared.searchInput} value={keyword} onChange={(e)=>setKeyword(e.target.value)} placeholder="취소번호 / 구매번호 / 구매자 / 상품"/><button className={shared.searchBtn}>조회</button></form><div className={shared.filterRow2}><label className="globalFilterField"><span>취소 사유</span><select aria-label="취소 사유" className={shared.selectSm} value={reason} onChange={(e)=>setReason(e.target.value)}><option value="">전체 취소 사유</option><option>단순 변심</option><option>판매자 미발송</option><option>상품 정보 상이</option><option>중복 결제</option><option>운영자 취소</option></select></label><label className="globalFilterField"><span>귀책</span><select aria-label="귀책" className={shared.selectSm} value={responsibility} onChange={(e)=>setResponsibility(e.target.value)}><option value="">전체 귀책</option><option>구매자</option><option>판매자</option><option>플랫폼</option><option>검토중</option></select></label><span>요청일</span><DatePicker className={shared.selectSm} defaultValue="2026-08-01"/><span>~</span><DatePicker className={shared.selectSm} defaultValue="2026-08-26"/><span className={shared.rowSpacer}/><button type="button" className={shared.resetBtn} onClick={()=>{setKeyword('');setSearch('');setReason('');setResponsibility('');}}>초기화</button></div></FilterBox></ControlArea>
    <GridArea><ResultBar count={filtered.length} unit="건"/><DataGrid columns={[{label:'취소번호 / 요청일'},{label:'구매자 / 판매자'},{label:'상품 / 구매번호'},{label:'취소 사유'},{label:'귀책'},{label:'환불액',align:'right'},{label:'처리 상태'},{label:'담당자'},{label:'관리'}]} rows={rows} gridTemplate="127px 111px minmax(190px,1.35fr) 95px 48px 95px 88px 70px 55px" minWidth="990px" empty={!filtered.length} emptyText="조건에 맞는 구매 취소 요청이 없습니다." showPagination pages={pages} rangeLabel={filtered.length?`1–${filtered.length} / ${filtered.length}`:'0건'}/></GridArea>
    {selected&&purchase&&buyer&&seller&&product&&<DetailDrawer eyebrow={`구매 취소 검토 · ${selected.id}`} title={product.title} status={selected.status} statusMeta={CANCEL_STATUS_META[selected.status]} subtitle={`${buyer.nickname} 요청 · ${selected.requestedAt}`} onClose={()=>setSelectedId(null)} actions={<>{!['취소완료','반려'].includes(selected.status)&&<><button type="button" className={drawer.primaryBtn} onClick={()=>update('환불처리중',selected.responsibility==='검토중'?'판매자':selected.responsibility)}>취소 승인</button><button type="button" className={drawer.dangerBtn} onClick={()=>update('반려')}>요청 반려</button></>}<span className={drawer.spacer}/>{selected.status==='환불처리중'&&<button type="button" className={drawer.actionLink} onClick={()=>update('취소완료')}>환불 완료</button>}</>} stats={[{label:'상품 금액',value:formatWon(purchase.amount)},{label:'환불 예정',value:formatWon(selected.refundAmount)},{label:'배송비',value:formatWon(purchase.deliveryFee)}]} fields={[{label:'구매번호',value:selected.purchaseId},{label:'취소 사유',value:selected.reasonType},{label:'귀책 구분',value:selected.responsibility},{label:'환불 방법',value:selected.refundMethod},{label:'담당자',value:selected.assignee},{label:'처리 완료일',value:selected.completedAt}]}><div className={drawer.sectionTitleLoose}>구매자 요청 내용</div><div className={styles.reasonCard}>{selected.reason}</div><div className={drawer.sectionTitleLoose}>판매자 응답</div><div className={drawer.bodyText}>{selected.sellerResponse}</div><div className={drawer.sectionTitleLoose}>환불 구성</div><div className={styles.refundBreakdown}><div><span>상품 금액</span><strong>{formatWon(purchase.amount)}</strong></div><div><span>배송비 환불</span><strong>{selected.responsibility==='판매자'?formatWon(purchase.deliveryFee):'0원'}</strong></div><div><span>최종 환불액</span><strong>{formatWon(selected.refundAmount)}</strong></div></div></DetailDrawer>}
    {toast&&<div className={base.toast}>{toast}</div>}
  </section>;
}
