import { useMemo, useState } from 'react';
import { DataGrid } from '../../components/DataGrid'; import type { GridColumn, GridRow } from '../../components/DataGrid/types';
import { ExcelDownloadButton } from '../../components/common/ExcelDownloadButton'; import { DatePicker } from '../../components/forms/DatePicker';
import shared from './shared.module.css'; import { CouponSummaryDrawer } from './CouponSummaryDrawer';
import { COUPONS, STATUS_META, computeStatus, discountSummary, issuePeriodSummary, validitySummary } from './couponsData';

const TRIGGERS: Record<string, string> = { NEW5000: '회원가입 완료', CATE01: '대상 카테고리 첫 구매', BADVALID: '휴면 회원 복귀' };
const COLUMNS: GridColumn[] = [{ label: '쿠폰' }, { label: '자동 발급 조건' }, { label: '혜택' }, { label: '발급 기간' }, { label: '유효기간' }, { label: '발급 한도', align: 'right' }, { label: '발급 수', align: 'right' }, { label: '상태' }];

export function AutomaticCouponsPage() {
  const [keyword, setKeyword] = useState(''); const [status, setStatus] = useState(''); const [selectedId, setSelectedId] = useState<string | null>(null);
  const filtered = useMemo(() => COUPONS.filter((item) => item.issueMethod === '자동 발급' && (!status || computeStatus(item) === status) && (!keyword || `${item.name} ${item.code} ${TRIGGERS[item.code] ?? ''}`.toLowerCase().includes(keyword.toLowerCase()))), [keyword, status]); const selected = COUPONS.find((item) => item.id === selectedId) ?? null;
  const rows: GridRow[] = filtered.map((item) => { const state = computeStatus(item); return { id: item.id, onClick: () => setSelectedId(item.id), cells: [{ kind: 'stack', title: item.name, subtitle: item.code }, { kind: 'text', text: TRIGGERS[item.code] ?? '운영 이벤트 조건', weight: 600 }, { kind: 'text', text: discountSummary(item), weight: 600 }, { kind: 'text', text: issuePeriodSummary(item) }, { kind: 'text', text: validitySummary(item) }, { kind: 'text', text: item.totalLimit ? item.totalLimit.toLocaleString() : '무제한', align: 'right', numeric: true }, { kind: 'text', text: item.issuedCount.toLocaleString(), align: 'right', numeric: true }, { kind: 'badge', text: state, ...STATUS_META[state] }] }; });
  return <div className={shared.page}><div className={shared.headTop}><div className={shared.headRow}><div><div className={shared.title}>자동 발급</div><div className={shared.subtitle}>회원 행동과 운영 이벤트 조건에 따라 자동 발급되는 쿠폰을 관리합니다.</div></div></div><div className={shared.filterBox}><form className={shared.filterRow1} onSubmit={(event) => event.preventDefault()}><input className={shared.searchInput} value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="쿠폰명 / 코드 / 자동 발급 조건"/><button className={shared.searchBtn}>검색</button></form><div className={shared.filterRow2}><label className="globalFilterField"><span>발급 상태</span><select className={shared.selectSm} value={status} onChange={(event) => setStatus(event.target.value)}><option value="">전체 발급 상태</option><option>발급중</option><option>발급 예정</option><option>발급 종료</option><option>비활성</option></select></label><label className={shared.dateFilterField}><span>발급 기간</span><span className={shared.dateRange}><DatePicker defaultValue="2026-08-01"/><span className={shared.dateSeparator}>~</span><DatePicker defaultValue="2026-08-31"/></span></label><span className={shared.rowSpacer}/><button type="button" className="detailFilterBtn">상세 필터</button><button className={shared.resetBtn} onClick={() => { setKeyword(''); setStatus(''); }}>초기화</button></div></div><div className={shared.resultRow}><span className={shared.resultLabel}>총 {filtered.length}개 자동 발급 정책</span><div className={shared.resultActions}><ExcelDownloadButton data-grid-download/></div></div></div><div className={shared.gridWrap}><DataGrid columns={COLUMNS} rows={rows} gridTemplate="minmax(210px,1.2fr) minmax(180px,1fr) 75px 170px 150px 90px 80px 85px" minWidth="1050px" empty={!rows.length} emptyText="등록된 자동 발급 쿠폰이 없습니다." showPagination pages={[{ label: '1', active: true }]}/></div>{selected && <CouponSummaryDrawer coupon={selected} eyebrow="자동 발급" onClose={() => setSelectedId(null)}/>}</div>;
}
