import { useMemo, useState } from 'react';
import { DataGrid } from '../../components/DataGrid'; import type { GridColumn, GridRow } from '../../components/DataGrid/types';
import { ExcelDownloadButton } from '../../components/common/ExcelDownloadButton'; import { DatePicker } from '../../components/forms/DatePicker';
import shared from './shared.module.css'; import { CouponSummaryDrawer } from './CouponSummaryDrawer';
import { COUPONS, STATUS_META, computeStatus, discountSummary, issuePeriodSummary, validitySummary } from './couponsData';

const COLUMNS: GridColumn[] = [{ label: '쿠폰' }, { label: '발급 방식' }, { label: '혜택' }, { label: '발급 기간' }, { label: '사용 유효기간' }, { label: '발급 수', align: 'right' }, { label: '사용 수', align: 'right' }, { label: '담당자' }, { label: '상태' }];

export function ExpiredCouponsPage() {
  const [keyword, setKeyword] = useState(''); const [method, setMethod] = useState(''); const [selectedId, setSelectedId] = useState<string | null>(null);
  const filtered = useMemo(() => COUPONS.filter((item) => computeStatus(item) === '발급 종료' && (!method || item.issueMethod === method) && (!keyword || `${item.name} ${item.code} ${item.owner}`.toLowerCase().includes(keyword.toLowerCase()))), [keyword, method]); const selected = COUPONS.find((item) => item.id === selectedId) ?? null;
  const rows: GridRow[] = filtered.map((item) => ({ id: item.id, onClick: () => setSelectedId(item.id), cells: [{ kind: 'stack', title: item.name, subtitle: item.code }, { kind: 'text', text: item.issueMethod }, { kind: 'text', text: discountSummary(item), weight: 600 }, { kind: 'text', text: issuePeriodSummary(item) }, { kind: 'text', text: validitySummary(item) }, { kind: 'text', text: item.issuedCount.toLocaleString(), align: 'right', numeric: true }, { kind: 'text', text: item.usedCount.toLocaleString(), align: 'right', numeric: true }, { kind: 'text', text: item.owner }, { kind: 'badge', text: '발급 종료', ...STATUS_META['발급 종료'] }] }));
  return <div className={shared.page}><div className={shared.headTop}><div className={shared.headRow}><div><div className={shared.title}>만료 쿠폰</div><div className={shared.subtitle}>발급 기간이 종료된 쿠폰의 발급·사용 실적과 유효기간을 조회합니다.</div></div></div><div className={shared.filterBox}><form className={shared.filterRow1} onSubmit={(event) => event.preventDefault()}><input className={shared.searchInput} value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="쿠폰명 / 코드 / 담당자"/><button className={shared.searchBtn}>검색</button></form><div className={shared.filterRow2}><label className="globalFilterField"><span>발급 방식</span><select className={shared.selectSm} value={method} onChange={(event) => setMethod(event.target.value)}><option value="">전체 발급 방식</option><option>관리자 발급</option><option>자동 발급</option></select></label><label className={shared.dateFilterField}><span>종료일</span><span className={shared.dateRange}><DatePicker defaultValue="2026-06-01"/><span className={shared.dateSeparator}>~</span><DatePicker defaultValue="2026-08-31"/></span></label><span className={shared.rowSpacer}/><button type="button" className="detailFilterBtn">상세 필터</button><button className={shared.resetBtn} onClick={() => { setKeyword(''); setMethod(''); }}>초기화</button></div></div><div className={shared.resultRow}><span className={shared.resultLabel}>총 {filtered.length}개 만료 쿠폰</span><div className={shared.resultActions}><ExcelDownloadButton data-grid-download/></div></div></div><div className={shared.gridWrap}><DataGrid columns={COLUMNS} rows={rows} gridTemplate="minmax(210px,1.2fr) 95px 75px 170px 155px 80px 80px 90px 85px" minWidth="1040px" empty={!rows.length} emptyText="조건에 맞는 만료 쿠폰이 없습니다." showPagination pages={[{ label: '1', active: true }]}/></div>{selected && <CouponSummaryDrawer coupon={selected} eyebrow="만료 쿠폰" onClose={() => setSelectedId(null)}/>}</div>;
}
