import { useMemo, useState } from 'react';
import { DataGrid } from '../../components/DataGrid'; import type { GridColumn, GridRow } from '../../components/DataGrid/types';
import { ExcelDownloadButton } from '../../components/common/ExcelDownloadButton'; import { DatePicker } from '../../components/forms/DatePicker';
import shared from '../ops/opsShared.module.css'; import { ControlArea, FilterBox, GridArea, Metrics, PageHeading, ResultBar } from '../c2c/sales/SalesActivityShared';
import { PromotionScopeDetailDrawer } from './PromotionScopeDetailDrawer'; import { PROMOTIONS, STATUS_META, computeStatus, discountSummary, fmtWon, periodSummary } from './promotionsData';

const COLUMNS: GridColumn[] = [{ label: '프로모션' }, { label: '할인 방식' }, { label: '할인' }, { label: '최소 주문금액', align: 'right' }, { label: '최대 할인', align: 'right' }, { label: '쿠폰 중복' }, { label: '적용 기간' }, { label: '상태' }];
export function CartPromotionsPage() {
  const [keyword, setKeyword] = useState(''); const [method, setMethod] = useState(''); const [selectedId, setSelectedId] = useState<string | null>(null);
  const filtered = useMemo(() => PROMOTIONS.filter((item) => item.applyUnit === '주문' && (!method || item.discountMethod === method) && (!keyword || `${item.name} ${item.code}`.toLowerCase().includes(keyword.toLowerCase()))), [keyword, method]); const selected = PROMOTIONS.find((item) => item.id === selectedId) ?? null;
  const rows: GridRow[] = filtered.map((item) => { const state = computeStatus(item); return { id: item.id, onClick: () => setSelectedId(item.id), cells: [{ kind: 'stack', title: item.name, subtitle: item.code }, { kind: 'text', text: item.discountMethod }, { kind: 'text', text: discountSummary(item), weight: 600 }, { kind: 'text', text: fmtWon(item.minPurchaseAmount), align: 'right', numeric: true }, { kind: 'text', text: item.maxDiscountAmount ? fmtWon(item.maxDiscountAmount) : '-', align: 'right', numeric: true }, { kind: 'badge', text: item.stackCoupon, bg: item.stackCoupon === '가능' ? '#ecfdf5' : '#fef2f2', fg: item.stackCoupon === '가능' ? '#047857' : '#dc2626' }, { kind: 'text', text: periodSummary(item) }, { kind: 'badge', text: state, ...STATUS_META[state] }] }; });
  return <section className={shared.page}><PageHeading title="장바구니 할인" subtitle="주문 합계와 최소 구매금액을 기준으로 적용되는 장바구니 할인을 관리합니다."/><Metrics items={[{ label: '장바구니 할인', value: `${PROMOTIONS.filter((item) => item.applyUnit === '주문').length}개`, note: '주문 단위' }, { label: '진행중', value: `${filtered.filter((item) => computeStatus(item) === '진행중').length}개`, note: '현재 적용', dot: '#10b981' }, { label: '정률 할인', value: `${filtered.filter((item) => item.discountMethod === '정률').length}개`, note: '할인율 적용' }, { label: '정액 할인', value: `${filtered.filter((item) => item.discountMethod === '정액').length}개`, note: '고정 금액 적용' }]}/><ControlArea><FilterBox><form className={shared.filterRow1} onSubmit={(event) => event.preventDefault()}><label className="globalFilterField"><span>검색 범위</span><select className={shared.selectSm}><option>전체 검색</option><option>프로모션명</option><option>코드</option></select></label><input className={shared.searchInput} value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="프로모션명 / 코드"/><button className={shared.searchBtn}>조회</button></form><div className={shared.filterRow2}><label className="globalFilterField"><span>할인 방식</span><select className={shared.selectSm} value={method} onChange={(event) => setMethod(event.target.value)}><option value="">전체 할인 방식</option><option>정률</option><option>정액</option></select></label><label className={shared.dateFilterField}><span>적용 기간</span><span className={shared.dateRange}><DatePicker defaultValue="2026-09-01"/><span className={shared.dateSeparator}>~</span><DatePicker defaultValue="2026-09-30"/></span></label><span className={shared.rowSpacer}/><button className={shared.resetBtn} onClick={() => { setKeyword(''); setMethod(''); }}>초기화</button></div></FilterBox></ControlArea><GridArea><ResultBar count={filtered.length} unit="개"><ExcelDownloadButton data-grid-download/></ResultBar><DataGrid columns={COLUMNS} rows={rows} gridTemplate="minmax(220px,1.3fr) 90px 80px 110px 100px 85px 180px 85px" minWidth="980px" empty={!rows.length} emptyText="등록된 장바구니 할인이 없습니다." showPagination pages={[{ label: '1', active: true }]}/></GridArea>{selected && <PromotionScopeDetailDrawer promotion={selected} eyebrow="장바구니 할인" onClose={() => setSelectedId(null)}/>}</section>;
}
