import { useMemo, useState } from 'react';
import { DataGrid } from '../../components/DataGrid'; import type { GridColumn, GridRow } from '../../components/DataGrid/types';
import { ExcelDownloadButton } from '../../components/common/ExcelDownloadButton';
import shared from '../ops/opsShared.module.css'; import { ControlArea, FilterBox, GridArea, Metrics, PageHeading, ResultBar } from '../c2c/sales/SalesActivityShared';
import { PRODUCTS } from '../products/productsData'; import { PromotionScopeDetailDrawer } from './PromotionScopeDetailDrawer';
import { PROMOTIONS, STATUS_META, computeStatus, discountSummary } from './promotionsData';

const COLUMNS: GridColumn[] = [{ label: '카테고리' }, { label: '대상 상품 수', align: 'right' }, { label: '프로모션' }, { label: '할인' }, { label: '최소 구매금액', align: 'right' }, { label: '적용 기간' }, { label: '우선순위' }, { label: '상태' }];
export function CategoryPromotionsPage() {
  const [keyword, setKeyword] = useState(''); const [status, setStatus] = useState(''); const [selectedId, setSelectedId] = useState<string | null>(null);
  const records = useMemo(() => PROMOTIONS.flatMap((promotion) => promotion.targetCategories.map((category) => ({ promotion, category, productCount: PRODUCTS.filter((item) => item.category === category).length }))).filter(({ promotion, category }) => (!status || computeStatus(promotion) === status) && (!keyword || `${category} ${promotion.name} ${promotion.code}`.toLowerCase().includes(keyword.toLowerCase()))), [keyword, status]); const selected = PROMOTIONS.find((item) => item.id === selectedId) ?? null;
  const rows: GridRow[] = records.map(({ promotion, category, productCount }) => { const state = computeStatus(promotion); return { id: `${promotion.id}-${category}`, onClick: () => setSelectedId(promotion.id), cells: [{ kind: 'text', text: category, weight: 600 }, { kind: 'text', text: String(productCount), align: 'right', numeric: true }, { kind: 'stack', title: promotion.name, subtitle: promotion.code }, { kind: 'text', text: discountSummary(promotion), weight: 600 }, { kind: 'text', text: `${promotion.minPurchaseAmount.toLocaleString()}원`, align: 'right', numeric: true }, { kind: 'text', text: `${promotion.startDate} ~ ${promotion.endDate ?? ''}` }, { kind: 'text', text: String(promotion.priority), numeric: true }, { kind: 'badge', text: state, ...STATUS_META[state] }] }; });
  return <section className={shared.page}><PageHeading title="카테고리 할인" subtitle="카테고리별 할인 정책과 대상 상품 범위를 관리합니다."/><Metrics items={[{ label: '연결 카테고리', value: `${new Set(records.map((item) => item.category)).size}개`, note: '현재 필터 기준' }, { label: '카테고리 프로모션', value: `${PROMOTIONS.filter((item) => item.targetType === '특정 카테고리').length}개`, note: '등록 정책' }, { label: '진행중', value: `${records.filter((item) => computeStatus(item.promotion) === '진행중').length}개`, note: '현재 적용', dot: '#10b981' }, { label: '중복 불가', value: `${records.filter((item) => item.promotion.stackPromotion === '불가').length}개`, note: '우선순위 확인', dot: '#f59e0b' }]}/><ControlArea><FilterBox><form className={shared.filterRow1} onSubmit={(event) => event.preventDefault()}><label className="globalFilterField"><span>검색 범위</span><select className={shared.selectSm}><option>전체 검색</option><option>카테고리</option><option>프로모션</option></select></label><input className={shared.searchInput} value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="카테고리 / 프로모션명 / 코드"/><button className={shared.searchBtn}>조회</button></form><div className={shared.filterRow2}><label className="globalFilterField"><span>상태</span><select className={shared.selectSm} value={status} onChange={(event) => setStatus(event.target.value)}><option value="">전체 상태</option><option>진행중</option><option>진행 예정</option><option>종료</option><option>비활성</option></select></label><span className={shared.rowSpacer}/><button className={shared.resetBtn} onClick={() => { setKeyword(''); setStatus(''); }}>초기화</button></div></FilterBox></ControlArea><GridArea><ResultBar count={records.length} unit="개"><ExcelDownloadButton data-grid-download/></ResultBar><DataGrid columns={COLUMNS} rows={rows} gridTemplate="130px 95px minmax(210px,1.2fr) 80px 110px 190px 75px 85px" minWidth="1000px" empty={!rows.length} emptyText="연결된 카테고리 할인이 없습니다." showPagination pages={[{ label: '1', active: true }]}/></GridArea>{selected && <PromotionScopeDetailDrawer promotion={selected} eyebrow="카테고리 할인" onClose={() => setSelectedId(null)}/>}</section>;
}
