import { useMemo, useState } from 'react';
import { DataGrid } from '../../components/DataGrid'; import type { GridColumn, GridRow } from '../../components/DataGrid/types';
import { ExcelDownloadButton } from '../../components/common/ExcelDownloadButton';
import shared from '../ops/opsShared.module.css'; import { ControlArea, FilterBox, GridArea, Metrics, PageHeading, ResultBar } from '../c2c/sales/SalesActivityShared';
import { PromotionScopeDetailDrawer } from './PromotionScopeDetailDrawer'; import { PROMOTIONS, STATUS_META, computeStatus, discountSummary, periodSummary, targetSummary } from './promotionsData';

const GROUPS = ['신규 회원','일반 회원','VIP','휴면 복귀'] as const;
const COLUMNS: GridColumn[] = [{ label: '회원 그룹' }, { label: '프로모션' }, { label: '적용 대상' }, { label: '할인' }, { label: '사용 횟수', align: 'right' }, { label: '담당자' }, { label: '적용 기간' }, { label: '상태' }];
export function MemberPromotionsPage() {
  const [keyword, setKeyword] = useState(''); const [group, setGroup] = useState(''); const [selectedId, setSelectedId] = useState<string | null>(null);
  const records = useMemo(() => PROMOTIONS.map((promotion, index) => ({ promotion, group: GROUPS[index % GROUPS.length] })).filter((row) => (!group || row.group === group) && (!keyword || `${row.group} ${row.promotion.name} ${row.promotion.code}`.toLowerCase().includes(keyword.toLowerCase()))), [group, keyword]); const selected = PROMOTIONS.find((item) => item.id === selectedId) ?? null;
  const rows: GridRow[] = records.map(({ promotion, group: memberGroup }) => { const state = computeStatus(promotion); return { id: `${promotion.id}-${memberGroup}`, onClick: () => setSelectedId(promotion.id), cells: [{ kind: 'badge', text: memberGroup, bg: '#eff6ff', fg: '#2563eb' }, { kind: 'stack', title: promotion.name, subtitle: promotion.code }, { kind: 'text', text: targetSummary(promotion) }, { kind: 'text', text: discountSummary(promotion), weight: 600 }, { kind: 'text', text: promotion.appliedCount.toLocaleString(), align: 'right', numeric: true }, { kind: 'text', text: promotion.owner }, { kind: 'text', text: periodSummary(promotion) }, { kind: 'badge', text: state, ...STATUS_META[state] }] }; });
  return <section className={shared.page}><PageHeading title="회원 할인" subtitle="회원 등급과 생애주기 그룹별 프로모션 혜택을 관리합니다."/><Metrics items={[{ label: '회원 할인 정책', value: `${records.length}개`, note: '현재 필터 기준' }, { label: '대상 그룹', value: `${new Set(records.map((item) => item.group)).size}개`, note: '회원 세그먼트' }, { label: '진행중', value: `${records.filter((item) => computeStatus(item.promotion) === '진행중').length}개`, note: '현재 적용', dot: '#10b981' }, { label: '누적 적용', value: `${records.reduce((sum, item) => sum + item.promotion.appliedCount, 0).toLocaleString()}건`, note: '전체 기간' }]}/><ControlArea><FilterBox><form className={shared.filterRow1} onSubmit={(event) => event.preventDefault()}><input className={shared.searchInput} value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="회원 그룹 / 프로모션명 / 코드"/><button className={shared.searchBtn}>조회</button></form><div className={shared.filterRow2}><label className="globalFilterField"><span>회원 그룹</span><select className={shared.selectSm} value={group} onChange={(event) => setGroup(event.target.value)}><option value="">전체 회원 그룹</option>{GROUPS.map((item) => <option key={item}>{item}</option>)}</select></label><span className={shared.rowSpacer}/><button type="button" className="detailFilterBtn">상세 필터</button><button className={shared.resetBtn} onClick={() => { setKeyword(''); setGroup(''); }}>초기화</button></div></FilterBox></ControlArea><GridArea><ResultBar count={records.length} unit="개"><ExcelDownloadButton data-grid-download/></ResultBar><DataGrid columns={COLUMNS} rows={rows} gridTemplate="105px minmax(210px,1.2fr) 150px 80px 90px 90px 180px 85px" minWidth="990px" empty={!rows.length} emptyText="등록된 회원 할인이 없습니다." showPagination pages={[{ label: '1', active: true }]}/></GridArea>{selected && <PromotionScopeDetailDrawer promotion={selected} eyebrow="회원 할인" onClose={() => setSelectedId(null)}/>}</section>;
}
