import { useMemo, useState } from 'react';
import { DataGrid } from '../../components/DataGrid';
import type { GridColumn, GridRow } from '../../components/DataGrid/types';
import { ExcelDownloadButton } from '../../components/common/ExcelDownloadButton';
import { DatePicker } from '../../components/forms/DatePicker';
import shared from '../ops/opsShared.module.css';
import { ControlArea, FilterBox, GridArea, Metrics, PageHeading, ResultBar } from '../c2c/sales/SalesActivityShared';
import { PromotionScopeDetailDrawer } from './PromotionScopeDetailDrawer';
import { PROMOTIONS, STATUS_META, computeStatus, discountSummary, matchesQuickFilter, periodSummary, targetSummary, type QuickFilter } from './promotionsData';

const COLUMNS: GridColumn[] = [{ label: '프로모션' }, { label: '할인' }, { label: '적용 대상' }, { label: '시작일' }, { label: '종료일' }, { label: '남은 기간' }, { label: '우선순위' }, { label: '상태' }];

export function PeriodPromotionsPage() {
  const [keyword, setKeyword] = useState(''); const [status, setStatus] = useState<QuickFilter>('전체'); const [selectedId, setSelectedId] = useState<string | null>(null);
  const issues = useMemo(() => Object.fromEntries(PROMOTIONS.map((item) => [item.id, [] as string[]])), []);
  const filtered = useMemo(() => PROMOTIONS.filter((item) => matchesQuickFilter(item, status, issues) && (!keyword || `${item.name} ${item.code}`.toLowerCase().includes(keyword.toLowerCase()))), [issues, keyword, status]); const selected = PROMOTIONS.find((item) => item.id === selectedId) ?? null;
  const rows: GridRow[] = filtered.map((item) => { const state = computeStatus(item); return { id: item.id, onClick: () => setSelectedId(item.id), cells: [{ kind: 'stack', title: item.name, subtitle: item.code }, { kind: 'text', text: discountSummary(item), weight: 600 }, { kind: 'text', text: targetSummary(item) }, { kind: 'text', text: item.startDate, numeric: true }, { kind: 'text', text: item.endDate ?? '상시', numeric: true }, { kind: 'text', text: periodSummary(item) }, { kind: 'text', text: String(item.priority), numeric: true }, { kind: 'badge', text: state, ...STATUS_META[state] }] }; });
  return <section className={shared.page}><PageHeading title="기간 할인" subtitle="시작일과 종료일을 기준으로 운영되는 프로모션의 일정과 우선순위를 관리합니다."/><Metrics items={[{ label: '전체 기간 할인', value: `${PROMOTIONS.length}개`, note: '등록 기준' }, { label: '진행중', value: `${PROMOTIONS.filter((item) => computeStatus(item) === '진행중').length}개`, note: '현재 적용', dot: '#10b981' }, { label: '진행 예정', value: `${PROMOTIONS.filter((item) => computeStatus(item) === '진행 예정').length}개`, note: '시작 대기', dot: '#4f7bd9' }, { label: '종료일 없음', value: `${PROMOTIONS.filter((item) => !item.endDate).length}개`, note: '상시 운영', dot: '#f59e0b' }]}/><ControlArea><FilterBox><form className={shared.filterRow1} onSubmit={(event) => event.preventDefault()}><label className="globalFilterField"><span>검색 범위</span><select className={shared.selectSm}><option>전체 검색</option><option>프로모션명</option><option>코드</option></select></label><input className={shared.searchInput} value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="프로모션명 / 코드"/><button className={shared.searchBtn}>조회</button></form><div className={shared.filterRow2}><label className="globalFilterField"><span>상태</span><select className={shared.selectSm} value={status} onChange={(event) => setStatus(event.target.value as QuickFilter)}><option>전체</option><option>진행중</option><option>진행 예정</option><option>종료</option><option>비활성</option></select></label><label className={shared.dateFilterField}><span>운영 기간</span><span className={shared.dateRange}><DatePicker defaultValue="2026-09-01"/><span className={shared.dateSeparator}>~</span><DatePicker defaultValue="2026-09-30"/></span></label><span className={shared.rowSpacer}/><button className={shared.resetBtn} onClick={() => { setKeyword(''); setStatus('전체'); }}>초기화</button></div></FilterBox></ControlArea><GridArea><ResultBar count={filtered.length} unit="개"><ExcelDownloadButton data-grid-download/></ResultBar><DataGrid columns={COLUMNS} rows={rows} gridTemplate="minmax(220px,1.4fr) 80px 150px 100px 100px 170px 75px 85px" minWidth="980px" empty={!rows.length} emptyText="조건에 맞는 기간 할인이 없습니다." showPagination pages={[{ label: '1', active: true }]}/></GridArea>{selected && <PromotionScopeDetailDrawer promotion={selected} eyebrow="기간 할인" onClose={() => setSelectedId(null)}/>}</section>;
}
