import { useMemo, useState } from 'react';
import { DataGrid } from '../../components/DataGrid'; import type { GridColumn, GridRow } from '../../components/DataGrid/types';
import { ExcelDownloadButton } from '../../components/common/ExcelDownloadButton';
import shared from '../ops/opsShared.module.css'; import { ControlArea, FilterBox, GridArea, Metrics, PageHeading, ResultBar } from '../c2c/sales/SalesActivityShared';
import { PRODUCTS } from '../products/productsData'; import { PromotionScopeDetailDrawer } from './PromotionScopeDetailDrawer';
import { PROMOTIONS, STATUS_META, computeStatus, discountSummary, productName } from './promotionsData';

const COLUMNS: GridColumn[] = [{ label: '상품코드' }, { label: '상품명' }, { label: '카테고리' }, { label: '프로모션' }, { label: '할인' }, { label: '판매가', align: 'right' }, { label: '적용 기간' }, { label: '상태' }];
export function ProductPromotionsPage() {
  const [keyword, setKeyword] = useState(''); const [category, setCategory] = useState(''); const [selectedId, setSelectedId] = useState<string | null>(null);
  const records = useMemo(() => PROMOTIONS.flatMap((promotion) => promotion.targetProductCodes.map((code) => ({ promotion, product: PRODUCTS.find((item) => item.code === code) }))).filter((row) => row.product && (!category || row.product.category === category) && (!keyword || `${row.promotion.name} ${row.product.name} ${row.product.code}`.toLowerCase().includes(keyword.toLowerCase()))), [category, keyword]); const selected = PROMOTIONS.find((item) => item.id === selectedId) ?? null;
  const rows: GridRow[] = records.map(({ promotion, product }) => { const state = computeStatus(promotion); return { id: `${promotion.id}-${product!.code}`, onClick: () => setSelectedId(promotion.id), cells: [{ kind: 'text', text: product!.code, weight: 600 }, { kind: 'text', text: productName(product!.code), weight: 600 }, { kind: 'text', text: product!.category }, { kind: 'stack', title: promotion.name, subtitle: promotion.code }, { kind: 'text', text: discountSummary(promotion), weight: 600 }, { kind: 'text', text: `${product!.price.toLocaleString()}원`, align: 'right', numeric: true }, { kind: 'text', text: `${promotion.startDate} ~ ${promotion.endDate ?? ''}` }, { kind: 'badge', text: state, ...STATUS_META[state] }] }; });
  const categories = [...new Set(PRODUCTS.map((item) => item.category))];
  return <section className={shared.page}><PageHeading title="상품 할인" subtitle="상품 단위로 연결된 할인 프로모션과 적용 기간을 관리합니다."/><Metrics items={[{ label: '할인 대상 상품', value: `${records.length}개`, note: '현재 필터 기준' }, { label: '상품 프로모션', value: `${PROMOTIONS.filter((item) => item.targetType === '특정 상품').length}개`, note: '등록 정책' }, { label: '진행중', value: `${PROMOTIONS.filter((item) => item.targetType === '특정 상품' && computeStatus(item) === '진행중').length}개`, note: '현재 적용', dot: '#10b981' }, { label: '제외 상품', value: `${new Set(PROMOTIONS.flatMap((item) => item.excludeProductCodes)).size}개`, note: '할인 제외', dot: '#f59e0b' }]}/><ControlArea><FilterBox><form className={shared.filterRow1} onSubmit={(event) => event.preventDefault()}><label className="globalFilterField"><span>검색 범위</span><select className={shared.selectSm}><option>전체 검색</option><option>상품명</option><option>상품코드</option></select></label><input className={shared.searchInput} value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="상품명 / 상품코드 / 프로모션"/><button className={shared.searchBtn}>조회</button></form><div className={shared.filterRow2}><label className="globalFilterField"><span>카테고리</span><select className={shared.selectSm} value={category} onChange={(event) => setCategory(event.target.value)}><option value="">전체 카테고리</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><span className={shared.rowSpacer}/><button className={shared.resetBtn} onClick={() => { setKeyword(''); setCategory(''); }}>초기화</button></div></FilterBox></ControlArea><GridArea><ResultBar count={records.length} unit="개"><ExcelDownloadButton data-grid-download/></ResultBar><DataGrid columns={COLUMNS} rows={rows} gridTemplate="100px minmax(180px,1fr) 110px minmax(210px,1.2fr) 80px 100px 190px 85px" minWidth="1055px" empty={!rows.length} emptyText="연결된 상품 할인이 없습니다." showPagination pages={[{ label: '1', active: true }]}/></GridArea>{selected && <PromotionScopeDetailDrawer promotion={selected} eyebrow="상품 할인" onClose={() => setSelectedId(null)}/>}</section>;
}
