import { useMemo, useState } from 'react';
import { DataGrid } from '../../components/DataGrid'; import type { GridColumn, GridRow } from '../../components/DataGrid/types';
import { ExcelDownloadButton } from '../../components/common/ExcelDownloadButton';
import shared from '../ops/opsShared.module.css'; import { ControlArea, FilterBox, GridArea, Metrics, PageHeading, ResultBar } from '../c2c/sales/SalesActivityShared';
import { PromotionScopeDetailDrawer } from './PromotionScopeDetailDrawer'; import { PROMOTIONS, STATUS_META, computeStatus, discountSummary, targetSummary } from './promotionsData';

const COLUMNS: GridColumn[] = [{ label: '프로모션' }, { label: '대상 유형' }, { label: '적용 대상' }, { label: '제외 상품', align: 'right' }, { label: '할인' }, { label: '중복 정책' }, { label: '우선순위' }, { label: '상태' }];
export function PromotionTargetsPage() {
  const [keyword, setKeyword] = useState(''); const [targetType, setTargetType] = useState(''); const [selectedId, setSelectedId] = useState<string | null>(null);
  const filtered = useMemo(() => PROMOTIONS.filter((item) => (!targetType || item.targetType === targetType) && (!keyword || `${item.name} ${item.code} ${targetSummary(item)}`.toLowerCase().includes(keyword.toLowerCase()))), [keyword, targetType]); const selected = PROMOTIONS.find((item) => item.id === selectedId) ?? null;
  const rows: GridRow[] = filtered.map((item) => { const state = computeStatus(item); return { id: item.id, onClick: () => setSelectedId(item.id), cells: [{ kind: 'stack', title: item.name, subtitle: item.code }, { kind: 'badge', text: item.targetType, bg: '#f4f4f5', fg: '#52525b' }, { kind: 'text', text: targetSummary(item), weight: 600 }, { kind: 'text', text: String(item.excludeProductCodes.length), align: 'right', numeric: true }, { kind: 'text', text: discountSummary(item), weight: 600 }, { kind: 'stack', title: `프로모션 ${item.stackPromotion}`, subtitle: `쿠폰 ${item.stackCoupon}` }, { kind: 'text', text: String(item.priority), numeric: true }, { kind: 'badge', text: state, ...STATUS_META[state] }] }; });
  return <section className={shared.page}><PageHeading title="프로모션 대상 관리" subtitle="프로모션별 적용 상품·카테고리와 제외 대상을 한곳에서 관리합니다."/><Metrics items={[{ label: '전체 프로모션', value: `${PROMOTIONS.length}개`, note: '대상 설정 기준' }, { label: '전체 대상', value: `${PROMOTIONS.filter((item) => item.targetType === '전체').length}개`, note: '전 상품 적용' }, { label: '상품 지정', value: `${PROMOTIONS.filter((item) => item.targetType === '특정 상품').length}개`, note: '상품 단위' }, { label: '카테고리 지정', value: `${PROMOTIONS.filter((item) => item.targetType === '특정 카테고리').length}개`, note: '카테고리 단위' }]}/><ControlArea><FilterBox><form className={shared.filterRow1} onSubmit={(event) => event.preventDefault()}><label className="globalFilterField"><span>검색 범위</span><select className={shared.selectSm}><option>전체 검색</option><option>프로모션</option><option>적용 대상</option></select></label><input className={shared.searchInput} value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="프로모션명 / 코드 / 상품 / 카테고리"/><button className={shared.searchBtn}>조회</button></form><div className={shared.filterRow2}><label className="globalFilterField"><span>대상 유형</span><select className={shared.selectSm} value={targetType} onChange={(event) => setTargetType(event.target.value)}><option value="">전체 대상 유형</option><option>전체</option><option>특정 상품</option><option>특정 카테고리</option></select></label><span className={shared.rowSpacer}/><button className={shared.resetBtn} onClick={() => { setKeyword(''); setTargetType(''); }}>초기화</button></div></FilterBox></ControlArea><GridArea><ResultBar count={filtered.length} unit="개"><ExcelDownloadButton data-grid-download/></ResultBar><DataGrid columns={COLUMNS} rows={rows} gridTemplate="minmax(220px,1.25fr) 110px minmax(180px,1fr) 85px 80px 130px 75px 85px" minWidth="1005px" empty={!rows.length} emptyText="조건에 맞는 프로모션 대상이 없습니다." showPagination pages={[{ label: '1', active: true }]}/></GridArea>{selected && <PromotionScopeDetailDrawer promotion={selected} eyebrow="프로모션 대상" onClose={() => setSelectedId(null)}/>}</section>;
}
