import { DatePicker } from '../../../components/forms/DatePicker';
import { useMemo, useState } from 'react';
import { DataGrid } from '../../../components/DataGrid';
import type { GridRow } from '../../../components/DataGrid/types';
import shared from '../../ops/opsShared.module.css';
import drawer from '../../ops/opsDrawerShared.module.css';
import styles from './SalesActivity.module.css';
import { ControlArea, DetailDrawer, Field, FilterBox, GridArea, Metrics, PageHeading, ResultBar } from './SalesActivityShared';
import { RESTRICTION_STATUS_META, SALE_RESTRICTIONS, SELLERS, sellerById, type RestrictionStatus, type SaleRestriction } from './salesActivityData';
import { downloadCsv, pages } from './salesActivityUtils';

const QUICK:Array<'전체'|RestrictionStatus>=['전체','적용중','예약','해제','만료'];
const EMPTY_FORM={sellerId:'',type:'판매 제한' as SaleRestriction['type'],reason:'',startedAt:'2026-08-26',endedAt:'2026-09-02',source:'운영자 직접 등록',memo:''};

export function SalesRestrictionsPage(){
  const [restrictions,setRestrictions]=useState(SALE_RESTRICTIONS); const [quick,setQuick]=useState<(typeof QUICK)[number]>('전체'); const [keyword,setKeyword]=useState(''); const [search,setSearch]=useState(''); const [type,setType]=useState('');
  const [selectedId,setSelectedId]=useState<string|null>(null); const [editorOpen,setEditorOpen]=useState(false); const [form,setForm]=useState(EMPTY_FORM); const [toast,setToast]=useState('');
  const filtered=useMemo(()=>restrictions.filter((item)=>(quick==='전체'||item.status===quick)&&(!type||item.type===type)&&(!search||`${item.id} ${sellerById(item.sellerId)?.nickname??''} ${item.sellerId} ${item.reason} ${item.source}`.toLowerCase().includes(search.toLowerCase()))),[quick,restrictions,search,type]);
  const selected=restrictions.find((item)=>item.id===selectedId)??null; const selectedSeller=selected?sellerById(selected.sellerId):null;
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),2300);};
  const release=()=>{if(!selected)return;setRestrictions((items)=>items.map((item)=>item.id===selected.id?{...item,status:'해제',endedAt:'2026-08-26 15:40',memo:`${item.memo}\n운영자 admin01 수동 해제`}:item));notify(`${selectedSeller?.nickname??selected.sellerId} 판매 제한을 해제했습니다.`);};
  const save=()=>{if(!form.sellerId||!form.reason.trim())return notify('판매자와 제한 사유를 입력해 주세요.');const item:SaleRestriction={id:`RST-260826-${String(restrictions.length+21).padStart(3,'0')}`,sellerId:form.sellerId,type:form.type,reason:form.reason.trim(),startedAt:`${form.startedAt} 00:00`,endedAt:`${form.endedAt} 23:59`,status:form.startedAt>'2026-08-26'?'예약':'적용중',operator:'admin01',source:form.source,memo:form.memo};setRestrictions((items)=>[item,...items]);setEditorOpen(false);setSelectedId(item.id);notify('판매 제한을 등록했습니다.');};
  const rows:GridRow[]=filtered.map((item)=>{const seller=sellerById(item.sellerId);return{id:item.id,onClick:()=>setSelectedId(item.id),cells:[{kind:'stack',title:item.id,subtitle:item.source},{kind:'avatarText',title:seller?.nickname??item.sellerId,subtitle:`${seller?.name??'-'} · ${item.sellerId}`,avatarChar:(seller?.nickname??'판')[0],avatarBg:'#fef2f2',avatarFg:'#dc2626'},{kind:'pillText',text:item.type,bg:item.type==='판매 제한'?'#fef2f2':'#fff7ed',fg:item.type==='판매 제한'?'#dc2626':'#c2410c'},{kind:'stack',title:item.reason,subtitle:item.memo||'운영 메모 없음'},{kind:'text',text:item.startedAt,numeric:true},{kind:'text',text:item.endedAt,numeric:true},{kind:'badge',text:item.status,...RESTRICTION_STATUS_META[item.status]},{kind:'text',text:item.operator},{kind:'link',text:'상세'}]};});
  return <section className={shared.page}>
    <PageHeading title="판매 제한" subtitle="판매자별 경고, 상품 등록 제한과 판매 제한을 등록하고 해제합니다." action={<><button type="button" className={shared.downloadBtn} onClick={()=>downloadCsv('판매-제한-내역.csv',['제한번호','판매자','유형','사유','시작','종료','상태','담당자'],filtered.map((item)=>[item.id,sellerById(item.sellerId)?.nickname??item.sellerId,item.type,item.reason,item.startedAt,item.endedAt,item.status,item.operator]))}>다운로드</button><button type="button" className={shared.createBtn} onClick={()=>{setForm(EMPTY_FORM);setEditorOpen(true);}}>+ 판매 제한 등록</button></>}/>
    <Metrics items={[{label:'현재 적용중',value:`${restrictions.filter((r)=>r.status==='적용중').length}건`,note:'즉시 확인 필요',tone:'down',dot:'#ef4444'},{label:'예약 제한',value:`${restrictions.filter((r)=>r.status==='예약').length}건`,note:'향후 자동 적용 예정',dot:'#f59e0b'},{label:'이번 달 해제',value:`${restrictions.filter((r)=>r.status==='해제').length}건`,note:'운영자 검토 완료',dot:'#4f7bd9'},{label:'제한 판매자',value:`${new Set(restrictions.filter((r)=>r.status==='적용중').map((r)=>r.sellerId)).size}명`,note:'중복 판매자 제외',dot:'#8b5cf6'}]}/>
    <ControlArea><div className={shared.quickFilters}>{QUICK.map((item)=><button type="button" key={item} className={`${shared.qfBtn} ${quick===item?styles.quickActive:''}`} onClick={()=>setQuick(item)}><span className={shared.qfLabel}>{item}</span><span className={shared.qfCount}>{restrictions.filter((r)=>item==='전체'||r.status===item).length}</span></button>)}</div><FilterBox><form className={shared.filterRow1} onSubmit={(e)=>{e.preventDefault();setSearch(keyword.trim());}}><select className={shared.selectSm}><option>통합 검색</option><option>제한번호</option><option>판매자</option><option>사유</option></select><input className={shared.searchInput} value={keyword} onChange={(e)=>setKeyword(e.target.value)} placeholder="제한번호 / 판매자 / 제한 사유 / 연결 건"/><button className={shared.searchBtn}>조회</button></form><div className={shared.filterRow2}><select className={shared.selectSm} value={type} onChange={(e)=>setType(e.target.value)}><option value="">전체 제한 유형</option><option>경고</option><option>상품 등록 제한</option><option>판매 제한</option></select><span>적용 기간</span><DatePicker className={shared.selectSm} defaultValue="2026-08-01"/><span>~</span><DatePicker className={shared.selectSm} defaultValue="2026-08-31"/><span className={shared.rowSpacer}/><button type="button" className={shared.resetBtn} onClick={()=>{setKeyword('');setSearch('');setType('');}}>초기화</button></div></FilterBox></ControlArea>
    <GridArea><ResultBar count={filtered.length} unit="건"/><DataGrid columns={[{label:'제한번호 / 출처'},{label:'판매자'},{label:'제한 유형'},{label:'제한 사유'},{label:'시작일'},{label:'종료일'},{label:'상태'},{label:'담당자'},{label:'관리'}]} rows={rows} gridTemplate="145px 150px 104px minmax(190px,1.4fr) 125px 125px 72px 70px 55px" minWidth="1080px" empty={!filtered.length} emptyText="조건에 맞는 판매 제한 내역이 없습니다." showPagination pages={pages} rangeLabel={filtered.length?`1–${filtered.length} / ${filtered.length}`:'0건'}/></GridArea>
    {selected&&selectedSeller&&<DetailDrawer eyebrow={`판매 제한 상세 · ${selected.id}`} title={selectedSeller.nickname} status={selected.status} statusMeta={RESTRICTION_STATUS_META[selected.status]} subtitle={`${selected.type} · ${selected.source}`} onClose={()=>setSelectedId(null)} actions={<>{selected.status==='적용중'&&<button type="button" className={drawer.primaryBtn} onClick={release}>제한 해제</button>}<span className={drawer.spacer}/><button type="button" className={drawer.actionLink} onClick={()=>notify('판매자에게 제한 안내를 재발송했습니다.')}>안내 재발송</button></>} stats={[{label:'누적 제한',value:`${restrictions.filter((r)=>r.sellerId===selected.sellerId).length}건`},{label:'누적 신고',value:`${selectedSeller.reportCount}건`},{label:'취소율',value:`${selectedSeller.cancelRate.toFixed(1)}%`}]} fields={[{label:'제한 유형',value:selected.type},{label:'제한 사유',value:selected.reason},{label:'적용 시작',value:selected.startedAt},{label:'적용 종료',value:selected.endedAt},{label:'처리자',value:selected.operator},{label:'연결 출처',value:selected.source}]}><div className={drawer.sectionTitleLoose}>운영 메모</div><div className={drawer.bodyText}>{selected.memo||'등록된 운영 메모가 없습니다.'}</div><div className={drawer.sectionTitleLoose}>영향 범위</div><div className={styles.warningBox}>{selected.type==='판매 제한'?'판매 중 상품 비노출 · 신규 상품 등록 및 신규 거래 차단':'해당 기능에 한해 제한 적용'}</div></DetailDrawer>}
    {editorOpen&&<div className={shared.dialogOverlay} onMouseDown={(e)=>{if(e.target===e.currentTarget)setEditorOpen(false);}}><div className={`${shared.dialogBox} ${styles.dialogWide}`}><h2 className={shared.dialogTitle}>판매 제한 등록</h2><p className={shared.dialogBody}>판매자 영향 범위와 근거를 확인한 후 제한을 등록합니다.</p><div className={styles.formGrid}><Field label="판매자 *"><select value={form.sellerId} onChange={(e)=>setForm({...form,sellerId:e.target.value})}><option value="">판매자 선택</option>{SELLERS.map((seller)=><option key={seller.id} value={seller.id}>{seller.nickname} · {seller.id}</option>)}</select></Field><Field label="제한 유형 *"><select value={form.type} onChange={(e)=>setForm({...form,type:e.target.value as SaleRestriction['type']})}><option>경고</option><option>상품 등록 제한</option><option>판매 제한</option></select></Field><Field label="시작일"><DatePicker value={form.startedAt} onChange={(e)=>setForm({...form,startedAt:e.target.value})}/></Field><Field label="종료일"><DatePicker value={form.endedAt} onChange={(e)=>setForm({...form,endedAt:e.target.value})}/></Field><Field label="제한 근거" wide><input value={form.source} onChange={(e)=>setForm({...form,source:e.target.value})} placeholder="신고/분쟁/탐지 번호"/></Field><Field label="제한 사유 *" wide><textarea value={form.reason} onChange={(e)=>setForm({...form,reason:e.target.value})} placeholder="판매자에게 안내할 제한 사유"/></Field><Field label="운영 메모" wide><textarea value={form.memo} onChange={(e)=>setForm({...form,memo:e.target.value})} placeholder="내부 검토 내용과 해제 조건"/></Field></div><div className={styles.warningBox}>판매 제한을 즉시 적용하면 해당 판매자의 판매 중 상품이 비노출되고 신규 거래가 차단됩니다.</div><div className={shared.dialogActions}><button type="button" className={drawer.editCancel} onClick={()=>setEditorOpen(false)}>취소</button><button type="button" className={drawer.editConfirm} onClick={save}>제한 등록</button></div></div></div>}
    {toast&&<div className={styles.toast}>{toast}</div>}
  </section>;
}
