import { DatePicker } from '../../../components/forms/DatePicker';
import { useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { DataGrid } from '../../../components/DataGrid';
import type { GridRow } from '../../../components/DataGrid/types';
import shared from '../shared.module.css';
import drawer from '../../ops/opsDrawerShared.module.css';
import base from '../sales/SalesActivity.module.css';
import styles from './UserProducts.module.css';
import { CommonButton, showToast } from '../../../components/common';
import { ControlArea, DetailDrawer, FilterBox, GridArea, Metrics, PageHeading, ResultBar } from '../sales/SalesActivityShared';
import { downloadCsv, pages } from '../sales/salesActivityUtils';
import { formatWon, sellerById } from '../sales/salesActivityData';
import { MODERATION_META, PRODUCT_MODERATION_CASES, PRODUCT_REVIEWS, REVIEW_META, USER_PRODUCT_HISTORY, productById, type ModerationStatus, type ReviewStage } from './userProductData';

export function UserProductReviewPage(){
  const [reviews,setReviews]=useState(PRODUCT_REVIEWS);const[quick,setQuick]=useState<'전체'|ReviewStage>('전체');const[keyword,setKeyword]=useState('');const[search,setSearch]=useState('');const[reviewer,setReviewer]=useState('');const[selectedId,setSelectedId]=useState<string|null>(null);
  const filtered=useMemo(()=>reviews.filter((item)=>(quick==='전체'||item.stage===quick)&&(!reviewer||(reviewer==='미배정'?item.reviewer==='미배정':item.reviewer!=='미배정'))&&(!search||(()=>{const product=productById(item.productId);return `${item.id} ${item.productId} ${product?.title??''} ${sellerById(product?.sellerId??'')?.nickname??''}`.toLowerCase().includes(search.toLowerCase());})())),[quick,reviews,reviewer,search]);
  const selected=reviews.find((item)=>item.id===selectedId)??null;const product=selected?productById(selected.productId):null;const seller=product?sellerById(product.sellerId):null;const notify=(message:string)=>{showToast({ message, type: 'success' });};
  const update=(stage:ReviewStage,reason:string)=>{if(!selected)return;setReviews((items)=>items.map((item)=>item.id===selected.id?{...item,stage,reviewer:item.reviewer==='미배정'?'admin01':item.reviewer,reason}:item));notify(`${selected.productId} 상품을 ${stage}(으)로 처리했습니다.`);};
  const stages:Array<'전체'|ReviewStage>=['전체','등록대기','검수중','승인','반려'];
  const rows:GridRow[]=filtered.map((item)=>{const p=productById(item.productId);const s=sellerById(p?.sellerId??'');const failed=[item.imageCheck,item.descriptionCheck,item.categoryCheck].filter((value)=>!value).length;return{id:item.id,onClick:()=>setSelectedId(item.id),cells:[{kind:'stack',title:item.id,subtitle:item.submittedAt},{kind:'thumbTitle',thumb:'#e0e7ff',title:p?.title??item.productId,id:item.productId,onClick:()=>setSelectedId(item.id)},{kind:'stack',title:s?.nickname??'-',subtitle:p?.sellerId??'-'},{kind:'text',text:p?.category??'-'},{kind:'text',text:p?formatWon(p.price):'-',align:'right',numeric:true},{kind:'badge',text:item.stage,...REVIEW_META[item.stage]},{kind:'text',text:failed?`${failed}개 미충족`:'전체 충족',color:failed?'#dc2626':'#047857'},{kind:'text',text:item.reviewer,color:item.reviewer==='미배정'?'#dc2626':undefined},{kind:'link',text:'검수'}]};});
  return <div className={shared.page}><PageHeading title="등록 / 검수 관리" subtitle="사용자 등록 상품의 이미지, 설명, 카테고리와 금지 키워드를 확인하고 승인·반려합니다."/>
    <Metrics items={[{label:'등록 대기',value:`${reviews.filter((r)=>r.stage==='등록대기').length}건`,note:'신규 검수 배정 필요',tone:'down',dot:'#f59e0b'},{label:'검수 진행중',value:`${reviews.filter((r)=>r.stage==='검수중').length}건`,note:'체크리스트 확인 중',dot:'#4f7bd9'},{label:'오늘 승인',value:`${reviews.filter((r)=>r.stage==='승인').length}건`,note:'검수 기준 충족',tone:'up',dot:'#10b981'},{label:'반려 / 보완',value:`${reviews.filter((r)=>r.stage==='반려').length}건`,note:'판매자 수정 필요',tone:'down',dot:'#ef4444'}]}/>
    <ControlArea><div className={shared.quickFilters}>{stages.map((item) => {
      const active = quick === item;
      return (
        <CommonButton
          type="button"
          key={item}
          variant={active ? 'primary-light' : 'secondary'}
          size="md"
          className={`${shared.qfBtn} ${active ? base.quickActive : ''}`}
          onClick={() => setQuick(item)}
        >
          <span className={shared.qfLabel}>{item}</span>
          <span className={shared.qfCount}>{reviews.filter((r) => item === '전체' || r.stage === item).length}</span>
        </CommonButton>
      );
    })}</div><FilterBox><form className={shared.filterRow1} onSubmit={(e)=>{e.preventDefault();setSearch(keyword.trim());}}><label className="globalFilterField"><span>검색 범위</span><select aria-label="검색 범위" className={shared.selectSm}><option>통합 검색</option><option>검수번호</option><option>상품명</option><option>판매자</option></select></label><input className={shared.searchInput} value={keyword} onChange={(e)=>setKeyword(e.target.value)} placeholder="검수번호 / 상품 ID / 상품명 / 판매자"/><button className={shared.searchBtn}>조회</button></form><div className={shared.filterRow2}><label className="globalFilterField"><span>배정 상태</span><select aria-label="배정 상태" className={shared.selectSm} value={reviewer} onChange={(e)=>setReviewer(e.target.value)}><option value="">전체 배정 상태</option><option>미배정</option><option value="배정">검수자 배정</option></select></label><label className={shared.dateFilterField}><span>등록일</span><div className={shared.dateRange}><DatePicker className={shared.selectSm} defaultValue="2026-08-20"/><span className={shared.dateSeparator}>~</span><DatePicker className={shared.selectSm} defaultValue="2026-08-27"/></div></label><span className={shared.rowSpacer}/><button type="button" className={shared.resetBtn} onClick={()=>{setKeyword('');setSearch('');setReviewer('');}}>초기화</button></div></FilterBox></ControlArea>
    <div className={shared.splitRow}>
      <div className={shared.splitListCol}>
        <GridArea><ResultBar count={filtered.length} unit="건"/><DataGrid columns={[{label:'검수번호 / 등록일'},{label:'상품'},{label:'판매자'},{label:'카테고리'},{label:'판매가',align:'right'},{label:'검수 상태'},{label:'체크 결과'},{label:'검수자'},{label:'관리'}]} rows={rows} gridTemplate="125px minmax(200px,1.35fr) 84px 92px 88px 80px 74px 70px 55px" minWidth="965px" empty={!filtered.length} emptyText="조건에 맞는 검수 상품이 없습니다." showPagination pages={pages} rangeLabel={filtered.length?`1–${filtered.length} / ${filtered.length}`:'0건'}/></GridArea>
      </div>
      <div className={shared.splitDetailCol}>
        {selected&&product&&seller ? <DetailDrawer variant="panel" eyebrow={`상품 검수 · ${selected.id}`} title={product.title} status={selected.stage} statusMeta={REVIEW_META[selected.stage]} subtitle={`${seller.nickname} · ${product.category}`} onClose={()=>setSelectedId(null)} actions={<>{selected.stage!=='승인'&&<button type="button" className={drawer.primaryBtn} onClick={()=>update('승인','검수 체크리스트 충족')}>상품 승인</button>}<span className={drawer.spacer}/>{selected.stage!=='반려'&&<button type="button" className={drawer.dangerBtn} onClick={()=>update('반려','상품 설명 및 증빙 보완 필요')}>검수 반려</button>}</>} stats={[{label:'판매가',value:formatWon(product.price)},{label:'신고',value:`${product.reportCount}건`},{label:'검수자',value:selected.reviewer}]} fields={[{label:'상품 ID',value:product.id},{label:'판매자',value:`${seller.nickname} (${seller.id})`},{label:'상품 상태',value:product.condition},{label:'등록일',value:selected.submittedAt},{label:'금지 키워드',value:selected.prohibitedKeyword}]}><div className={drawer.sectionTitleLoose}>검수 체크리스트</div><div className={styles.checkList}>{[['상품 이미지',selected.imageCheck],['상품 설명',selected.descriptionCheck],['카테고리',selected.categoryCheck]].map(([label,ok])=><div key={String(label)} className={styles.checkItem}><span>{label}</span><strong className={ok?styles.checkOk:styles.checkFail}>{ok?'충족':'확인 필요'}</strong></div>)}</div><div className={drawer.sectionTitleLoose}>검수 의견</div><div className={drawer.bodyText}>{selected.reason}</div></DetailDrawer> : <div className={shared.splitEmpty}>왼쪽 목록에서 건을 선택하면<br/>검수 상세가 여기에 표시됩니다.</div>}
      </div>
    </div>
  </div>;
}

export function UserProductModerationPage(){
  const navigate=useNavigate();const[searchParams,setSearchParams]=useSearchParams();const productFilter=searchParams.get('product')??'';
  const [cases,setCases]=useState(PRODUCT_MODERATION_CASES);const[quick,setQuick]=useState<'전체'|ModerationStatus>('전체');const[keyword,setKeyword]=useState('');const[search,setSearch]=useState('');const[source,setSource]=useState('');const[selectedId,setSelectedId]=useState<string|null>(null);
  const filtered=useMemo(()=>cases.filter((item)=>(!productFilter||item.productId===productFilter)&&(quick==='전체'||item.status===quick)&&(!source||item.source===source)&&(!search||(()=>{const p=productById(item.productId);return `${item.id} ${item.productId} ${p?.title??''} ${item.issue} ${sellerById(p?.sellerId??'')?.nickname??''}`.toLowerCase().includes(search.toLowerCase());})())),[cases,productFilter,quick,search,source]);const selected=cases.find((item)=>item.id===selectedId)??null;const product=selected?productById(selected.productId):null;const seller=product?sellerById(product.sellerId):null;
  const notify=(message:string)=>{showToast({ message, type: 'success' });};const action=(next:'숨김'|'삭제'|'복구')=>{if(!selected)return;setCases((items)=>items.map((item)=>item.id===selected.id?{...item,status:'조치완료',action:next,assignee:item.assignee==='미배정'?'admin01':item.assignee}:item));notify(`${selected.productId} 상품을 ${next} 처리했습니다.`);};const statuses:Array<'전체'|ModerationStatus>=['전체','검토대기','소명중','조치완료'];
  const rows:GridRow[]=filtered.map((item)=>{const p=productById(item.productId);const s=sellerById(p?.sellerId??'');return{id:item.id,onClick:()=>setSelectedId(item.id),cells:[{kind:'stack',title:item.id,subtitle:item.receivedAt},{kind:'thumbTitle',thumb:item.risk==='긴급'?'#fecaca':'#fef3c7',title:p?.title??item.productId,id:item.productId,onClick:()=>setSelectedId(item.id)},{kind:'stack',title:s?.nickname??'-',subtitle:p?.sellerId??'-'},{kind:'pillText',text:item.source,bg:'#f4f4f5',fg:'#52525b'},{kind:'stack',title:item.issue,subtitle:`위험도 ${item.risk}`},{kind:'badge',text:item.status,...MODERATION_META[item.status]},{kind:'text',text:item.action,color:item.action==='삭제'?'#dc2626':undefined},{kind:'text',text:item.assignee,color:item.assignee==='미배정'?'#dc2626':undefined},{kind:'link',text:'검토'}]};});
  return <div className={shared.page}><PageHeading title="노출 / 운영 조치" subtitle="신고와 자동 탐지로 확인된 사용자 상품을 검토하고 숨김·삭제·복구 조치를 처리합니다. 회원 기능 제재는 제재 관리에서 담당합니다."/>
    <Metrics items={[{label:'검토 대기',value:`${cases.filter((c)=>c.status==='검토대기').length}건`,note:'담당자 확인 필요',tone:'down',dot:'#f59e0b'},{label:'판매자 소명중',value:`${cases.filter((c)=>c.status==='소명중').length}건`,note:'자료 제출 대기',dot:'#8b5cf6'},{label:'긴급 위험',value:`${cases.filter((c)=>c.risk==='긴급'&&c.status!=='조치완료').length}건`,note:'우선 조치 대상',tone:'down',dot:'#ef4444'},{label:'조치 완료',value:`${cases.filter((c)=>c.status==='조치완료').length}건`,note:'숨김·삭제·복구',tone:'up',dot:'#10b981'}]}/>
    <ControlArea><div className={shared.quickFilters}>{statuses.map((item) => {
      const active = quick === item;
      return (
        <CommonButton
          type="button"
          key={item}
          variant={active ? 'primary-light' : 'secondary'}
          size="md"
          className={`${shared.qfBtn} ${active ? base.quickActive : ''}`}
          onClick={() => setQuick(item)}
        >
          <span className={shared.qfLabel}>{item}</span>
          <span className={shared.qfCount}>{cases.filter((c) => item === '전체' || c.status === item).length}</span>
        </CommonButton>
      );
    })}</div><FilterBox><form className={shared.filterRow1} onSubmit={(e)=>{e.preventDefault();setSearch(keyword.trim());}}><label className="globalFilterField"><span>검색 범위</span><select aria-label="검색 범위" className={shared.selectSm}><option>통합 검색</option><option>사건번호</option><option>상품명</option><option>판매자</option></select></label><input className={shared.searchInput} value={keyword} onChange={(e)=>setKeyword(e.target.value)} placeholder={productFilter?`${productFilter} 상품의 조치 건만 표시 중`:'사건번호 / 상품 / 판매자 / 탐지 사유'}/><button className={shared.searchBtn}>조회</button></form><div className={shared.filterRow2}><label className="globalFilterField"><span>유입 경로</span><select aria-label="유입 경로" className={shared.selectSm} value={source} onChange={(e)=>setSource(e.target.value)}><option value="">전체 유입 경로</option><option>회원 신고</option><option>자동 탐지</option><option>운영 모니터링</option></select></label><label className={shared.dateFilterField}><span>접수일</span><div className={shared.dateRange}><DatePicker className={shared.selectSm} defaultValue="2026-08-01"/><span className={shared.dateSeparator}>~</span><DatePicker className={shared.selectSm} defaultValue="2026-08-27"/></div></label><span className={shared.rowSpacer}/><button type="button" className={shared.resetBtn} onClick={()=>{setKeyword('');setSearch('');setSource('');setSearchParams(new URLSearchParams(),{replace:true});}}>초기화</button></div></FilterBox></ControlArea>
    <div className={shared.splitRow}>
      <div className={shared.splitListCol}>
        <GridArea><ResultBar count={filtered.length} unit="건"/><DataGrid columns={[{label:'사건번호 / 접수일'},{label:'상품'},{label:'판매자'},{label:'유입 경로'},{label:'탐지·신고 사유'},{label:'처리 상태'},{label:'조치'},{label:'담당자'},{label:'관리'}]} rows={rows} gridTemplate="125px minmax(195px,1.3fr) 72px 82px minmax(175px,1.2fr) 80px 48px 70px 55px" minWidth="980px" empty={!filtered.length} emptyText="조건에 맞는 상품 운영 조치 건이 없습니다." showPagination pages={pages} rangeLabel={filtered.length?`1–${filtered.length} / ${filtered.length}`:'0건'}/></GridArea>
      </div>
      <div className={shared.splitDetailCol}>
        {selected&&product&&seller ? <DetailDrawer variant="panel" eyebrow={`상품 조치 검토 · ${selected.id}`} title={product.title} status={selected.status} statusMeta={MODERATION_META[selected.status]} subtitle={`${selected.source} · 위험도 ${selected.risk}`} onClose={()=>setSelectedId(null)} actions={<>{selected.source==='자동 탐지'&&<button type="button" className={drawer.actionLink} onClick={()=>navigate(`/c2c/product-policy/detection-history?product=${encodeURIComponent(product.id)}`)}>탐지 근거</button>}<button type="button" className={drawer.actionLink} onClick={()=>action('숨김')}>상품 숨김</button><button type="button" className={drawer.primaryBtn} onClick={()=>action('복구')}>노출 복구</button><span className={drawer.spacer}/><button type="button" className={drawer.dangerBtn} onClick={()=>action('삭제')}>상품 삭제</button></>} stats={[{label:'신고',value:`${product.reportCount}건`},{label:'현재 조치',value:selected.action},{label:'담당자',value:selected.assignee}]} fields={[{label:'상품 ID',value:product.id},{label:'판매자',value:`${seller.nickname} (${seller.id})`},{label:'유입 경로',value:selected.source},{label:'접수일',value:selected.receivedAt},{label:'노출 상태',value:product.exposure},{label:'판매 상태',value:product.status}]}><div className={drawer.sectionTitleLoose}>탐지 / 신고 내용</div><div className={styles.issueCard}>{selected.issue}</div><div className={drawer.sectionTitleLoose}>처리 참고</div><div className={styles.sourceBox}><div><span>위험도</span><strong>{selected.risk}</strong></div><div><span>판매자 소명</span><strong>{selected.appeal}</strong></div></div></DetailDrawer> : <div className={shared.splitEmpty}>왼쪽 목록에서 건을 선택하면<br/>조치 상세가 여기에 표시됩니다.</div>}
      </div>
    </div>
  </div>;
}

export function UserProductHistoryPage(){
  const [keyword,setKeyword]=useState('');const[search,setSearch]=useState('');const[action,setAction]=useState('');const[actor,setActor]=useState('');const[selectedId,setSelectedId]=useState<string|null>(null);
  const filtered=useMemo(()=>USER_PRODUCT_HISTORY.filter((item)=>(!action||item.action.includes(action))&&(!actor||(actor==='SYSTEM'?item.actor==='SYSTEM':item.actor!=='SYSTEM'))&&(!search||(()=>{const p=productById(item.productId);return `${item.id} ${item.productId} ${p?.title??''} ${item.reason} ${item.source} ${item.actor}`.toLowerCase().includes(search.toLowerCase());})())),[action,actor,search]);const selected=USER_PRODUCT_HISTORY.find((item)=>item.id===selectedId)??null;const product=selected?productById(selected.productId):null;const seller=product?sellerById(product.sellerId):null;
  const rows:GridRow[]=filtered.map((item)=>{const p=productById(item.productId);const s=sellerById(p?.sellerId??'');return{id:item.id,onClick:()=>setSelectedId(item.id),cells:[{kind:'text',text:item.occurredAt,numeric:true},{kind:'stack',title:item.action,subtitle:item.id},{kind:'thumbTitle',thumb:'#e0e7ff',title:p?.title??item.productId,id:item.productId,onClick:()=>setSelectedId(item.id)},{kind:'stack',title:s?.nickname??'-',subtitle:p?.sellerId??'-'},{kind:'text',text:item.before,color:'#71717a'},{kind:'text',text:`→ ${item.after}`,weight:600},{kind:'stack',title:item.actor,subtitle:item.source},{kind:'text',text:item.reason},{kind:'link',text:'상세'}]};});
  return <div className={shared.page}><PageHeading title="사용자 상품 처리 이력" subtitle="상품 등록·검수·노출·숨김·삭제·복구 과정의 변경 전후 값과 처리 근거를 조회합니다." action={<button type="button" className={shared.downloadBtn} onClick={()=>downloadCsv('사용자상품-처리이력.csv',['발생일시','상품 ID','처리','변경 전','변경 후','처리자','근거','사유'],filtered.map((item)=>[item.occurredAt,item.productId,item.action,item.before,item.after,item.actor,item.source,item.reason]))}>이력 다운로드</button>}/>
    <ControlArea><FilterBox><form className={shared.filterRow1} onSubmit={(e)=>{e.preventDefault();setSearch(keyword.trim());}}><label className="globalFilterField"><span>검색 범위</span><select aria-label="검색 범위" className={shared.selectSm}><option>통합 검색</option><option>로그 ID</option><option>상품 ID</option><option>상품명</option><option>처리자</option></select></label><input className={shared.searchInput} value={keyword} onChange={(e)=>setKeyword(e.target.value)} placeholder="로그 ID / 상품 / 판매자 / 처리 사유"/><button className={shared.searchBtn}>조회</button></form><div className={shared.filterRow2}><label className="globalFilterField"><span>처리 유형</span><select aria-label="처리 유형" className={shared.selectSm} value={action} onChange={(e)=>setAction(e.target.value)}><option value="">전체 처리 유형</option><option value="승인">승인</option><option value="반려">반려</option><option value="숨김">숨김</option><option value="삭제">삭제</option><option value="복구">복구</option><option value="수정">정보 수정</option></select></label><label className="globalFilterField"><span>처리 주체</span><select aria-label="처리 주체" className={shared.selectSm} value={actor} onChange={(e)=>setActor(e.target.value)}><option value="">전체 처리 주체</option><option>관리자 / 판매자</option><option value="SYSTEM">SYSTEM</option></select></label><label className={shared.dateFilterField}><span>처리일</span><div className={shared.dateRange}><DatePicker mode="datetime-local" className={shared.selectSm} defaultValue="2026-08-20T00:00"/><span className={shared.dateSeparator}>~</span><DatePicker mode="datetime-local" className={shared.selectSm} defaultValue="2026-08-27T23:59"/></div></label><span className={shared.rowSpacer}/><button type="button" className={shared.resetBtn} onClick={()=>{setKeyword('');setSearch('');setAction('');setActor('');}}>초기화</button></div></FilterBox></ControlArea>
    <GridArea><ResultBar count={filtered.length} unit="건"/><DataGrid columns={[{label:'발생일시'},{label:'처리 / 로그 ID'},{label:'상품'},{label:'판매자'},{label:'변경 전'},{label:'변경 후'},{label:'처리자 / 근거'},{label:'처리 사유'},{label:'관리'}]} rows={rows} gridTemplate="128px 106px minmax(190px,1.3fr) 84px 72px 88px 110px minmax(160px,1.1fr) 55px" minWidth="970px" empty={!filtered.length} emptyText="조건에 맞는 상품 처리 이력이 없습니다." showPagination pages={pages} rangeLabel={filtered.length?`1–${filtered.length} / ${filtered.length}`:'0건'}/></GridArea>
    {selected&&product&&seller&&<DetailDrawer eyebrow={`상품 처리 로그 · ${selected.id}`} title={selected.action} status="처리 이력" statusMeta={{bg:'#f4f4f5',fg:'#52525b'}} subtitle={`${product.title} · ${selected.occurredAt}`} onClose={()=>setSelectedId(null)} stats={[{label:'상품',value:product.id},{label:'판매자',value:seller.nickname},{label:'처리자',value:selected.actor}]} fields={[{label:'처리 근거',value:selected.source},{label:'발생 일시',value:selected.occurredAt},{label:'카테고리',value:product.category},{label:'판매가',value:formatWon(product.price)}]}><div className={drawer.sectionTitleLoose}>변경 내용</div><div className={base.compare}><b>{selected.before}</b><span className={base.arrow}>→</span><span className={base.after}>{selected.after}</span></div><div className={drawer.sectionTitleLoose}>처리 사유</div><div className={base.warningBox}>{selected.reason}</div></DetailDrawer>}
  </div>;
}
