import { useState } from 'react';
import drawer from '../ops/opsDrawerShared.module.css';
import styles from './InboundManagementPage.module.css';
import { hasInboundIssue, inboundTotals, isDelayed, itemTotals, type InboundRecord } from './inboundData';

type Tab = 'summary' | 'items' | 'receipts' | 'inspection' | 'stock' | 'related' | 'memo' | 'history';
interface Props { record: InboundRecord; onClose: () => void; onProcess: () => void; onCancel: () => void; onCloseRemaining: () => void; onAddMemo: (content:string) => void; }
const STATUS_META: Record<InboundRecord['status'], {bg:string;fg:string}> = {작성중:{bg:'#f4f4f5',fg:'#52525b'},'입고 예정':{bg:'#eff6ff',fg:'#2563eb'},'입고 진행':{bg:'#f5f3ff',fg:'#7c3aed'},'부분 입고':{bg:'#fff7ed',fg:'#c2410c'},'입고 완료':{bg:'#ecfdf5',fg:'#047857'},취소:{bg:'#f4f4f5',fg:'#71717a'}};

export function InboundDetailDrawer({record,onClose,onProcess,onCancel,onCloseRemaining,onAddMemo}:Props){
  const [tab,setTab]=useState<Tab>('summary'); const [memoText,setMemoText]=useState(''); const totals=inboundTotals(record); const pendingInspection=Math.max(totals.arrived-totals.normal-totals.defective-totals.excluded,0); const meta=STATUS_META[record.status]; const canProcess=!['입고 완료','취소'].includes(record.status); const canCancel=record.receipts.every((value)=>value.items.every((line)=>line.arrived===0))&&!['입고 완료','취소'].includes(record.status);
  return <aside className={`${drawer.aside} ${styles.detailDrawer}`}><div className={drawer.head}><div className={drawer.headRow}><div className={drawer.headBody}><div className={drawer.eyebrow}>입고 상세</div><div className={drawer.titleRow}><h2 className={drawer.title}>{record.id}</h2><span className={drawer.badge} style={{background:meta.bg,color:meta.fg}}>{record.status}</span>{isDelayed(record)&&<span className={styles.delayBadge}>⚠ 입고 지연</span>}{hasInboundIssue(record)&&<span className={styles.issueBadge}>확인 필요</span>}</div><div className={drawer.sub}>{record.type} · {record.warehouse} · {record.supplier}</div></div><button type="button" className={drawer.closeBtn} onClick={onClose}>✕</button></div>
    <div className={styles.summaryGrid}><Stat label="예정" value={totals.planned}/><Stat label="누적 도착" value={totals.arrived}/><Stat label="정상 입고" value={totals.normal}/><Stat label="불량" value={totals.defective} tone={totals.defective?'danger':undefined}/><Stat label="미입고" value={totals.remaining} tone={totals.remaining?'warn':undefined}/><Stat label="재고 반영" value={totals.reflected} tone="accent"/></div>
    <div className={drawer.actionRow}><button type="button" className={drawer.actionLink} onClick={()=>window.location.assign('/inventory/status')}>현재 재고 보기 ↗</button><span className={drawer.spacer}/>{canCancel&&<button type="button" className={drawer.dangerBtn} onClick={onCancel}>입고 취소</button>}{canProcess&&totals.arrived>0&&totals.remaining>0&&<button type="button" className={drawer.actionLink} onClick={onCloseRemaining}>잔여 입고 종료</button>}{canProcess&&<button type="button" className={drawer.primaryBtn} onClick={onProcess}>{totals.arrived?'추가 입고 처리':'입고 처리'}</button>}</div>
    <div className={drawer.tabs}>{([['summary','개요'],['items',`입고 상품 ${record.items.length}`],['receipts',`처리 내역 ${record.receipts.length}`],['inspection','검수 결과'],['stock','재고 반영'],['related','관련 발주'],['memo','관리자 메모'],['history','처리 이력']] as [Tab,string][]).map(([key,label])=><button key={key} type="button" className={`${drawer.tabBtn} ${tab===key?drawer.tabActive:''}`} onClick={()=>setTab(key)}>{label}</button>)}</div></div>
    <div className={drawer.scroll}>{hasInboundIssue(record)&&<div className={styles.issuePanel}><strong>확인할 입고 항목이 있습니다.</strong>{isDelayed(record)&&<span>예정일이 지났지만 미입고 수량이 남아 있습니다.</span>}{pendingInspection>0&&<span>도착 {pendingInspection}개의 검수 결과가 아직 확정되지 않았습니다.</span>}{totals.defective>0&&<span>불량 {totals.defective}개는 판매 재고에 반영되지 않았습니다.</span>}{totals.over>0&&<span>예정 수량보다 {totals.over}개 초과 입고되었습니다.</span>}{record.closedRemaining&&totals.remaining>0&&<span>잔여 {totals.remaining}개는 “{record.closedReason}” 사유로 종료되었습니다.</span>}</div>}
      {tab==='summary'&&<><h3 className={drawer.sectionTitle}>기본 정보</h3><div className={drawer.fieldBox}><Info label="입고 유형" value={record.type}/><Info label="입고 예정일" value={record.expectedDate}/><Info label="일정 상태" value={isDelayed(record)?'지연':'정상'}/><Info label="입고 창고" value={record.warehouse}/><Info label="공급처" value={record.supplier}/><Info label="담당자" value={record.manager}/><Info label="등록일" value={record.createdAt}/><Info label="최종 처리" value={record.updatedAt}/></div><div className={styles.ruleNote}>입고 예정 수량은 현재고에 포함되지 않습니다. 입고 처리에서 검수된 정상 수량만 Transaction으로 재고에 반영됩니다.</div></>}
      {tab==='items'&&<><div className={`${styles.itemTable} ${styles.inboundItemTable}`}><div className={`${styles.itemHead} ${styles.inboundItemGrid}`}><span>상품 / SKU</span><span>예정</span><span>도착</span><span>정상</span><span>불량</span><span>미입고</span><span>상태</span></div>{record.items.map((line)=>{const sum=itemTotals(record,line.skuId);const status=sum.over?'초과':sum.remaining===0?'완료':sum.arrived?'부분':'예정';return <div key={line.skuId} className={`${styles.itemRow} ${styles.inboundItemGrid}`}><div><strong>{line.productName}</strong><span>{line.sku} · {line.option}</span></div><b>{sum.planned}</b><b>{sum.arrived}</b><b>{sum.normal}</b><b className={sum.defective?styles.dangerText:''}>{sum.defective}</b><b>{sum.remaining}</b><em className={styles.inlineStatus}>{status}</em></div>})}</div></>}
      {tab==='receipts'&&<>{record.receipts.length?record.receipts.map((entry)=><div key={entry.id} className={styles.receiptCard}><div className={styles.receiptTop}><div><strong>{entry.sequence}차 입고</strong><span>{entry.id}</span></div><div><b>{entry.receivedAt}</b><span>{entry.actor}</span></div></div>{entry.items.map((line)=>{const sku=record.items.find((value)=>value.skuId===line.skuId);return <div key={line.skuId} className={styles.receiptLine}><span>{sku?.sku}</span><span>도착 {line.arrived}</span><b>정상 {line.normal}</b><span className={line.defective?styles.dangerText:''}>불량 {line.defective}</span><span>제외 {line.excluded}</span></div>})}{entry.memo&&<p>{entry.memo}</p>}</div>):<div className={styles.emptyPanel}>아직 처리된 입고 차수가 없습니다.</div>}</>}
      {tab==='inspection'&&<>{record.receipts.length?<div className={styles.itemTable}><div className={styles.inspectionSummary}><Stat label="누적 도착" value={totals.arrived}/><Stat label="정상" value={totals.normal} tone="accent"/><Stat label="불량" value={totals.defective} tone={totals.defective?'danger':undefined}/><Stat label="기타 제외" value={totals.excluded}/></div>{record.receipts.map((entry)=><div key={entry.id} className={styles.inspectionLine}><strong>{entry.sequence}차 · {entry.receivedAt}</strong><span>도착 {entry.items.reduce((sum,line)=>sum+line.arrived,0)}</span><span>정상 {entry.items.reduce((sum,line)=>sum+line.normal,0)}</span><span className={entry.items.some((line)=>line.defective)?styles.dangerText:''}>불량 {entry.items.reduce((sum,line)=>sum+line.defective,0)}</span><span>제외 {entry.items.reduce((sum,line)=>sum+line.excluded,0)}</span></div>)}</div>:<div className={styles.emptyPanel}>아직 검수 결과가 없습니다.</div>}<div className={styles.ruleNote}>도착 수량 = 정상 + 불량 + 기타 제외입니다. 정상 수량만 판매 가능한 현재고에 반영됩니다.</div></>}
      {tab==='stock'&&<>{record.receipts.some((entry)=>entry.items.some((line)=>line.normal>0))?record.receipts.flatMap((entry)=>entry.items.map((line)=>({entry,line}))).filter(({line})=>line.normal>0).map(({entry,line})=>{const sku=record.items.find((value)=>value.skuId===line.skuId)!;const priorReceipts=record.receipts.filter((value)=>value.sequence<entry.sequence).flatMap((value)=>value.items).filter((value)=>value.skuId===line.skuId).reduce((sum,value)=>sum+value.normal,0);const before=sku.beforeStock+priorReceipts;return <div key={`${entry.id}-${line.skuId}`} className={styles.stockCard}><div><strong>{sku.productName}</strong><span>{sku.sku} · {entry.receivedAt}</span></div><div className={styles.stockFlow}><span>입고 전 <b>{before}</b></span><i>+</i><span>정상 입고 <b>{line.normal}</b></span><i>→</i><span>입고 후 <b>{before+line.normal}</b></span></div><button type="button" onClick={()=>window.location.assign('/inventory/history')}>{line.movementId??'ST-신규'} · 변동 보기 ↗</button></div>}):<div className={styles.emptyPanel}>아직 재고에 반영된 정상 입고 수량이 없습니다.</div>}<div className={styles.ruleNote}>완료된 입고의 수량은 직접 수정하지 않습니다. 오류 정정은 재고 조정 또는 반제 Transaction으로 남겨야 합니다.</div></>}
      {tab==='related'&&<><div className={drawer.fieldBox}><Info label="관련 발주" value={record.purchaseOrder??'-'}/><Info label="발주 수량" value={record.purchaseOrder?`${totals.planned}개`:'-'}/><Info label="누적 도착" value={`${totals.arrived}개`}/><Info label="미입고" value={`${totals.remaining}개`}/><Info label="관련 반품" value={record.returnReference??'-'}/><Info label="외부 입고번호" value={record.supplierReference??'-'}/></div>{record.purchaseOrder&&<button type="button" className={styles.fullLink} onClick={()=>window.location.assign('/orders/purchase')}>발주 상세 보기 ↗</button>}</>}
      {tab==='memo'&&<><h3 className={drawer.sectionTitle}>등록 시 메모</h3><div className={drawer.bodyText}>{record.memo||'등록된 메모가 없습니다.'}</div><h3 className={drawer.sectionTitle}>관리자 메모</h3>{record.adminMemos?.length?record.adminMemos.map((memo)=><div key={memo.id} className={styles.adminMemo}><div><strong>{memo.actor}</strong><span>{memo.at}</span></div><p>{memo.content}</p></div>):<div className={styles.emptyPanel}>추가된 관리자 메모가 없습니다.</div>}<div className={styles.memoComposer}><textarea value={memoText} onChange={(event)=>setMemoText(event.target.value)} placeholder="추가 납품 일정 등 내부 메모를 입력하세요."/><button type="button" onClick={()=>{if(!memoText.trim())return;onAddMemo(memoText.trim());setMemoText('')}}>등록</button></div>{record.cancelReason&&<div className={styles.cancelPanel}><strong>취소 사유</strong><span>{record.cancelReason}</span></div>}</>}
      {tab==='history'&&record.history.map((entry,index)=><div key={`${entry.at}-${index}`} className={drawer.timelineItem}><span className={drawer.timelineDot}/><div className={drawer.timelineBody}><div className={drawer.timelineRow}><strong className={drawer.timelineTitle}>{entry.title}</strong><span className={drawer.timelineWhen}>{entry.at}</span></div><div className={drawer.timelineDetail}>{entry.detail} · {entry.actor}</div></div></div>)}
    </div></aside>;
}
function Stat({label,value,tone}:{label:string;value:number;tone?:'warn'|'danger'|'accent'}){return <div className={tone?styles[tone]:''}><span>{label}</span><strong>{value.toLocaleString()}</strong></div>}
function Info({label,value}:{label:string;value:string}){return <div className={drawer.fieldRow}><span className={drawer.fieldLabel}>{label}</span><strong className={drawer.fieldValue}>{value}</strong></div>}
