import { useMemo, useState } from 'react';
import drawer from '../ops/opsDrawerShared.module.css';
import styles from './InventoryStatusPage.module.css';
import { availableStock, inventoryStatus, type InventoryViewRow, type WarehouseStock } from './inventoryData';

type Tab='overview'|'warehouse'|'reserved'|'schedule'|'movement'|'settings';
interface Props{row:InventoryViewRow;onClose:()=>void;onAdjust:()=>void;onSafety:()=>void}
const STATUS_META={정상:{bg:'#ecfdf5',fg:'#047857'},'재고 부족':{bg:'#fff7ed',fg:'#c2410c'},품절:{bg:'#fef2f2',fg:'#dc2626'},미관리:{bg:'#f4f4f5',fg:'#71717a'}};

export function InventoryDetailDrawer({row,onClose,onAdjust,onSafety}:Props){
  const [tab,setTab]=useState<Tab>('overview');const status=inventoryStatus(row);const meta=STATUS_META[status];
  const warehouses=useMemo(()=>{const map=new Map<string,WarehouseStock>();row.sourceSkus.flatMap((sku)=>sku.warehouses).forEach((item)=>{const current=map.get(item.warehouse);map.set(item.warehouse,current?{warehouse:item.warehouse,current:current.current+item.current,reserved:current.reserved+item.reserved,locked:current.locked+item.locked,inboundExpected:current.inboundExpected+item.inboundExpected}:{...item})});return[...map.values()]},[row]);
  const reservations=row.sourceSkus.flatMap((sku)=>sku.reservations.map((item)=>({...item,sku:sku.sku,option:sku.option})));const movements=row.sourceSkus.flatMap((sku)=>sku.movements.map((item)=>({...item,sku:sku.sku}))).sort((a,b)=>b.at.localeCompare(a.at));
  return <aside className={`${drawer.aside} ${styles.detailDrawer}`}><div className={drawer.head}><div className={drawer.headRow}><div className={styles.productThumb} style={{background:row.thumbnail}}>BOX</div><div className={drawer.headBody}><div className={drawer.eyebrow}>{row.productCode}{row.sku?` · ${row.sku}`:''}</div><div className={drawer.titleRow}><h2 className={drawer.title}>{row.productName}</h2><span className={drawer.badge} style={{background:meta.bg,color:meta.fg}}>{status}</span>{row.issues.length>0&&<span className={styles.issueBadge}>⚠ 확인 필요 {row.issues.length}</span>}</div><div className={drawer.sub}>{row.option} · {row.category} · {row.brand} · 판매 상태 {row.saleStatus}</div></div><button type="button" className={drawer.closeBtn} onClick={onClose}>✕</button></div>
    <div className={styles.stockSummary}><div><span>현재고</span><strong>{row.inventoryManaged?row.current.toLocaleString():'-'}</strong></div><div><span>예약재고</span><strong>{row.inventoryManaged?row.reserved.toLocaleString():'-'}</strong></div><div className={styles.availableStat}><span>판매 가능</span><strong className={row.available<=0?styles.stockDanger:row.safety!==null&&row.available<=row.safety?styles.stockWarn:''}>{row.inventoryManaged?row.available.toLocaleString():'무제한'}</strong></div><div><span>안전재고</span><strong>{row.safety?.toLocaleString()??'-'}</strong></div><div><span>입고 예정</span><strong>{row.inboundExpected.toLocaleString()}</strong></div><div><span>출고 예정</span><strong>{row.outboundExpected.toLocaleString()}</strong></div></div>
    <div className={drawer.actionRow}><button type="button" className={drawer.actionLink} onClick={()=>window.location.assign('/products')}>상품 상세 ↗</button>{row.inboundExpected>0&&<button type="button" className={drawer.actionLink} onClick={()=>window.location.assign('/inventory/inbound')}>입고 예정 보기 ↗</button>}<span className={drawer.spacer}/>{row.inventoryManaged&&<button type="button" className={drawer.actionLink} onClick={onSafety}>안전재고 설정</button>}{row.inventoryManaged&&<button type="button" className={drawer.primaryBtn} onClick={onAdjust}>재고 조정</button>}</div>
    <div className={drawer.tabs}>{([['overview','현재 재고'],['warehouse',`창고별 ${warehouses.length}`],['reserved',`예약재고 ${reservations.length}`],['schedule','입출고 예정'],['movement',`최근 변동 ${movements.length}`],['settings','재고 설정']] as [Tab,string][]).map(([key,label])=><button key={key} type="button" className={`${drawer.tabBtn} ${tab===key?drawer.tabActive:''}`} onClick={()=>setTab(key)}>{label}</button>)}</div></div>
    <div className={drawer.scroll}>
      {row.issues.length>0&&<div className={styles.issueBanner}><strong>재고 확인 필요</strong>{row.issues.map((issue)=><span key={issue}>⚠ {issue}</span>)}</div>}
      {tab==='overview'&&<>{!row.inventoryManaged?<div className={styles.unmanagedPanel}><strong>재고 미관리 상품</strong><p>디지털 상품이나 무제한 판매 상품으로, 재고 0개인 품절 상태와 구분됩니다.</p></div>:<><h3 className={drawer.sectionTitle}>판매 가능 재고 계산</h3><div className={styles.calculation}><Calc label="현재고" value={row.current}/><Calc label="예약재고" value={-row.reserved}/><Calc label="기타 잠금" value={-row.locked}/><div className={styles.calcTotal}><span>판매 가능 재고</span><strong>{row.available.toLocaleString()}</strong></div></div><div className={styles.definitionNote}>ⓘ 예약재고는 결제 완료된 주문 기준입니다. 출고 예정은 예약재고 중 출고지시가 생성된 부분집합이며 중복 차감하지 않습니다.</div></>}
      {row.sku===null&&<><h3 className={drawer.sectionTitleLoose}>옵션 / SKU 현황</h3><div className={styles.miniTable}><div className={styles.miniHead}><span>SKU / 옵션</span><span>현재</span><span>예약</span><span>판매 가능</span><span>상태</span></div>{row.sourceSkus.map((sku)=>{const child={inventoryManaged:sku.inventoryManaged,available:availableStock(sku),safety:sku.safety};const childStatus=inventoryStatus(child);return <div key={sku.id} className={styles.miniRow}><span><strong>{sku.sku}</strong><em>{sku.option}</em></span><span>{sku.inventoryManaged?sku.current:'-'}</span><span>{sku.inventoryManaged?sku.reserved:'-'}</span><b>{sku.inventoryManaged?availableStock(sku):'무제한'}</b><i style={{color:STATUS_META[childStatus].fg}}>{childStatus}</i></div>})}</div></>}</>}
      {tab==='warehouse'&&<>{warehouses.length?<><div className={styles.definitionNote}>ⓘ 전체 합계입니다. 실제 주문 가능 수량은 창고별 배송·출고 정책에 따라 달라질 수 있습니다.</div><div className={styles.miniTable}><div className={styles.warehouseHead}><span>창고</span><span>현재고</span><span>예약</span><span>잠금</span><span>판매 가능</span><span>입고 예정</span></div>{warehouses.map((item)=><div key={item.warehouse} className={styles.warehouseRow}><strong>{item.warehouse}</strong><span>{item.current}</span><span>{item.reserved}</span><span>{item.locked}</span><b>{item.current-item.reserved-item.locked}</b><span>{item.inboundExpected}</span></div>)}</div></>:<div className={styles.emptyPanel}>창고 재고를 관리하지 않는 상품입니다.</div>}</>}
      {tab==='reserved'&&<>{reservations.length?<><div className={styles.readOnlyNotice}>예약재고는 주문/출고 Workflow 결과이므로 여기서 직접 수정할 수 없습니다.</div>{reservations.map((item)=><div key={`${item.sku}-${item.orderId}`} className={styles.reservationRow}><div><strong>{item.orderId}</strong><span>{item.sku} · {item.option}</span></div><b>{item.quantity}개</b><em>{item.status}</em><span>{item.reservedAt}</span><button type="button">주문 보기 ↗</button></div>)}</>:<div className={styles.emptyPanel}>현재 예약된 주문 재고가 없습니다.</div>}</>}
      {tab==='schedule'&&<><div className={styles.scheduleGrid}><div><span>입고 예정</span><strong>{row.inboundExpected.toLocaleString()}개</strong><p>{row.inboundCases?`${row.inboundCases}건 · 가장 빠른 일정 ${row.inboundDate}`:'확정 일정 없음'}</p><button type="button" onClick={()=>window.location.assign('/inventory/inbound')}>입고 관리 보기</button></div><div><span>출고 예정</span><strong>{row.outboundExpected.toLocaleString()}개</strong><p>예약재고 {row.reserved}개 중 출고지시 생성 수량</p><button type="button" onClick={()=>window.location.assign('/inventory/outbound')}>출고 관리 보기</button></div></div><div className={styles.readOnlyNotice}>입고 예정과 출고 예정 수량은 해당 업무 화면에서 관리하며 재고 현황에서는 직접 수정하지 않습니다.</div></>}
      {tab==='movement'&&<>{movements.length?movements.map((item)=><div key={`${item.sku}-${item.id}`} className={drawer.timelineItem}><span className={`${styles.movementIcon} ${item.quantity>=0?styles.movePlus:styles.moveMinus}`}>{item.quantity>=0?'+':'−'}</span><div className={drawer.timelineBody}><div className={drawer.timelineRow}><strong className={drawer.timelineTitle}>{item.type} {item.quantity>0?'+':''}{item.quantity}개</strong><span className={drawer.timelineWhen}>{item.at}</span></div><div className={drawer.timelineDetail}>{item.sku} · {item.before} → {item.after} · {item.reference} · {item.actor}{item.reason?` · ${item.reason}`:''}</div></div></div>):<div className={styles.emptyPanel}>기록된 재고 변동이 없습니다.</div>}<button type="button" className={styles.fullLink} onClick={()=>window.location.assign('/inventory/history')}>전체 재고 변동 이력 보기 ↗</button></>}
      {tab==='settings'&&<><div className={drawer.fieldBox}><Info label="재고 관리" value={row.inventoryManaged?'사용':'사용 안 함 · 무제한'}/><Info label="음수재고" value="허용 안 함"/><Info label="예약 시점" value="결제 완료 시"/><Info label="재고 차감" value="출고 완료 시"/><Info label="안전재고" value={row.safety===null?'미설정':`${row.safety}개`}/><Info label="부족 알림" value={row.sourceSkus.some((sku)=>sku.alertEnabled)?'최초 진입 시 알림':'사용 안 함'}/></div>{row.inventoryManaged&&<button type="button" className={styles.fullPrimary} onClick={onSafety}>안전재고 및 알림 설정</button>}<div className={styles.definitionNote}>판매 상태 변경은 상품 관리에서 진행합니다. 판매중지해도 현재 재고 수량은 변경되지 않습니다.</div></>}
    </div>
  </aside>;
}
function Calc({label,value}:{label:string;value:number}){return <div><span>{label}</span><strong className={value<0?styles.minus:''}>{value>0?'+':''}{value.toLocaleString()}</strong></div>}
function Info({label,value}:{label:string;value:string}){return <div className={drawer.fieldRow}><span className={drawer.fieldLabel}>{label}</span><strong className={drawer.fieldValue}>{value}</strong></div>}
