export type InventoryStatus = '정상' | '재고 부족' | '품절' | '미관리';
export type SaleStatus = '판매중' | '판매중지' | '판매예정';
export interface WarehouseStock { warehouse: string; current: number; reserved: number; locked: number; inboundExpected: number; }
export interface Reservation { orderId: string; quantity: number; status: string; reservedAt: string; }
export interface StockMovement { id: string; at: string; type: '입고' | '출고' | '재고 조정' | '예약' | '예약 해제' | '반품 복원'; quantity: number; before: number; after: number; reference: string; actor: string; reason?: string; }
export interface InventorySku {
  id: string; sku: string; option: string; inventoryManaged: boolean; current: number; reserved: number; locked: number; inboundExpected: number; inboundDate: string | null; inboundCases: number; outboundExpected: number; safety: number | null; alertEnabled: boolean;
  saleStatus: SaleStatus; warehouse: string; issues: string[]; lastInboundAt: string | null; lastOutboundAt: string | null; warehouses: WarehouseStock[]; reservations: Reservation[]; movements: StockMovement[];
}
export interface InventoryProduct { id: string; code: string; name: string; category: string; brand: string; saleStatus: SaleStatus; unit: string; thumbnail: string; skus: InventorySku[]; }
export interface InventoryViewRow { id: string; productId: string; productCode: string; productName: string; category: string; brand: string; thumbnail: string; sku: string | null; option: string; skuCount: number; soldOutSkuCount: number; inventoryManaged: boolean; current: number; reserved: number; locked: number; available: number; inboundExpected: number; inboundDate: string | null; inboundCases: number; outboundExpected: number; safety: number | null; saleStatus: SaleStatus; warehouse: string; issues: string[]; lastInboundAt: string | null; lastOutboundAt: string | null; sourceSkus: InventorySku[]; }

const wh=(warehouse:string,current:number,reserved:number,locked:number,inboundExpected=0):WarehouseStock=>({warehouse,current,reserved,locked,inboundExpected});
const mv=(id:string,at:string,type:StockMovement['type'],quantity:number,before:number,after:number,reference:string,actor='system',reason?:string):StockMovement=>({id,at,type,quantity,before,after,reference,actor,reason});
const baseSku=(value:Partial<InventorySku>&Pick<InventorySku,'id'|'sku'|'option'|'current'|'reserved'|'safety'>):InventorySku=>({inventoryManaged:true,locked:0,inboundExpected:0,inboundDate:null,inboundCases:0,outboundExpected:0,alertEnabled:true,saleStatus:'판매중',warehouse:'전체 창고',issues:[],lastInboundAt:'2026-08-25 08:10',lastOutboundAt:'2026-08-26 09:30',warehouses:[wh('수도권 센터',value.current,value.reserved,0)],reservations:[],movements:[],...value});

export const INVENTORY_PRODUCTS:InventoryProduct[]=[
  {id:'PRD-001',code:'P-001',name:'프리미엄 사무용 의자',category:'사무가구',brand:'워크핏',saleStatus:'판매중',unit:'개',thumbnail:'#dbeafe',skus:[
    baseSku({id:'INV-001',sku:'SKU-001-RS',option:'레드 / S',current:20,reserved:5,safety:10,inboundExpected:20,inboundDate:'2026-08-29',inboundCases:1,outboundExpected:3,warehouse:'전체 창고',warehouses:[wh('수도권 센터',12,4,0,20),wh('부산 센터',8,1,0)],reservations:[{orderId:'O-00182',quantity:3,status:'출고대기',reservedAt:'2026-08-26 08:40'},{orderId:'O-00183',quantity:2,status:'주문확정',reservedAt:'2026-08-25 17:20'}],movements:[mv('MOV-101','2026-08-26 09:30','출고',-2,22,20,'O-00180'),mv('MOV-100','2026-08-25 08:10','입고',10,12,22,'IN-00124')]}),
    baseSku({id:'INV-002',sku:'SKU-001-RM',option:'레드 / M',current:0,reserved:0,safety:5,inboundExpected:30,inboundDate:'2026-09-02',inboundCases:2,outboundExpected:0,lastInboundAt:'2026-08-10 11:00',lastOutboundAt:'2026-08-25 16:20',warehouses:[wh('수도권 센터',0,0,0,20),wh('부산 센터',0,0,0,10)],movements:[mv('MOV-110','2026-08-25 16:20','출고',-1,1,0,'O-00179')]}),
    baseSku({id:'INV-003',sku:'SKU-001-BS',option:'블루 / S',current:50,reserved:8,safety:15,outboundExpected:6,warehouses:[wh('수도권 센터',30,5,0),wh('부산 센터',20,3,0)],reservations:[{orderId:'O-00191',quantity:5,status:'배송준비',reservedAt:'2026-08-26 07:20'},{orderId:'O-00192',quantity:3,status:'주문확정',reservedAt:'2026-08-26 08:15'}],movements:[mv('MOV-120','2026-08-26 09:10','예약',-3,45,42,'O-00192')]}),
    baseSku({id:'INV-004',sku:'SKU-001-BM',option:'블루 / M',current:50,reserved:5,safety:15,outboundExpected:3,warehouses:[wh('수도권 센터',50,5,0)],movements:[mv('MOV-130','2026-08-26 08:50','예약',-5,50,45,'O-00193')]})]},
  {id:'PRD-002',code:'P-002',name:'스탠딩 전동 데스크',category:'사무가구',brand:'워크핏',saleStatus:'판매중',unit:'개',thumbnail:'#ede9fe',skus:[
    baseSku({id:'INV-005',sku:'SKU-002-W120',option:'화이트 / 1200',current:12,reserved:8,safety:10,inboundExpected:40,inboundDate:'2026-08-30',inboundCases:1,outboundExpected:6,warehouses:[wh('수도권 센터',12,8,0,40)],reservations:[{orderId:'O-00201',quantity:6,status:'출고대기',reservedAt:'2026-08-26 08:00'},{orderId:'O-00203',quantity:2,status:'주문확정',reservedAt:'2026-08-26 09:00'}],movements:[mv('MOV-140','2026-08-26 09:00','예약',-2,6,4,'O-00203')]}),
    baseSku({id:'INV-006',sku:'SKU-002-B140',option:'블랙 / 1400',current:38,reserved:4,safety:10,outboundExpected:4,warehouses:[wh('수도권 센터',28,4,0),wh('부산 센터',10,0,0)],movements:[mv('MOV-141','2026-08-25 13:10','입고',20,18,38,'IN-00131')]})]},
  {id:'PRD-003',code:'P-003',name:'무선 키보드 세트',category:'IT 액세서리',brand:'키웍스',saleStatus:'판매중',unit:'세트',thumbnail:'#dcfce7',skus:[baseSku({id:'INV-007',sku:'SKU-003-KR',option:'한글 / 블랙',current:0,reserved:3,locked:0,safety:20,inboundExpected:100,inboundDate:'2026-08-28',inboundCases:1,outboundExpected:3,issues:['예약재고 > 현재고','판매가능재고 음수','초과 예약'],lastInboundAt:'2026-08-11 10:30',lastOutboundAt:'2026-08-26 10:05',warehouses:[wh('수도권 센터',0,3,0,100)],reservations:[{orderId:'O-00210',quantity:3,status:'출고보류',reservedAt:'2026-08-26 09:50'}],movements:[mv('MOV-150','2026-08-26 10:05','출고',-3,3,0,'O-00209'),mv('MOV-149','2026-08-26 09:50','예약',-3,3,0,'O-00210')]})]},
  {id:'PRD-004',code:'P-004',name:'A4 복사용지 80g',category:'사무용품',brand:'페이퍼온',saleStatus:'판매중',unit:'박스',thumbnail:'#fef3c7',skus:[baseSku({id:'INV-008',sku:'SKU-004-BOX',option:'2500매 / 1박스',current:2480,reserved:320,safety:500,inboundExpected:1000,inboundDate:'2026-09-01',inboundCases:2,outboundExpected:280,warehouse:'전체 창고',warehouses:[wh('수도권 센터',1600,220,0,600),wh('부산 센터',880,100,0,400)],reservations:[{orderId:'O-00230',quantity:120,status:'출고대기',reservedAt:'2026-08-26 07:50'}],movements:[mv('MOV-160','2026-08-26 09:20','출고',-80,2560,2480,'O-00228'),mv('MOV-159','2026-08-25 15:00','입고',500,2060,2560,'IN-00135')]})]},
  {id:'PRD-005',code:'P-005',name:'기업용 협업 소프트웨어',category:'디지털 상품',brand:'클라우드원',saleStatus:'판매중',unit:'라이선스',thumbnail:'#e4e4e7',skus:[baseSku({id:'INV-009',sku:'SKU-005-LIC',option:'연간 라이선스',inventoryManaged:false,current:0,reserved:0,safety:null,alertEnabled:false,lastInboundAt:null,lastOutboundAt:null,warehouses:[],movements:[]})]},
  {id:'PRD-006',code:'P-006',name:'휴대용 빔프로젝터',category:'IT 기기',brand:'비전빔',saleStatus:'판매중지',unit:'개',thumbnail:'#fee2e2',skus:[baseSku({id:'INV-010',sku:'SKU-006-WH',option:'화이트',current:42,reserved:0,safety:10,saleStatus:'판매중지',outboundExpected:0,warehouses:[wh('수도권 센터',42,0,0)],movements:[mv('MOV-170','2026-08-24 17:00','반품 복원',2,40,42,'RET-00018','admin02','재판매 가능 검수 완료')]})]},
  {id:'PRD-007',code:'P-007',name:'알루미늄 노트북 거치대',category:'IT 액세서리',brand:'오피스픽',saleStatus:'판매중',unit:'개',thumbnail:'#cffafe',skus:[baseSku({id:'INV-011',sku:'SKU-007-SL',option:'실버',current:120,reserved:18,locked:4,safety:30,inboundExpected:0,outboundExpected:12,issues:['출고 완료 재고 미차감'],warehouse:'전체 창고',warehouses:[wh('수도권 센터',80,12,4),wh('부산 센터',40,6,0)],reservations:[{orderId:'O-00240',quantity:12,status:'출고대기',reservedAt:'2026-08-26 08:30'}],movements:[mv('MOV-180','2026-08-26 10:20','출고',-2,122,120,'O-00239'),mv('MOV-179','2026-08-25 18:20','재고 조정',-3,125,122,'ADJ-00031','admin01','재고 실사 차이')]})]},
  {id:'PRD-008',code:'P-008',name:'회의실 화이트보드',category:'사무가구',brand:'보드랩',saleStatus:'판매예정',unit:'개',thumbnail:'#fce7f3',skus:[baseSku({id:'INV-012',sku:'SKU-008-120',option:'1200 × 900',current:0,reserved:0,safety:null,saleStatus:'판매예정',inboundExpected:30,inboundDate:'2026-09-05',inboundCases:1,outboundExpected:0,alertEnabled:false,lastInboundAt:null,lastOutboundAt:null,warehouses:[wh('수도권 센터',0,0,0,30)],movements:[]})]},
];

export function availableStock(sku:InventorySku){return sku.inventoryManaged?sku.current-sku.reserved-sku.locked:0}
export function inventoryStatus(row:Pick<InventoryViewRow,'inventoryManaged'|'available'|'safety'>):InventoryStatus{if(!row.inventoryManaged)return'미관리';if(row.available<=0)return'품절';if(row.safety!==null&&row.available<=row.safety)return'재고 부족';return'정상'}
export function skuRows(products=INVENTORY_PRODUCTS):InventoryViewRow[]{return products.flatMap((product)=>product.skus.map((sku)=>({id:sku.id,productId:product.id,productCode:product.code,productName:product.name,category:product.category,brand:product.brand,thumbnail:product.thumbnail,sku:sku.sku,option:sku.option,skuCount:1,soldOutSkuCount:sku.inventoryManaged&&availableStock(sku)<=0?1:0,inventoryManaged:sku.inventoryManaged,current:sku.current,reserved:sku.reserved,locked:sku.locked,available:availableStock(sku),inboundExpected:sku.inboundExpected,inboundDate:sku.inboundDate,inboundCases:sku.inboundCases,outboundExpected:sku.outboundExpected,safety:sku.safety,saleStatus:sku.saleStatus??product.saleStatus,warehouse:sku.warehouse,issues:sku.issues,lastInboundAt:sku.lastInboundAt,lastOutboundAt:sku.lastOutboundAt,sourceSkus:[sku]})))}
export function productRows(products=INVENTORY_PRODUCTS):InventoryViewRow[]{return products.map((product)=>{const managed=product.skus.filter((sku)=>sku.inventoryManaged);const available=managed.reduce((sum,sku)=>sum+availableStock(sku),0);const dates=managed.map((sku)=>sku.inboundDate).filter(Boolean) as string[];return{id:product.id,productId:product.id,productCode:product.code,productName:product.name,category:product.category,brand:product.brand,thumbnail:product.thumbnail,sku:null,option:`옵션 ${product.skus.length}개`,skuCount:product.skus.length,soldOutSkuCount:managed.filter((sku)=>availableStock(sku)<=0).length,inventoryManaged:managed.length>0,current:managed.reduce((sum,sku)=>sum+sku.current,0),reserved:managed.reduce((sum,sku)=>sum+sku.reserved,0),locked:managed.reduce((sum,sku)=>sum+sku.locked,0),available,inboundExpected:managed.reduce((sum,sku)=>sum+sku.inboundExpected,0),inboundDate:dates.sort()[0]??null,inboundCases:managed.reduce((sum,sku)=>sum+sku.inboundCases,0),outboundExpected:managed.reduce((sum,sku)=>sum+sku.outboundExpected,0),safety:managed.length?managed.reduce((sum,sku)=>sum+(sku.safety??0),0):null,saleStatus:product.saleStatus,warehouse:'전체 창고',issues:[...new Set(managed.flatMap((sku)=>sku.issues))],lastInboundAt:managed.map((sku)=>sku.lastInboundAt).filter(Boolean).sort().at(-1)??null,lastOutboundAt:managed.map((sku)=>sku.lastOutboundAt).filter(Boolean).sort().at(-1)??null,sourceSkus:product.skus}})}
