import { useRef, useState } from 'react';
import drawer from '../ops/opsDrawerShared.module.css';
import styles from './InboundManagementPage.module.css';
import { useOutsideClose } from '../../lib/useOutsideClose';
import { movementDirection, movementIssues, sourcePath, type StockMovementLog } from './stockMovementData';
type Tab='info'|'change'|'source'|'related'|'processing'|'linked'|'memo';
interface Props{record:StockMovementLog;onClose:()=>void;onAddMemo:(content:string)=>void;onOpenLinked:(id:string)=>void}
const TYPE_META:Record<string,{bg:string;fg:string}>={입고:{bg:'#ecfdf5',fg:'#047857'},출고:{bg:'#fef2f2',fg:'#dc2626'},'재고 조정':{bg:'#fff7ed',fg:'#c2410c'},'반품 재입고':{bg:'#ecfeff',fg:'#0e7490'},'주문 예약':{bg:'#eef2ff',fg:'#4f46e5'},'예약 해제':{bg:'#f5f3ff',fg:'#7c3aed'},'출고 반제':{bg:'#ecfdf5',fg:'#047857'},'입고 반제':{bg:'#fef2f2',fg:'#dc2626'},'재고 이동 출고':{bg:'#fef2f2',fg:'#dc2626'},'재고 이동 입고':{bg:'#ecfdf5',fg:'#047857'},'시스템 보정':{bg:'#f4f4f5',fg:'#52525b'}};
export function StockMovementDetailDrawer({record,onClose,onAddMemo,onOpenLinked}:Props){const [tab,setTab]=useState<Tab>('info');const [memo,setMemo]=useState('');const issues=movementIssues(record);const meta=TYPE_META[record.type]??TYPE_META['시스템 보정'];const asideRef=useRef<HTMLElement>(null);useOutsideClose(asideRef,onClose);return <aside ref={asideRef} className={`${drawer.aside} ${styles.detailDrawer}`}><div className={drawer.head}><div className={drawer.headRow}><div className={styles.productThumb} style={{background:record.thumbnail}}>LOG</div><div className={drawer.headBody}><div className={drawer.eyebrow}>재고 변동 상세 · 수정/삭제 불가</div><div className={drawer.titleRow}><h2 className={drawer.title}>{record.id}</h2><span className={drawer.badge} style={{background:meta.bg,color:meta.fg}}>{record.type}</span>{issues.length>0&&<span className={styles.issueBadge}>확인 필요 {issues.length}</span>}</div><div className={drawer.sub}>{record.productName} · {record.sku} · {record.warehouse}</div></div><button type="button" className={drawer.closeBtn} onClick={onClose}>✕</button></div><div className={styles.summaryGrid}><Stat label="변동 전" value={record.currentBefore}/><Stat label="현재고 증감" value={record.currentDelta} signed tone={record.currentDelta<0?'danger':record.currentDelta>0?'accent':undefined}/><Stat label="변동 후" value={record.currentAfter}/><Stat label="예약 증감" value={record.reservedDelta} signed/><Stat label="판매가능 증감" value={record.availableDelta} signed/><div><span>방향</span><strong>{movementDirection(record)}</strong></div></div><div className={drawer.actionRow}><button type="button" className={drawer.actionLink} onClick={()=>window.location.assign('/inventory/status')}>현재 재고 보기 ↗</button>{record.sourceId&&<button type="button" className={drawer.primaryBtn} onClick={()=>window.location.assign(sourcePath(record))}>Source 상세 보기 ↗</button>}</div><div className={drawer.tabs}>{([['info','변동 정보'],['change','재고 변화'],['source','Source'],['related','관련 주문/배송'],['processing','처리 정보'],['linked','연결된 변동'],['memo','관리자 메모']] as [Tab,string][]).map(([key,label])=><button key={key} type="button" className={`${drawer.tabBtn} ${tab===key?drawer.tabActive:''}`} onClick={()=>setTab(key)}>{label}</button>)}</div></div><div className={drawer.scroll}>
 {issues.length>0&&<div className={styles.issuePanel}><strong>원장 무결성 확인이 필요합니다.</strong>{issues.map((issue)=><span key={issue}>⚠ {issue}</span>)}</div>}
 {tab==='info'&&<div className={drawer.fieldBox}><Info label="변동번호" value={record.id}/><Info label="변동 유형" value={record.type}/><Info label="증감 방향" value={movementDirection(record)}/><Info label="상품코드" value={record.productCode}/><Info label="SKU / 옵션" value={`${record.sku} · ${record.option}`}/><Info label="창고" value={record.warehouse}/><Info label="변동일시" value={record.occurredAt}/><Info label="현재 재고" value={`${record.currentNow}개 · 변동 후 수량과 별개`}/></div>}
 {tab==='change'&&<><div className={styles.itemTable}><div className={styles.inspectionLine}><strong>재고 항목</strong><span>변경 전</span><span>변경</span><span>변경 후</span><span>검증</span></div><Change label="현재고" before={record.currentBefore} delta={record.currentDelta} after={record.currentAfter}/><Change label="예약재고" before={record.reservedBefore} delta={record.reservedDelta} after={record.reservedAfter}/><Change label="판매가능재고" before={record.availableBefore} delta={record.availableDelta} after={record.availableAfter}/><Change label="잠금재고" before={record.lockedBefore} delta={record.lockedAfter-record.lockedBefore} after={record.lockedAfter}/></div><div className={styles.ruleNote}>현재고·예약재고·판매가능재고 변화는 한 Transaction으로 묶어 추적합니다. 실제 출고에서는 예약 때 이미 가용재고가 감소해 판매가능 수량 변화가 0일 수 있습니다.</div></>}
 {tab==='source'&&<><div className={drawer.fieldBox}><Info label="Source 유형" value={record.sourceType}/><Info label="Source 번호" value={record.sourceId||'연결 누락'}/><Info label="변동 사유" value={record.reason}/></div>{record.sourceId&&<button type="button" className={styles.fullLink} onClick={()=>window.location.assign(sourcePath(record))}>{record.sourceType} Source 상세 보기 ↗</button>}<div className={styles.ruleNote}>잘못된 이력을 발견해도 원본을 수정하지 않습니다. 원 Source에서 반제 또는 새 재고 조정 Transaction을 생성해야 합니다.</div></>}
 {tab==='related'&&<div className={drawer.fieldBox}><Info label="관련 주문" value={record.orderId??'-'}/><Info label="관련 배송" value={record.shipmentId??'-'}/><Info label="재고 이동 Pair" value={record.transferPairId??'-'}/></div>}
 {tab==='processing'&&<div className={drawer.fieldBox}><Info label="변동 발생" value={record.occurredAt}/><Info label="시스템 기록" value={record.recordedAt}/><Info label="처리자" value={record.actor}/><Info label="처리 주체" value={record.actorType}/><Info label="수정 가능" value="불가 · Audit Log"/><Info label="삭제 가능" value="불가"/></div>}
 {tab==='linked'&&<>{record.linkedMovementId||record.transferPairId?<div className={styles.stockCard}><div><strong>{record.linkedMovementId?'반제/원 변동':'재고 이동 Pair'}</strong><span>{record.linkedMovementId??record.transferPairId}</span></div><button type="button" onClick={()=>onOpenLinked((record.linkedMovementId??record.transferPairId)!)}>연결된 변동 보기 ↗</button></div>:<div className={styles.emptyPanel}>연결된 반제 또는 Pair 변동이 없습니다.</div>}</>}
 {tab==='memo'&&<>{record.adminMemos?.length?record.adminMemos.map((item)=><div key={item.id} className={styles.adminMemo}><div><strong>{item.actor}</strong><span>{item.at}</span></div><p>{item.content}</p></div>):<div className={styles.emptyPanel}>등록된 관리자 메모가 없습니다.</div>}<div className={styles.memoComposer}><textarea value={memo} onChange={(event)=>setMemo(event.target.value)} placeholder="원장 확인 결과 등 별도 메모를 입력하세요."/><button type="button" onClick={()=>{if(!memo.trim())return;onAddMemo(memo.trim());setMemo('')}}>등록</button></div><div className={styles.ruleNote}>관리자 메모는 Audit Transaction 수량과 Source 정보에 영향을 주지 않습니다.</div></>}
 </div></aside>}
function Stat({label,value,signed,tone}:{label:string;value:number;signed?:boolean;tone?:'danger'|'accent'}){return <div className={tone?styles[tone]:''}><span>{label}</span><strong>{signed&&value>0?'+':''}{value.toLocaleString()}</strong></div>}
function Info({label,value}:{label:string;value:string}){return <div className={drawer.fieldRow}><span className={drawer.fieldLabel}>{label}</span><strong className={drawer.fieldValue}>{value}</strong></div>}
function Change({label,before,delta,after}:{label:string;before:number;delta:number;after:number}){const valid=before+delta===after;return <div className={styles.inspectionLine}><strong>{label}</strong><span>{before}</span><span className={delta<0?styles.dangerText:''}>{delta>0?'+':''}{delta}</span><span>{after}</span><span className={valid?'':styles.dangerText}>{valid?'정상':'불일치'}</span></div>}
