import { useState } from 'react';
import drawer from '../ops/opsDrawerShared.module.css';
import styles from './InboundManagementPage.module.css';
import { isOutboundDelayed, outboundIssues, outboundItemTotals, outboundTotals, type StockOutboundRecord } from './outboundData';

type Tab='summary'|'items'|'transactions'|'stock'|'order'|'shipping'|'memo'|'history';
interface Props{record:StockOutboundRecord;onClose:()=>void;onProcess:()=>void;onCancel:()=>void;onCloseRemaining:()=>void}
const META:Record<StockOutboundRecord['status'],{bg:string;fg:string}>={작성중:{bg:'#f4f4f5',fg:'#52525b'},'출고 대기':{bg:'#eff6ff',fg:'#2563eb'},'출고 진행':{bg:'#f5f3ff',fg:'#7c3aed'},'부분 출고':{bg:'#fff7ed',fg:'#c2410c'},'출고 완료':{bg:'#ecfdf5',fg:'#047857'},취소:{bg:'#f4f4f5',fg:'#71717a'}};

export function StockOutboundDetailDrawer({record,onClose,onProcess,onCancel,onCloseRemaining}:Props){const [tab,setTab]=useState<Tab>('summary');const totals=outboundTotals(record);const issues=outboundIssues(record);const meta=META[record.status];const canProcess=!['출고 완료','취소'].includes(record.status);const canCancel=record.transactions.length===0&&!['출고 완료','취소'].includes(record.status);return <aside className={`${drawer.aside} ${styles.detailDrawer}`}><div className={drawer.head}><div className={drawer.headRow}><div className={drawer.headBody}><div className={drawer.eyebrow}>재고 출고 상세 · 배송사 인계 전 재고 Transaction</div><div className={drawer.titleRow}><h2 className={drawer.title}>{record.id}</h2><span className={drawer.badge} style={{background:meta.bg,color:meta.fg}}>{record.status}</span>{isOutboundDelayed(record)&&<span className={styles.delayBadge}>⚠ 출고 지연</span>}{issues.length>0&&<span className={styles.issueBadge}>확인 필요 {issues.length}</span>}</div><div className={drawer.sub}>{record.type} · {record.warehouse} · {record.orderId??record.reason}</div></div><button type="button" className={drawer.closeBtn} onClick={onClose}>✕</button></div><div className={styles.summaryGrid}><Stat label="요청" value={totals.requested}/><Stat label="누적 출고" value={totals.shipped}/><Stat label="미출고" value={totals.remaining} tone={totals.remaining?'warn':undefined}/><Stat label="재고 차감" value={totals.deducted} tone="accent"/><Stat label="예약 해제" value={totals.reservationReleased}/><Stat label="차감 차이" value={totals.difference} tone={totals.difference?'danger':undefined}/></div><div className={drawer.actionRow}><button type="button" className={drawer.actionLink} onClick={()=>window.location.assign('/inventory/status')}>재고 현황 ↗</button><span className={drawer.spacer}/>{canCancel&&<button type="button" className={drawer.dangerBtn} onClick={onCancel}>출고 취소</button>}{canProcess&&totals.shipped>0&&totals.remaining>0&&<button type="button" className={drawer.actionLink} onClick={onCloseRemaining}>잔여 출고 종료</button>}{canProcess&&<button type="button" className={drawer.primaryBtn} onClick={onProcess}>{totals.shipped?'추가 출고 처리':'출고 처리'}</button>}</div><div className={drawer.tabs}>{([['summary','기본 정보'],['items',`출고 상품 ${record.items.length}`],['transactions',`출고 차수 ${record.transactions.length}`],['stock','재고 차감'],['order','관련 주문'],['shipping','관련 배송'],['memo','메모'],['history','처리 이력']] as [Tab,string][]).map(([key,label])=><button key={key} type="button" className={`${drawer.tabBtn} ${tab===key?drawer.tabActive:''}`} onClick={()=>setTab(key)}>{label}</button>)}</div></div><div className={drawer.scroll}>
  {issues.length>0&&<div className={styles.issuePanel}><strong>재고 출고 확인이 필요합니다.</strong>{issues.map((issue)=><span key={issue}>⚠ {issue}</span>)}</div>}
  {tab==='summary'&&<><h3 className={drawer.sectionTitle}>기본 정보</h3><div className={drawer.fieldBox}><Info label="출고 유형" value={record.type}/><Info label="출고 요청일" value={record.requestedAt}/><Info label="출고 예정일" value={record.expectedDate}/><Info label="일정 상태" value={isOutboundDelayed(record)?'지연':'정상'}/><Info label="출고 창고" value={record.warehouse}/><Info label="출고 사유" value={record.reason}/><Info label="담당자" value={record.manager}/><Info label="최종 처리" value={record.updatedAt}/></div><div className={styles.ruleNote}>출고 요청은 현재고를 차감하지 않습니다. 실제 출고 확정 시 현재고를 차감하고 주문 출고라면 같은 수량의 예약재고를 해제합니다.</div></>}
  {tab==='items'&&<div className={styles.itemTable}><div className={styles.itemHead}><span>상품 / SKU</span><span>요청</span><span>누적 출고</span><span>재고 차감</span><span>미출고</span><span>상태</span></div>{record.items.map((line)=>{const sum=outboundItemTotals(record,line.skuId);const status=sum.remaining===0?'완료':sum.shipped?'부분':'대기';return <div key={line.skuId} className={styles.itemRow}><div><strong>{line.productName}</strong><span>{line.sku} · {line.option}</span></div><b>{sum.requested}</b><b>{sum.shipped}</b><b className={sum.shipped!==sum.deducted?styles.dangerText:''}>{sum.deducted}</b><b>{sum.remaining}</b><em className={styles.inlineStatus}>{status}</em></div>})}</div>}
  {tab==='transactions'&&<>{record.transactions.length?record.transactions.map((entry)=><div key={entry.id} className={styles.receiptCard}><div className={styles.receiptTop}><div><strong>{entry.sequence}차 출고</strong><span>{entry.id}</span></div><div><b>{entry.shippedAt}</b><span>{entry.actor}</span></div></div>{entry.items.map((line)=>{const sku=record.items.find((value)=>value.skuId===line.skuId);return <div key={line.skuId} className={styles.receiptLine}><span>{sku?.sku}</span><span>출고 {line.shipped}</span><b>차감 {line.deducted}</b><span>예약 해제 {line.reservationReleased}</span><span>{line.movementId??'이력 누락'}</span></div>})}{entry.memo&&<p>{entry.memo}</p>}</div>):<div className={styles.emptyPanel}>아직 확정된 출고 차수가 없습니다.</div>}</>}
  {tab==='stock'&&<>{record.transactions.some((entry)=>entry.items.some((line)=>line.deducted>0))?record.transactions.flatMap((entry)=>entry.items.map((line)=>({entry,line}))).filter(({line})=>line.shipped>0).map(({entry,line})=>{const sku=record.items.find((value)=>value.skuId===line.skuId)!;const previous=record.transactions.filter((value)=>value.sequence<entry.sequence).flatMap((value)=>value.items).filter((value)=>value.skuId===line.skuId).reduce((sum,value)=>sum+value.deducted,0);const before=sku.currentStock-previous;return <div key={`${entry.id}-${line.skuId}`} className={styles.stockCard}><div><strong>{sku.productName}</strong><span>{sku.sku} · {entry.shippedAt}</span></div><div className={styles.stockFlow}><span>출고 전 <b>{before}</b></span><i>−</i><span>이번 차감 <b>{line.deducted}</b></span><i>→</i><span>출고 후 <b>{before-line.deducted}</b></span></div><button type="button" onClick={()=>window.location.assign('/inventory/history')}>{line.movementId??'재고 변동 누락'} · 변동 보기 ↗</button></div>}):<div className={styles.emptyPanel}>아직 재고 차감 Transaction이 없습니다.</div>}<div className={styles.ruleNote}>완료된 출고를 직접 취소하거나 수량을 덮어쓰지 않습니다. 오류는 원 출고와 연결된 반제 +재고 Transaction으로 정정합니다.</div></>}
  {tab==='order'&&<><div className={drawer.fieldBox}><Info label="관련 주문" value={record.orderId??'주문 외 출고'}/><Info label="주문 상태" value={record.orderStatus??'-'}/><Info label="예약재고 해제" value={`${totals.reservationReleased}개`}/><Info label="잔여 예약" value={`${record.items.reduce((sum,line)=>sum+Math.max(line.reservedStock-outboundItemTotals(record,line.skuId).reservationReleased,0),0)}개`}/></div>{record.orderId&&<button type="button" className={styles.stockCard} onClick={()=>window.location.assign('/orders/processing')}>주문 상세 보기 ↗</button>}</>}
  {tab==='shipping'&&<><div className={drawer.fieldBox}><Info label="관련 배송" value={record.shipmentId??'배송 없음'}/><Info label="배송 상태" value={record.shipmentStatus??'-'}/><Info label="재고 출고 상태" value={record.status}/></div><div className={styles.ruleNote}>이 화면은 창고 재고 차감 업무를 담당합니다. 송장 등록과 배송사 인계는 배송 관리에서 진행합니다.</div>{record.shipmentId&&<button type="button" className={styles.stockCard} onClick={()=>window.location.assign('/delivery/outbound-waiting')}>배송 출고 화면 보기 ↗</button>}</>}
  {tab==='memo'&&<><h3 className={drawer.sectionTitle}>관리자 메모</h3><div className={drawer.bodyText}>{record.memo||'등록된 메모가 없습니다.'}</div>{record.cancelReason&&<div className={styles.cancelPanel}><strong>취소 사유</strong><span>{record.cancelReason}</span></div>}{record.closedReason&&<div className={styles.cancelPanel}><strong>잔여 종료 사유</strong><span>{record.closedReason}</span></div>}</>}
  {tab==='history'&&record.history.map((entry,index)=><div key={`${entry.at}-${index}`} className={drawer.timelineItem}><span className={drawer.timelineDot}/><div className={drawer.timelineBody}><div className={drawer.timelineRow}><strong className={drawer.timelineTitle}>{entry.title}</strong><span className={drawer.timelineWhen}>{entry.at}</span></div><div className={drawer.timelineDetail}>{entry.detail} · {entry.actor}</div></div></div>)}
  </div></aside>}
function Stat({label,value,tone}:{label:string;value:number;tone?:'warn'|'danger'|'accent'}){return <div className={tone?styles[tone]:''}><span>{label}</span><strong>{value.toLocaleString()}</strong></div>}
function Info({label,value}:{label:string;value:string}){return <div className={drawer.fieldRow}><span className={drawer.fieldLabel}>{label}</span><strong className={drawer.fieldValue}>{value}</strong></div>}
